apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.name" . }}-postgresql
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    component: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.name" . }}-dragonfly
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    component: dragonfly
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.name" . }}-questdb
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8812
      targetPort: pgwire
      protocol: TCP
      name: pgwire
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    component: questdb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.name" . }}-redpanda
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    component: redpanda
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.name" . }}-seaweedfs
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8333
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    component: seaweedfs
