apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paryty-frontend
  labels:
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paryty.example.com
      secretName: paryty-tls
  rules:
    - host: paryty.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paryty-frontend
                port:
                  name: http
