// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: paryty/v1/agent.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRegistration is sent by an agent when it first connects.
type AgentRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique agent identifier (UUID).
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Hostname of the node.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// IP addresses of the node.
	IpAddresses []string `protobuf:"bytes,3,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	// Agent version (semver).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// What the agent can collect.
	Capabilities *AgentCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Labels (e.g., environment=prod, region=us-east-1).
	Labels *Labels `protobuf:"bytes,6,opt,name=labels,proto3" json:"labels,omitempty"`
	// When the agent started.
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_paryty_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentRegistration) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *AgentRegistration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRegistration) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentRegistration) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentRegistration) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// AgentRegistrationResponse is returned by the cluster after registration.
type AgentRegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned session ID for this connection.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Server-provided configuration overrides.
	Config *AgentConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Server timestamp for clock synchronization.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistrationResponse) Reset() {
	*x = AgentRegistrationResponse{}
	mi := &file_paryty_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistrationResponse) ProtoMessage() {}

func (x *AgentRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistrationResponse.ProtoReflect.Descriptor instead.
func (*AgentRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRegistrationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentRegistrationResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentRegistrationResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// AgentConfig is pushed from cluster to agent.
type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collection interval override.
	CollectionIntervalMs int32 `protobuf:"varint,1,opt,name=collection_interval_ms,json=collectionIntervalMs,proto3" json:"collection_interval_ms,omitempty"`
	// Sampling rate (0.0 to 1.0).
	SamplingRate float32 `protobuf:"fixed32,2,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	// Whether metal scraper is enabled.
	MetalEnabled bool `protobuf:"varint,3,opt,name=metal_enabled,json=metalEnabled,proto3" json:"metal_enabled,omitempty"`
	// Whether eBPF observer is enabled.
	EbpfEnabled bool `protobuf:"varint,4,opt,name=ebpf_enabled,json=ebpfEnabled,proto3" json:"ebpf_enabled,omitempty"`
	// Whether supervisor is enabled.
	SupervisorEnabled bool `protobuf:"varint,5,opt,name=supervisor_enabled,json=supervisorEnabled,proto3" json:"supervisor_enabled,omitempty"`
	// Compression algorithm to use.
	Compression string `protobuf:"bytes,6,opt,name=compression,proto3" json:"compression,omitempty"`
	// Maximum batch size before forced flush.
	MaxBatchSize int32 `protobuf:"varint,7,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	// Maximum batch age before forced flush (ms).
	MaxBatchAgeMs int32 `protobuf:"varint,8,opt,name=max_batch_age_ms,json=maxBatchAgeMs,proto3" json:"max_batch_age_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_paryty_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetCollectionIntervalMs() int32 {
	if x != nil {
		return x.CollectionIntervalMs
	}
	return 0
}

func (x *AgentConfig) GetSamplingRate() float32 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *AgentConfig) GetMetalEnabled() bool {
	if x != nil {
		return x.MetalEnabled
	}
	return false
}

func (x *AgentConfig) GetEbpfEnabled() bool {
	if x != nil {
		return x.EbpfEnabled
	}
	return false
}

func (x *AgentConfig) GetSupervisorEnabled() bool {
	if x != nil {
		return x.SupervisorEnabled
	}
	return false
}

func (x *AgentConfig) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *AgentConfig) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *AgentConfig) GetMaxBatchAgeMs() int32 {
	if x != nil {
		return x.MaxBatchAgeMs
	}
	return 0
}

// MetricBatch is the top-level message sent from agent to cluster.
type MetricBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent identifier.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Session identifier.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Batch sequence number (for deduplication and ordering).
	SequenceNumber int64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// When the batch was created.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Metal scraper metrics.
	Cpu        *CpuMetric         `protobuf:"bytes,10,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory     *MemoryMetric      `protobuf:"bytes,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks      []*DiskMetric      `protobuf:"bytes,12,rep,name=disks,proto3" json:"disks,omitempty"`
	Interfaces []*NetworkMetric   `protobuf:"bytes,13,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Processes  []*ProcessMetric   `protobuf:"bytes,14,rep,name=processes,proto3" json:"processes,omitempty"`
	Containers []*ContainerMetric `protobuf:"bytes,15,rep,name=containers,proto3" json:"containers,omitempty"`
	// Supervisor data.
	HealthChecks []*HealthCheckResult `protobuf:"bytes,20,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	LogEntries   []*LogEntry          `protobuf:"bytes,21,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	// eBPF observation data.
	NetworkEvents []*NetworkEvent `protobuf:"bytes,30,rep,name=network_events,json=networkEvents,proto3" json:"network_events,omitempty"`
	// Agent self-metrics.
	SelfMetrics   *AgentSelfMetrics `protobuf:"bytes,40,opt,name=self_metrics,json=selfMetrics,proto3" json:"self_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_paryty_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *MetricBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MetricBatch) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MetricBatch) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricBatch) GetCpu() *CpuMetric {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricBatch) GetMemory() *MemoryMetric {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricBatch) GetDisks() []*DiskMetric {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricBatch) GetInterfaces() []*NetworkMetric {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *MetricBatch) GetProcesses() []*ProcessMetric {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *MetricBatch) GetContainers() []*ContainerMetric {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MetricBatch) GetHealthChecks() []*HealthCheckResult {
	if x != nil {
		return x.HealthChecks
	}
	return nil
}

func (x *MetricBatch) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *MetricBatch) GetNetworkEvents() []*NetworkEvent {
	if x != nil {
		return x.NetworkEvents
	}
	return nil
}

func (x *MetricBatch) GetSelfMetrics() *AgentSelfMetrics {
	if x != nil {
		return x.SelfMetrics
	}
	return nil
}

// CpuMetric contains CPU usage data.
type CpuMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU usage percentage (0-100 per core).
	TotalUsagePercent float64 `protobuf:"fixed64,1,opt,name=total_usage_percent,json=totalUsagePercent,proto3" json:"total_usage_percent,omitempty"`
	// Per-core usage percentages.
	PerCorePercent []float64 `protobuf:"fixed64,2,rep,packed,name=per_core_percent,json=perCorePercent,proto3" json:"per_core_percent,omitempty"`
	// Load averages.
	LoadAverage_1M  float64 `protobuf:"fixed64,3,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	LoadAverage_5M  float64 `protobuf:"fixed64,4,opt,name=load_average_5m,json=loadAverage5m,proto3" json:"load_average_5m,omitempty"`
	LoadAverage_15M float64 `protobuf:"fixed64,5,opt,name=load_average_15m,json=loadAverage15m,proto3" json:"load_average_15m,omitempty"`
	// CPU frequency in MHz.
	FrequencyMhz float64 `protobuf:"fixed64,6,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	// Context switches since boot.
	ContextSwitches int64 `protobuf:"varint,7,opt,name=context_switches,json=contextSwitches,proto3" json:"context_switches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuMetric) Reset() {
	*x = CpuMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetric) ProtoMessage() {}

func (x *CpuMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetric.ProtoReflect.Descriptor instead.
func (*CpuMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CpuMetric) GetTotalUsagePercent() float64 {
	if x != nil {
		return x.TotalUsagePercent
	}
	return 0
}

func (x *CpuMetric) GetPerCorePercent() []float64 {
	if x != nil {
		return x.PerCorePercent
	}
	return nil
}

func (x *CpuMetric) GetLoadAverage_1M() float64 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *CpuMetric) GetLoadAverage_5M() float64 {
	if x != nil {
		return x.LoadAverage_5M
	}
	return 0
}

func (x *CpuMetric) GetLoadAverage_15M() float64 {
	if x != nil {
		return x.LoadAverage_15M
	}
	return 0
}

func (x *CpuMetric) GetFrequencyMhz() float64 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *CpuMetric) GetContextSwitches() int64 {
	if x != nil {
		return x.ContextSwitches
	}
	return 0
}

// MemoryMetric contains memory usage data.
type MemoryMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total physical memory in bytes.
	TotalBytes int64 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Used memory in bytes.
	UsedBytes int64 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	// Free memory in bytes.
	FreeBytes int64 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	// Available memory in bytes.
	AvailableBytes int64 `protobuf:"varint,4,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	// Cached memory in bytes.
	CachedBytes int64 `protobuf:"varint,5,opt,name=cached_bytes,json=cachedBytes,proto3" json:"cached_bytes,omitempty"`
	// Buffer memory in bytes.
	BufferBytes int64 `protobuf:"varint,6,opt,name=buffer_bytes,json=bufferBytes,proto3" json:"buffer_bytes,omitempty"`
	// Total swap in bytes.
	SwapTotalBytes int64 `protobuf:"varint,7,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	// Used swap in bytes.
	SwapUsedBytes int64 `protobuf:"varint,8,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`
	// Usage percentage (0-100).
	UsagePercent  float64 `protobuf:"fixed64,9,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetric) Reset() {
	*x = MemoryMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetric) ProtoMessage() {}

func (x *MemoryMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetric.ProtoReflect.Descriptor instead.
func (*MemoryMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryMetric) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryMetric) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryMetric) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *MemoryMetric) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryMetric) GetCachedBytes() int64 {
	if x != nil {
		return x.CachedBytes
	}
	return 0
}

func (x *MemoryMetric) GetBufferBytes() int64 {
	if x != nil {
		return x.BufferBytes
	}
	return 0
}

func (x *MemoryMetric) GetSwapTotalBytes() int64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *MemoryMetric) GetSwapUsedBytes() int64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *MemoryMetric) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// DiskMetric contains disk usage and I/O data for one device.
type DiskMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device name (e.g., "sda", "nvme0n1").
	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Mount point (e.g., "/", "/data").
	MountPoint string `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Filesystem type (e.g., "ext4", "xfs").
	FilesystemType string `protobuf:"bytes,3,opt,name=filesystem_type,json=filesystemType,proto3" json:"filesystem_type,omitempty"`
	// Total space in bytes.
	TotalBytes int64 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Used space in bytes.
	UsedBytes int64 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	// Free space in bytes.
	FreeBytes int64 `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	// Read operations per second.
	ReadOpsPerSec float64 `protobuf:"fixed64,7,opt,name=read_ops_per_sec,json=readOpsPerSec,proto3" json:"read_ops_per_sec,omitempty"`
	// Write operations per second.
	WriteOpsPerSec float64 `protobuf:"fixed64,8,opt,name=write_ops_per_sec,json=writeOpsPerSec,proto3" json:"write_ops_per_sec,omitempty"`
	// Read throughput in bytes/sec.
	ReadBytesPerSec float64 `protobuf:"fixed64,9,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	// Write throughput in bytes/sec.
	WriteBytesPerSec float64 `protobuf:"fixed64,10,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	// Average I/O latency in milliseconds.
	IoLatencyMs float64 `protobuf:"fixed64,11,opt,name=io_latency_ms,json=ioLatencyMs,proto3" json:"io_latency_ms,omitempty"`
	// Queue depth.
	QueueDepth    float64 `protobuf:"fixed64,12,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetric) Reset() {
	*x = DiskMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetric) ProtoMessage() {}

func (x *DiskMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetric.ProtoReflect.Descriptor instead.
func (*DiskMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DiskMetric) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DiskMetric) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetric) GetFilesystemType() string {
	if x != nil {
		return x.FilesystemType
	}
	return ""
}

func (x *DiskMetric) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetric) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetric) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskMetric) GetReadOpsPerSec() float64 {
	if x != nil {
		return x.ReadOpsPerSec
	}
	return 0
}

func (x *DiskMetric) GetWriteOpsPerSec() float64 {
	if x != nil {
		return x.WriteOpsPerSec
	}
	return 0
}

func (x *DiskMetric) GetReadBytesPerSec() float64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *DiskMetric) GetWriteBytesPerSec() float64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

func (x *DiskMetric) GetIoLatencyMs() float64 {
	if x != nil {
		return x.IoLatencyMs
	}
	return 0
}

func (x *DiskMetric) GetQueueDepth() float64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

// NetworkMetric contains network usage data for one interface.
type NetworkMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interface name (e.g., "eth0", "lo").
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Received bytes per second.
	RxBytesPerSec float64 `protobuf:"fixed64,2,opt,name=rx_bytes_per_sec,json=rxBytesPerSec,proto3" json:"rx_bytes_per_sec,omitempty"`
	// Transmitted bytes per second.
	TxBytesPerSec float64 `protobuf:"fixed64,3,opt,name=tx_bytes_per_sec,json=txBytesPerSec,proto3" json:"tx_bytes_per_sec,omitempty"`
	// Received packets per second.
	RxPacketsPerSec float64 `protobuf:"fixed64,4,opt,name=rx_packets_per_sec,json=rxPacketsPerSec,proto3" json:"rx_packets_per_sec,omitempty"`
	// Transmitted packets per second.
	TxPacketsPerSec float64 `protobuf:"fixed64,5,opt,name=tx_packets_per_sec,json=txPacketsPerSec,proto3" json:"tx_packets_per_sec,omitempty"`
	// Receive errors.
	RxErrors int64 `protobuf:"varint,6,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	// Transmit errors.
	TxErrors int64 `protobuf:"varint,7,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	// Receive drops.
	RxDropped int64 `protobuf:"varint,8,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	// Transmit drops.
	TxDropped int64 `protobuf:"varint,9,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	// TCP retransmits.
	TcpRetransmits int64 `protobuf:"varint,10,opt,name=tcp_retransmits,json=tcpRetransmits,proto3" json:"tcp_retransmits,omitempty"`
	// Estimated RTT in milliseconds.
	EstimatedRttMs float64 `protobuf:"fixed64,11,opt,name=estimated_rtt_ms,json=estimatedRttMs,proto3" json:"estimated_rtt_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkMetric) Reset() {
	*x = NetworkMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetric) ProtoMessage() {}

func (x *NetworkMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetric.ProtoReflect.Descriptor instead.
func (*NetworkMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkMetric) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkMetric) GetRxBytesPerSec() float64 {
	if x != nil {
		return x.RxBytesPerSec
	}
	return 0
}

func (x *NetworkMetric) GetTxBytesPerSec() float64 {
	if x != nil {
		return x.TxBytesPerSec
	}
	return 0
}

func (x *NetworkMetric) GetRxPacketsPerSec() float64 {
	if x != nil {
		return x.RxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetric) GetTxPacketsPerSec() float64 {
	if x != nil {
		return x.TxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetric) GetRxErrors() int64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkMetric) GetTxErrors() int64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NetworkMetric) GetRxDropped() int64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NetworkMetric) GetTxDropped() int64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

func (x *NetworkMetric) GetTcpRetransmits() int64 {
	if x != nil {
		return x.TcpRetransmits
	}
	return 0
}

func (x *NetworkMetric) GetEstimatedRttMs() float64 {
	if x != nil {
		return x.EstimatedRttMs
	}
	return 0
}

// ProcessMetric contains per-process data.
type ProcessMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process ID.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Parent PID (0 if none).
	ParentPid int32 `protobuf:"varint,2,opt,name=parent_pid,json=parentPid,proto3" json:"parent_pid,omitempty"`
	// Process name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Command line.
	CommandLine string `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// CPU usage percentage.
	CpuUsagePercent float64 `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	// RSS memory in bytes.
	RssBytes int64 `protobuf:"varint,6,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	// VSZ memory in bytes.
	VszBytes int64 `protobuf:"varint,7,opt,name=vsz_bytes,json=vszBytes,proto3" json:"vsz_bytes,omitempty"`
	// Process status (running, sleeping, stopped, zombie).
	Status string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// Number of threads.
	ThreadCount int32 `protobuf:"varint,9,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	// Number of open file descriptors.
	FdCount int32 `protobuf:"varint,10,opt,name=fd_count,json=fdCount,proto3" json:"fd_count,omitempty"`
	// Container ID (empty if not in container).
	ContainerId string `protobuf:"bytes,11,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Start time.
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetric) Reset() {
	*x = ProcessMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetric) ProtoMessage() {}

func (x *ProcessMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetric.ProtoReflect.Descriptor instead.
func (*ProcessMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessMetric) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetric) GetParentPid() int32 {
	if x != nil {
		return x.ParentPid
	}
	return 0
}

func (x *ProcessMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetric) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessMetric) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ProcessMetric) GetRssBytes() int64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessMetric) GetVszBytes() int64 {
	if x != nil {
		return x.VszBytes
	}
	return 0
}

func (x *ProcessMetric) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessMetric) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *ProcessMetric) GetFdCount() int32 {
	if x != nil {
		return x.FdCount
	}
	return 0
}

func (x *ProcessMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ProcessMetric) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// ContainerMetric contains container detection data.
type ContainerMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (from cgroup).
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Container runtime (docker, podman, containerd).
	Runtime string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Container name (if available).
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Image name.
	Image string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	// Container status.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// cgroup version (v1 or v2).
	CgroupVersion string `protobuf:"bytes,6,opt,name=cgroup_version,json=cgroupVersion,proto3" json:"cgroup_version,omitempty"`
	// Container labels.
	Labels *Labels `protobuf:"bytes,7,opt,name=labels,proto3" json:"labels,omitempty"`
	// Processes in this container.
	Pids          []int32 `protobuf:"varint,8,rep,packed,name=pids,proto3" json:"pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMetric) Reset() {
	*x = ContainerMetric{}
	mi := &file_paryty_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetric) ProtoMessage() {}

func (x *ContainerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetric.ProtoReflect.Descriptor instead.
func (*ContainerMetric) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetric) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ContainerMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerMetric) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerMetric) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerMetric) GetCgroupVersion() string {
	if x != nil {
		return x.CgroupVersion
	}
	return ""
}

func (x *ContainerMetric) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerMetric) GetPids() []int32 {
	if x != nil {
		return x.Pids
	}
	return nil
}

// HealthCheckResult is the result of a single health check.
type HealthCheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health check name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Target URL/address.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Check type (http, tcp, grpc).
	CheckType string `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	// Result status.
	Status HealthStatus `protobuf:"varint,4,opt,name=status,proto3,enum=paryty.v1.HealthStatus" json:"status,omitempty"`
	// Response time in milliseconds.
	ResponseTimeMs float64 `protobuf:"fixed64,5,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	// Error message (if unhealthy).
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// When the check was performed.
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_paryty_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheckResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HealthCheckResult) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealthCheckResult) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResult) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *HealthCheckResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HealthCheckResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// LogEntry is a log line captured by the supervisor.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source file path.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Log level (INFO, WARN, ERROR, DEBUG).
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// Log message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// When the log was written.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Additional structured fields.
	Fields        *Labels `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_paryty_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetFields() *Labels {
	if x != nil {
		return x.Fields
	}
	return nil
}

// AgentSelfMetrics contains metrics about the agent itself.
type AgentSelfMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU usage of the agent process in percent.
	CpuUsagePercent float64 `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	// RSS memory of the agent process in bytes.
	RssBytes int64 `protobuf:"varint,2,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	// Number of goroutines/threads.
	ThreadCount int32 `protobuf:"varint,3,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	// Number of active connections.
	ActiveConnections int32 `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Edge buffer usage in bytes.
	EdgeBufferBytes int64 `protobuf:"varint,5,opt,name=edge_buffer_bytes,json=edgeBufferBytes,proto3" json:"edge_buffer_bytes,omitempty"`
	// Edge buffer entry count.
	EdgeBufferCount int64 `protobuf:"varint,6,opt,name=edge_buffer_count,json=edgeBufferCount,proto3" json:"edge_buffer_count,omitempty"`
	// Uptime in seconds.
	UptimeSeconds int64 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Total batches sent.
	BatchesSent int64 `protobuf:"varint,8,opt,name=batches_sent,json=batchesSent,proto3" json:"batches_sent,omitempty"`
	// Total bytes sent (after compression).
	BytesSent int64 `protobuf:"varint,9,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Total compression ratio.
	CompressionRatio float64 `protobuf:"fixed64,10,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentSelfMetrics) Reset() {
	*x = AgentSelfMetrics{}
	mi := &file_paryty_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSelfMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSelfMetrics) ProtoMessage() {}

func (x *AgentSelfMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSelfMetrics.ProtoReflect.Descriptor instead.
func (*AgentSelfMetrics) Descriptor() ([]byte, []int) {
	return file_paryty_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentSelfMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *AgentSelfMetrics) GetRssBytes() int64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *AgentSelfMetrics) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *AgentSelfMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *AgentSelfMetrics) GetEdgeBufferBytes() int64 {
	if x != nil {
		return x.EdgeBufferBytes
	}
	return 0
}

func (x *AgentSelfMetrics) GetEdgeBufferCount() int64 {
	if x != nil {
		return x.EdgeBufferCount
	}
	return 0
}

func (x *AgentSelfMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AgentSelfMetrics) GetBatchesSent() int64 {
	if x != nil {
		return x.BatchesSent
	}
	return 0
}

func (x *AgentSelfMetrics) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *AgentSelfMetrics) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

var File_paryty_v1_agent_proto protoreflect.FileDescriptor

const file_paryty_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x15paryty/v1/agent.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16paryty/v1/common.proto\x1a\x14paryty/v1/ebpf.proto\"\xaf\x02\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fip_addresses\x18\x03 \x03(\tR\vipAddresses\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12@\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1c.paryty.v1.AgentCapabilitiesR\fcapabilities\x12)\n" +
	"\x06labels\x18\x06 \x01(\v2\x11.paryty.v1.LabelsR\x06labels\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xa7\x01\n" +
	"\x19AgentRegistrationResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x06config\x18\x02 \x01(\v2\x16.paryty.v1.AgentConfigR\x06config\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xd0\x02\n" +
	"\vAgentConfig\x124\n" +
	"\x16collection_interval_ms\x18\x01 \x01(\x05R\x14collectionIntervalMs\x12#\n" +
	"\rsampling_rate\x18\x02 \x01(\x02R\fsamplingRate\x12#\n" +
	"\rmetal_enabled\x18\x03 \x01(\bR\fmetalEnabled\x12!\n" +
	"\febpf_enabled\x18\x04 \x01(\bR\vebpfEnabled\x12-\n" +
	"\x12supervisor_enabled\x18\x05 \x01(\bR\x11supervisorEnabled\x12 \n" +
	"\vcompression\x18\x06 \x01(\tR\vcompression\x12$\n" +
	"\x0emax_batch_size\x18\a \x01(\x05R\fmaxBatchSize\x12'\n" +
	"\x10max_batch_age_ms\x18\b \x01(\x05R\rmaxBatchAgeMs\"\xd7\x05\n" +
	"\vMetricBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x03cpu\x18\n" +
	" \x01(\v2\x14.paryty.v1.CpuMetricR\x03cpu\x12/\n" +
	"\x06memory\x18\v \x01(\v2\x17.paryty.v1.MemoryMetricR\x06memory\x12+\n" +
	"\x05disks\x18\f \x03(\v2\x15.paryty.v1.DiskMetricR\x05disks\x128\n" +
	"\n" +
	"interfaces\x18\r \x03(\v2\x18.paryty.v1.NetworkMetricR\n" +
	"interfaces\x126\n" +
	"\tprocesses\x18\x0e \x03(\v2\x18.paryty.v1.ProcessMetricR\tprocesses\x12:\n" +
	"\n" +
	"containers\x18\x0f \x03(\v2\x1a.paryty.v1.ContainerMetricR\n" +
	"containers\x12A\n" +
	"\rhealth_checks\x18\x14 \x03(\v2\x1c.paryty.v1.HealthCheckResultR\fhealthChecks\x124\n" +
	"\vlog_entries\x18\x15 \x03(\v2\x13.paryty.v1.LogEntryR\n" +
	"logEntries\x12>\n" +
	"\x0enetwork_events\x18\x1e \x03(\v2\x17.paryty.v1.NetworkEventR\rnetworkEvents\x12>\n" +
	"\fself_metrics\x18( \x01(\v2\x1b.paryty.v1.AgentSelfMetricsR\vselfMetrics\"\xaf\x02\n" +
	"\tCpuMetric\x12.\n" +
	"\x13total_usage_percent\x18\x01 \x01(\x01R\x11totalUsagePercent\x12(\n" +
	"\x10per_core_percent\x18\x02 \x03(\x01R\x0eperCorePercent\x12&\n" +
	"\x0fload_average_1m\x18\x03 \x01(\x01R\rloadAverage1m\x12&\n" +
	"\x0fload_average_5m\x18\x04 \x01(\x01R\rloadAverage5m\x12(\n" +
	"\x10load_average_15m\x18\x05 \x01(\x01R\x0eloadAverage15m\x12#\n" +
	"\rfrequency_mhz\x18\x06 \x01(\x01R\ffrequencyMhz\x12)\n" +
	"\x10context_switches\x18\a \x01(\x03R\x0fcontextSwitches\"\xd3\x02\n" +
	"\fMemoryMetric\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x03R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x03R\tfreeBytes\x12'\n" +
	"\x0favailable_bytes\x18\x04 \x01(\x03R\x0eavailableBytes\x12!\n" +
	"\fcached_bytes\x18\x05 \x01(\x03R\vcachedBytes\x12!\n" +
	"\fbuffer_bytes\x18\x06 \x01(\x03R\vbufferBytes\x12(\n" +
	"\x10swap_total_bytes\x18\a \x01(\x03R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\b \x01(\x03R\rswapUsedBytes\x12#\n" +
	"\rusage_percent\x18\t \x01(\x01R\fusagePercent\"\xcb\x03\n" +
	"\n" +
	"DiskMetric\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12'\n" +
	"\x0ffilesystem_type\x18\x03 \x01(\tR\x0efilesystemType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x03R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x03R\tfreeBytes\x12'\n" +
	"\x10read_ops_per_sec\x18\a \x01(\x01R\rreadOpsPerSec\x12)\n" +
	"\x11write_ops_per_sec\x18\b \x01(\x01R\x0ewriteOpsPerSec\x12+\n" +
	"\x12read_bytes_per_sec\x18\t \x01(\x01R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\n" +
	" \x01(\x01R\x10writeBytesPerSec\x12\"\n" +
	"\rio_latency_ms\x18\v \x01(\x01R\vioLatencyMs\x12\x1f\n" +
	"\vqueue_depth\x18\f \x01(\x01R\n" +
	"queueDepth\"\xad\x03\n" +
	"\rNetworkMetric\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12'\n" +
	"\x10rx_bytes_per_sec\x18\x02 \x01(\x01R\rrxBytesPerSec\x12'\n" +
	"\x10tx_bytes_per_sec\x18\x03 \x01(\x01R\rtxBytesPerSec\x12+\n" +
	"\x12rx_packets_per_sec\x18\x04 \x01(\x01R\x0frxPacketsPerSec\x12+\n" +
	"\x12tx_packets_per_sec\x18\x05 \x01(\x01R\x0ftxPacketsPerSec\x12\x1b\n" +
	"\trx_errors\x18\x06 \x01(\x03R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\a \x01(\x03R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\b \x01(\x03R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\t \x01(\x03R\ttxDropped\x12'\n" +
	"\x0ftcp_retransmits\x18\n" +
	" \x01(\x03R\x0etcpRetransmits\x12(\n" +
	"\x10estimated_rtt_ms\x18\v \x01(\x01R\x0eestimatedRttMs\"\x91\x03\n" +
	"\rProcessMetric\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"parent_pid\x18\x02 \x01(\x05R\tparentPid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x12\x1b\n" +
	"\trss_bytes\x18\x06 \x01(\x03R\brssBytes\x12\x1b\n" +
	"\tvsz_bytes\x18\a \x01(\x03R\bvszBytes\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12!\n" +
	"\fthread_count\x18\t \x01(\x05R\vthreadCount\x12\x19\n" +
	"\bfd_count\x18\n" +
	" \x01(\x05R\afdCount\x12!\n" +
	"\fcontainer_id\x18\v \x01(\tR\vcontainerId\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xf6\x01\n" +
	"\x0fContainerMetric\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0ecgroup_version\x18\x06 \x01(\tR\rcgroupVersion\x12)\n" +
	"\x06labels\x18\a \x01(\v2\x11.paryty.v1.LabelsR\x06labels\x12\x12\n" +
	"\x04pids\x18\b \x03(\x05R\x04pids\"\x99\x02\n" +
	"\x11HealthCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.paryty.v1.HealthStatusR\x06status\x12(\n" +
	"\x10response_time_ms\x18\x05 \x01(\x01R\x0eresponseTimeMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"checked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\xb7\x01\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x06fields\x18\x05 \x01(\v2\x11.paryty.v1.LabelsR\x06fields\"\x9b\x03\n" +
	"\x10AgentSelfMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12\x1b\n" +
	"\trss_bytes\x18\x02 \x01(\x03R\brssBytes\x12!\n" +
	"\fthread_count\x18\x03 \x01(\x05R\vthreadCount\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12*\n" +
	"\x11edge_buffer_bytes\x18\x05 \x01(\x03R\x0fedgeBufferBytes\x12*\n" +
	"\x11edge_buffer_count\x18\x06 \x01(\x03R\x0fedgeBufferCount\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fbatches_sent\x18\b \x01(\x03R\vbatchesSent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\t \x01(\x03R\tbytesSent\x12+\n" +
	"\x11compression_ratio\x18\n" +
	" \x01(\x01R\x10compressionRatioB?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_agent_proto_rawDescOnce sync.Once
	file_paryty_v1_agent_proto_rawDescData []byte
)

func file_paryty_v1_agent_proto_rawDescGZIP() []byte {
	file_paryty_v1_agent_proto_rawDescOnce.Do(func() {
		file_paryty_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_agent_proto_rawDesc), len(file_paryty_v1_agent_proto_rawDesc)))
	})
	return file_paryty_v1_agent_proto_rawDescData
}

var file_paryty_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_paryty_v1_agent_proto_goTypes = []any{
	(*AgentRegistration)(nil),         // 0: paryty.v1.AgentRegistration
	(*AgentRegistrationResponse)(nil), // 1: paryty.v1.AgentRegistrationResponse
	(*AgentConfig)(nil),               // 2: paryty.v1.AgentConfig
	(*MetricBatch)(nil),               // 3: paryty.v1.MetricBatch
	(*CpuMetric)(nil),                 // 4: paryty.v1.CpuMetric
	(*MemoryMetric)(nil),              // 5: paryty.v1.MemoryMetric
	(*DiskMetric)(nil),                // 6: paryty.v1.DiskMetric
	(*NetworkMetric)(nil),             // 7: paryty.v1.NetworkMetric
	(*ProcessMetric)(nil),             // 8: paryty.v1.ProcessMetric
	(*ContainerMetric)(nil),           // 9: paryty.v1.ContainerMetric
	(*HealthCheckResult)(nil),         // 10: paryty.v1.HealthCheckResult
	(*LogEntry)(nil),                  // 11: paryty.v1.LogEntry
	(*AgentSelfMetrics)(nil),          // 12: paryty.v1.AgentSelfMetrics
	(*AgentCapabilities)(nil),         // 13: paryty.v1.AgentCapabilities
	(*Labels)(nil),                    // 14: paryty.v1.Labels
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*NetworkEvent)(nil),              // 16: paryty.v1.NetworkEvent
	(HealthStatus)(0),                 // 17: paryty.v1.HealthStatus
}
var file_paryty_v1_agent_proto_depIdxs = []int32{
	13, // 0: paryty.v1.AgentRegistration.capabilities:type_name -> paryty.v1.AgentCapabilities
	14, // 1: paryty.v1.AgentRegistration.labels:type_name -> paryty.v1.Labels
	15, // 2: paryty.v1.AgentRegistration.started_at:type_name -> google.protobuf.Timestamp
	2,  // 3: paryty.v1.AgentRegistrationResponse.config:type_name -> paryty.v1.AgentConfig
	15, // 4: paryty.v1.AgentRegistrationResponse.server_time:type_name -> google.protobuf.Timestamp
	15, // 5: paryty.v1.MetricBatch.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 6: paryty.v1.MetricBatch.cpu:type_name -> paryty.v1.CpuMetric
	5,  // 7: paryty.v1.MetricBatch.memory:type_name -> paryty.v1.MemoryMetric
	6,  // 8: paryty.v1.MetricBatch.disks:type_name -> paryty.v1.DiskMetric
	7,  // 9: paryty.v1.MetricBatch.interfaces:type_name -> paryty.v1.NetworkMetric
	8,  // 10: paryty.v1.MetricBatch.processes:type_name -> paryty.v1.ProcessMetric
	9,  // 11: paryty.v1.MetricBatch.containers:type_name -> paryty.v1.ContainerMetric
	10, // 12: paryty.v1.MetricBatch.health_checks:type_name -> paryty.v1.HealthCheckResult
	11, // 13: paryty.v1.MetricBatch.log_entries:type_name -> paryty.v1.LogEntry
	16, // 14: paryty.v1.MetricBatch.network_events:type_name -> paryty.v1.NetworkEvent
	12, // 15: paryty.v1.MetricBatch.self_metrics:type_name -> paryty.v1.AgentSelfMetrics
	15, // 16: paryty.v1.ProcessMetric.started_at:type_name -> google.protobuf.Timestamp
	14, // 17: paryty.v1.ContainerMetric.labels:type_name -> paryty.v1.Labels
	17, // 18: paryty.v1.HealthCheckResult.status:type_name -> paryty.v1.HealthStatus
	15, // 19: paryty.v1.HealthCheckResult.checked_at:type_name -> google.protobuf.Timestamp
	15, // 20: paryty.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	14, // 21: paryty.v1.LogEntry.fields:type_name -> paryty.v1.Labels
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_paryty_v1_agent_proto_init() }
func file_paryty_v1_agent_proto_init() {
	if File_paryty_v1_agent_proto != nil {
		return
	}
	file_paryty_v1_common_proto_init()
	file_paryty_v1_ebpf_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_agent_proto_rawDesc), len(file_paryty_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paryty_v1_agent_proto_goTypes,
		DependencyIndexes: file_paryty_v1_agent_proto_depIdxs,
		MessageInfos:      file_paryty_v1_agent_proto_msgTypes,
	}.Build()
	File_paryty_v1_agent_proto = out.File
	file_paryty_v1_agent_proto_goTypes = nil
	file_paryty_v1_agent_proto_depIdxs = nil
}
