// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: paryty/v1/anomaly.proto

package parytyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnomalyDetectionService_DetectAnomalies_FullMethodName            = "/paryty.v1.AnomalyDetectionService/DetectAnomalies"
	AnomalyDetectionService_DetectCrossMetricAnomalies_FullMethodName = "/paryty.v1.AnomalyDetectionService/DetectCrossMetricAnomalies"
	AnomalyDetectionService_ExplainAnomaly_FullMethodName             = "/paryty.v1.AnomalyDetectionService/ExplainAnomaly"
	AnomalyDetectionService_GetDetectionStatus_FullMethodName         = "/paryty.v1.AnomalyDetectionService/GetDetectionStatus"
)

// AnomalyDetectionServiceClient is the client API for AnomalyDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnomalyDetectionService provides ML-powered anomaly detection.
type AnomalyDetectionServiceClient interface {
	// Detect anomalies in a single metric.
	DetectAnomalies(ctx context.Context, in *DetectAnomaliesRequest, opts ...grpc.CallOption) (*DetectAnomaliesResponse, error)
	// Detect anomalies across multiple metrics (cross-metric).
	DetectCrossMetricAnomalies(ctx context.Context, in *DetectCrossMetricRequest, opts ...grpc.CallOption) (*DetectCrossMetricResponse, error)
	// Get anomaly explanation.
	ExplainAnomaly(ctx context.Context, in *ExplainAnomalyRequest, opts ...grpc.CallOption) (*ExplainAnomalyResponse, error)
	// Get detection model status.
	GetDetectionStatus(ctx context.Context, in *GetDetectionStatusRequest, opts ...grpc.CallOption) (*GetDetectionStatusResponse, error)
}

type anomalyDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnomalyDetectionServiceClient(cc grpc.ClientConnInterface) AnomalyDetectionServiceClient {
	return &anomalyDetectionServiceClient{cc}
}

func (c *anomalyDetectionServiceClient) DetectAnomalies(ctx context.Context, in *DetectAnomaliesRequest, opts ...grpc.CallOption) (*DetectAnomaliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectAnomaliesResponse)
	err := c.cc.Invoke(ctx, AnomalyDetectionService_DetectAnomalies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyDetectionServiceClient) DetectCrossMetricAnomalies(ctx context.Context, in *DetectCrossMetricRequest, opts ...grpc.CallOption) (*DetectCrossMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectCrossMetricResponse)
	err := c.cc.Invoke(ctx, AnomalyDetectionService_DetectCrossMetricAnomalies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyDetectionServiceClient) ExplainAnomaly(ctx context.Context, in *ExplainAnomalyRequest, opts ...grpc.CallOption) (*ExplainAnomalyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainAnomalyResponse)
	err := c.cc.Invoke(ctx, AnomalyDetectionService_ExplainAnomaly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyDetectionServiceClient) GetDetectionStatus(ctx context.Context, in *GetDetectionStatusRequest, opts ...grpc.CallOption) (*GetDetectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetectionStatusResponse)
	err := c.cc.Invoke(ctx, AnomalyDetectionService_GetDetectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnomalyDetectionServiceServer is the server API for AnomalyDetectionService service.
// All implementations must embed UnimplementedAnomalyDetectionServiceServer
// for forward compatibility.
//
// AnomalyDetectionService provides ML-powered anomaly detection.
type AnomalyDetectionServiceServer interface {
	// Detect anomalies in a single metric.
	DetectAnomalies(context.Context, *DetectAnomaliesRequest) (*DetectAnomaliesResponse, error)
	// Detect anomalies across multiple metrics (cross-metric).
	DetectCrossMetricAnomalies(context.Context, *DetectCrossMetricRequest) (*DetectCrossMetricResponse, error)
	// Get anomaly explanation.
	ExplainAnomaly(context.Context, *ExplainAnomalyRequest) (*ExplainAnomalyResponse, error)
	// Get detection model status.
	GetDetectionStatus(context.Context, *GetDetectionStatusRequest) (*GetDetectionStatusResponse, error)
	mustEmbedUnimplementedAnomalyDetectionServiceServer()
}

// UnimplementedAnomalyDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnomalyDetectionServiceServer struct{}

func (UnimplementedAnomalyDetectionServiceServer) DetectAnomalies(context.Context, *DetectAnomaliesRequest) (*DetectAnomaliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAnomalies not implemented")
}
func (UnimplementedAnomalyDetectionServiceServer) DetectCrossMetricAnomalies(context.Context, *DetectCrossMetricRequest) (*DetectCrossMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectCrossMetricAnomalies not implemented")
}
func (UnimplementedAnomalyDetectionServiceServer) ExplainAnomaly(context.Context, *ExplainAnomalyRequest) (*ExplainAnomalyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainAnomaly not implemented")
}
func (UnimplementedAnomalyDetectionServiceServer) GetDetectionStatus(context.Context, *GetDetectionStatusRequest) (*GetDetectionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetectionStatus not implemented")
}
func (UnimplementedAnomalyDetectionServiceServer) mustEmbedUnimplementedAnomalyDetectionServiceServer() {
}
func (UnimplementedAnomalyDetectionServiceServer) testEmbeddedByValue() {}

// UnsafeAnomalyDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnomalyDetectionServiceServer will
// result in compilation errors.
type UnsafeAnomalyDetectionServiceServer interface {
	mustEmbedUnimplementedAnomalyDetectionServiceServer()
}

func RegisterAnomalyDetectionServiceServer(s grpc.ServiceRegistrar, srv AnomalyDetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedAnomalyDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnomalyDetectionService_ServiceDesc, srv)
}

func _AnomalyDetectionService_DetectAnomalies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectAnomaliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectionServiceServer).DetectAnomalies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyDetectionService_DetectAnomalies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectionServiceServer).DetectAnomalies(ctx, req.(*DetectAnomaliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyDetectionService_DetectCrossMetricAnomalies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectCrossMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectionServiceServer).DetectCrossMetricAnomalies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyDetectionService_DetectCrossMetricAnomalies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectionServiceServer).DetectCrossMetricAnomalies(ctx, req.(*DetectCrossMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyDetectionService_ExplainAnomaly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainAnomalyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectionServiceServer).ExplainAnomaly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyDetectionService_ExplainAnomaly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectionServiceServer).ExplainAnomaly(ctx, req.(*ExplainAnomalyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyDetectionService_GetDetectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectionServiceServer).GetDetectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyDetectionService_GetDetectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectionServiceServer).GetDetectionStatus(ctx, req.(*GetDetectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnomalyDetectionService_ServiceDesc is the grpc.ServiceDesc for AnomalyDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnomalyDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paryty.v1.AnomalyDetectionService",
	HandlerType: (*AnomalyDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectAnomalies",
			Handler:    _AnomalyDetectionService_DetectAnomalies_Handler,
		},
		{
			MethodName: "DetectCrossMetricAnomalies",
			Handler:    _AnomalyDetectionService_DetectCrossMetricAnomalies_Handler,
		},
		{
			MethodName: "ExplainAnomaly",
			Handler:    _AnomalyDetectionService_ExplainAnomaly_Handler,
		},
		{
			MethodName: "GetDetectionStatus",
			Handler:    _AnomalyDetectionService_GetDetectionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paryty/v1/anomaly.proto",
}
