// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paryty/v1/anomaly.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnomalyType classifies the type of anomaly.
type AnomalyType int32

const (
	AnomalyType_ANOMALY_TYPE_UNSPECIFIED AnomalyType = 0
	// Single value anomaly (spike or dip).
	AnomalyType_ANOMALY_TYPE_POINT AnomalyType = 1
	// Unusual given surrounding context.
	AnomalyType_ANOMALY_TYPE_CONTEXTUAL AnomalyType = 2
	// Pattern anomaly across multiple points.
	AnomalyType_ANOMALY_TYPE_COLLECTIVE AnomalyType = 3
	// Trend change (slope shift).
	AnomalyType_ANOMALY_TYPE_TREND AnomalyType = 4
)

// Enum value maps for AnomalyType.
var (
	AnomalyType_name = map[int32]string{
		0: "ANOMALY_TYPE_UNSPECIFIED",
		1: "ANOMALY_TYPE_POINT",
		2: "ANOMALY_TYPE_CONTEXTUAL",
		3: "ANOMALY_TYPE_COLLECTIVE",
		4: "ANOMALY_TYPE_TREND",
	}
	AnomalyType_value = map[string]int32{
		"ANOMALY_TYPE_UNSPECIFIED": 0,
		"ANOMALY_TYPE_POINT":       1,
		"ANOMALY_TYPE_CONTEXTUAL":  2,
		"ANOMALY_TYPE_COLLECTIVE":  3,
		"ANOMALY_TYPE_TREND":       4,
	}
)

func (x AnomalyType) Enum() *AnomalyType {
	p := new(AnomalyType)
	*p = x
	return p
}

func (x AnomalyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyType) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_anomaly_proto_enumTypes[0].Descriptor()
}

func (AnomalyType) Type() protoreflect.EnumType {
	return &file_paryty_v1_anomaly_proto_enumTypes[0]
}

func (x AnomalyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyType.Descriptor instead.
func (AnomalyType) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{0}
}

// DetectAnomaliesRequest requests anomaly detection on a single metric.
type DetectAnomaliesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent to check.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Metric name.
	MetricName string `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Recent values (last N data points).
	Values []float32 `protobuf:"fixed32,4,rep,packed,name=values,proto3" json:"values,omitempty"`
	// Corresponding timestamps (Unix seconds).
	Timestamps []int64 `protobuf:"varint,5,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Detection sensitivity: 0.0 (less sensitive) to 1.0 (more sensitive). Default: 0.5.
	Sensitivity   float32 `protobuf:"fixed32,6,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAnomaliesRequest) Reset() {
	*x = DetectAnomaliesRequest{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAnomaliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAnomaliesRequest) ProtoMessage() {}

func (x *DetectAnomaliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAnomaliesRequest.ProtoReflect.Descriptor instead.
func (*DetectAnomaliesRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{0}
}

func (x *DetectAnomaliesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DetectAnomaliesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DetectAnomaliesRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *DetectAnomaliesRequest) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DetectAnomaliesRequest) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *DetectAnomaliesRequest) GetSensitivity() float32 {
	if x != nil {
		return x.Sensitivity
	}
	return 0
}

// DetectAnomaliesResponse contains detected anomalies.
type DetectAnomaliesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent checked.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Metric name.
	MetricName string `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Detected anomalies.
	Anomalies []*Anomaly `protobuf:"bytes,4,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	// Overall anomaly score: 0.0 (normal) to 1.0 (highly anomalous).
	OverallScore  float32 `protobuf:"fixed32,5,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAnomaliesResponse) Reset() {
	*x = DetectAnomaliesResponse{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAnomaliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAnomaliesResponse) ProtoMessage() {}

func (x *DetectAnomaliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAnomaliesResponse.ProtoReflect.Descriptor instead.
func (*DetectAnomaliesResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{1}
}

func (x *DetectAnomaliesResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DetectAnomaliesResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DetectAnomaliesResponse) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *DetectAnomaliesResponse) GetAnomalies() []*Anomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

func (x *DetectAnomaliesResponse) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

// Anomaly represents a detected anomaly.
type Anomaly struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the anomaly.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Anomalous value.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// Anomaly score: 0.0 - 1.0.
	Score float32 `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	// Type of anomaly.
	Type AnomalyType `protobuf:"varint,4,opt,name=type,proto3,enum=paryty.v1.AnomalyType" json:"type,omitempty"`
	// Human-readable explanation.
	Explanation string `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Contributing factors.
	ContributingFactors []string `protobuf:"bytes,6,rep,name=contributing_factors,json=contributingFactors,proto3" json:"contributing_factors,omitempty"`
	// Detection method that found this anomaly.
	DetectionMethod string `protobuf:"bytes,7,opt,name=detection_method,json=detectionMethod,proto3" json:"detection_method,omitempty"`
	// Severity estimate.
	Severity      Severity `protobuf:"varint,8,opt,name=severity,proto3,enum=paryty.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{2}
}

func (x *Anomaly) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Anomaly) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Anomaly) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Anomaly) GetType() AnomalyType {
	if x != nil {
		return x.Type
	}
	return AnomalyType_ANOMALY_TYPE_UNSPECIFIED
}

func (x *Anomaly) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Anomaly) GetContributingFactors() []string {
	if x != nil {
		return x.ContributingFactors
	}
	return nil
}

func (x *Anomaly) GetDetectionMethod() string {
	if x != nil {
		return x.DetectionMethod
	}
	return ""
}

func (x *Anomaly) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

// DetectCrossMetricRequest requests cross-metric anomaly detection.
type DetectCrossMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent to check.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Map of metric_name -> values.
	Metrics map[string]*FloatArray `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Corresponding timestamps (Unix seconds).
	Timestamps    []int64 `protobuf:"varint,4,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectCrossMetricRequest) Reset() {
	*x = DetectCrossMetricRequest{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectCrossMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectCrossMetricRequest) ProtoMessage() {}

func (x *DetectCrossMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectCrossMetricRequest.ProtoReflect.Descriptor instead.
func (*DetectCrossMetricRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{3}
}

func (x *DetectCrossMetricRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DetectCrossMetricRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DetectCrossMetricRequest) GetMetrics() map[string]*FloatArray {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DetectCrossMetricRequest) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// FloatArray wraps a repeated float for use in maps.
type FloatArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{4}
}

func (x *FloatArray) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// DetectCrossMetricResponse contains cross-metric anomalies.
type DetectCrossMetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Individual anomalies.
	Anomalies []*Anomaly `protobuf:"bytes,1,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	// Cross-metric correlation anomalies.
	CorrelationAnomalies []*CorrelationAnomaly `protobuf:"bytes,2,rep,name=correlation_anomalies,json=correlationAnomalies,proto3" json:"correlation_anomalies,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DetectCrossMetricResponse) Reset() {
	*x = DetectCrossMetricResponse{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectCrossMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectCrossMetricResponse) ProtoMessage() {}

func (x *DetectCrossMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectCrossMetricResponse.ProtoReflect.Descriptor instead.
func (*DetectCrossMetricResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{5}
}

func (x *DetectCrossMetricResponse) GetAnomalies() []*Anomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

func (x *DetectCrossMetricResponse) GetCorrelationAnomalies() []*CorrelationAnomaly {
	if x != nil {
		return x.CorrelationAnomalies
	}
	return nil
}

// CorrelationAnomaly represents an anomaly in metric correlations.
type CorrelationAnomaly struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First metric in the correlation.
	MetricA string `protobuf:"bytes,1,opt,name=metric_a,json=metricA,proto3" json:"metric_a,omitempty"`
	// Second metric in the correlation.
	MetricB string `protobuf:"bytes,2,opt,name=metric_b,json=metricB,proto3" json:"metric_b,omitempty"`
	// Human-readable description (e.g., "CPU spike without memory increase").
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Severity: 0.0 - 1.0.
	Severity      float32 `protobuf:"fixed32,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelationAnomaly) Reset() {
	*x = CorrelationAnomaly{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationAnomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationAnomaly) ProtoMessage() {}

func (x *CorrelationAnomaly) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationAnomaly.ProtoReflect.Descriptor instead.
func (*CorrelationAnomaly) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{6}
}

func (x *CorrelationAnomaly) GetMetricA() string {
	if x != nil {
		return x.MetricA
	}
	return ""
}

func (x *CorrelationAnomaly) GetMetricB() string {
	if x != nil {
		return x.MetricB
	}
	return ""
}

func (x *CorrelationAnomaly) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CorrelationAnomaly) GetSeverity() float32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

// ExplainAnomalyRequest requests an explanation for a specific anomaly.
type ExplainAnomalyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent the anomaly occurred on.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Metric name.
	MetricName string `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Timestamp of the anomaly.
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainAnomalyRequest) Reset() {
	*x = ExplainAnomalyRequest{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainAnomalyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainAnomalyRequest) ProtoMessage() {}

func (x *ExplainAnomalyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainAnomalyRequest.ProtoReflect.Descriptor instead.
func (*ExplainAnomalyRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{7}
}

func (x *ExplainAnomalyRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExplainAnomalyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExplainAnomalyRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ExplainAnomalyRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ExplainAnomalyResponse provides a detailed anomaly explanation.
type ExplainAnomalyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The anomaly with full details.
	Anomaly *Anomaly `protobuf:"bytes,1,opt,name=anomaly,proto3" json:"anomaly,omitempty"`
	// Similar past incidents.
	SimilarIncidents []string `protobuf:"bytes,2,rep,name=similar_incidents,json=similarIncidents,proto3" json:"similar_incidents,omitempty"`
	// Recommended actions.
	Recommendations []string `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExplainAnomalyResponse) Reset() {
	*x = ExplainAnomalyResponse{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainAnomalyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainAnomalyResponse) ProtoMessage() {}

func (x *ExplainAnomalyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainAnomalyResponse.ProtoReflect.Descriptor instead.
func (*ExplainAnomalyResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{8}
}

func (x *ExplainAnomalyResponse) GetAnomaly() *Anomaly {
	if x != nil {
		return x.Anomaly
	}
	return nil
}

func (x *ExplainAnomalyResponse) GetSimilarIncidents() []string {
	if x != nil {
		return x.SimilarIncidents
	}
	return nil
}

func (x *ExplainAnomalyResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// GetDetectionStatusRequest requests the status of detection models.
type GetDetectionStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant scope.
	TenantId      string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetectionStatusRequest) Reset() {
	*x = GetDetectionStatusRequest{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectionStatusRequest) ProtoMessage() {}

func (x *GetDetectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDetectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{9}
}

func (x *GetDetectionStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetDetectionStatusResponse contains model status information.
type GetDetectionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of model_name -> status.
	Models map[string]*ModelStatus `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Last training timestamp.
	LastTraining int64 `protobuf:"varint,2,opt,name=last_training,json=lastTraining,proto3" json:"last_training,omitempty"`
	// Anomalies detected in last 24 hours.
	AnomaliesDetected_24H int32 `protobuf:"varint,3,opt,name=anomalies_detected_24h,json=anomaliesDetected24h,proto3" json:"anomalies_detected_24h,omitempty"`
	// Current false positive rate estimate.
	FalsePositiveRate float32 `protobuf:"fixed32,4,opt,name=false_positive_rate,json=falsePositiveRate,proto3" json:"false_positive_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDetectionStatusResponse) Reset() {
	*x = GetDetectionStatusResponse{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectionStatusResponse) ProtoMessage() {}

func (x *GetDetectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDetectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{10}
}

func (x *GetDetectionStatusResponse) GetModels() map[string]*ModelStatus {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *GetDetectionStatusResponse) GetLastTraining() int64 {
	if x != nil {
		return x.LastTraining
	}
	return 0
}

func (x *GetDetectionStatusResponse) GetAnomaliesDetected_24H() int32 {
	if x != nil {
		return x.AnomaliesDetected_24H
	}
	return 0
}

func (x *GetDetectionStatusResponse) GetFalsePositiveRate() float32 {
	if x != nil {
		return x.FalsePositiveRate
	}
	return 0
}

// ModelStatus represents the status of a single detection model.
type ModelStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the model is trained and ready.
	Trained bool `protobuf:"varint,2,opt,name=trained,proto3" json:"trained,omitempty"`
	// Model accuracy (0.0 - 1.0).
	Accuracy float32 `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	// Last update timestamp.
	LastUpdated   int64 `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStatus) Reset() {
	*x = ModelStatus{}
	mi := &file_paryty_v1_anomaly_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStatus) ProtoMessage() {}

func (x *ModelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_anomaly_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStatus.ProtoReflect.Descriptor instead.
func (*ModelStatus) Descriptor() ([]byte, []int) {
	return file_paryty_v1_anomaly_proto_rawDescGZIP(), []int{11}
}

func (x *ModelStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelStatus) GetTrained() bool {
	if x != nil {
		return x.Trained
	}
	return false
}

func (x *ModelStatus) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ModelStatus) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_paryty_v1_anomaly_proto protoreflect.FileDescriptor

const file_paryty_v1_anomaly_proto_rawDesc = "" +
	"\n" +
	"\x17paryty/v1/anomaly.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16paryty/v1/common.proto\"\xcb\x01\n" +
	"\x16DetectAnomaliesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x16\n" +
	"\x06values\x18\x04 \x03(\x02R\x06values\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x05 \x03(\x03R\n" +
	"timestamps\x12 \n" +
	"\vsensitivity\x18\x06 \x01(\x02R\vsensitivity\"\xc9\x01\n" +
	"\x17DetectAnomaliesResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x120\n" +
	"\tanomalies\x18\x04 \x03(\v2\x12.paryty.v1.AnomalyR\tanomalies\x12#\n" +
	"\roverall_score\x18\x05 \x01(\x02R\foverallScore\"\xb0\x02\n" +
	"\aAnomaly\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.paryty.v1.AnomalyTypeR\x04type\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x121\n" +
	"\x14contributing_factors\x18\x06 \x03(\tR\x13contributingFactors\x12)\n" +
	"\x10detection_method\x18\a \x01(\tR\x0fdetectionMethod\x12/\n" +
	"\bseverity\x18\b \x01(\x0e2\x13.paryty.v1.SeverityR\bseverity\"\x91\x02\n" +
	"\x18DetectCrossMetricRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12J\n" +
	"\ametrics\x18\x03 \x03(\v20.paryty.v1.DetectCrossMetricRequest.MetricsEntryR\ametrics\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x04 \x03(\x03R\n" +
	"timestamps\x1aQ\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.paryty.v1.FloatArrayR\x05value:\x028\x01\"$\n" +
	"\n" +
	"FloatArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xa1\x01\n" +
	"\x19DetectCrossMetricResponse\x120\n" +
	"\tanomalies\x18\x01 \x03(\v2\x12.paryty.v1.AnomalyR\tanomalies\x12R\n" +
	"\x15correlation_anomalies\x18\x02 \x03(\v2\x1d.paryty.v1.CorrelationAnomalyR\x14correlationAnomalies\"\x88\x01\n" +
	"\x12CorrelationAnomaly\x12\x19\n" +
	"\bmetric_a\x18\x01 \x01(\tR\ametricA\x12\x19\n" +
	"\bmetric_b\x18\x02 \x01(\tR\ametricB\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x02R\bseverity\"\x8e\x01\n" +
	"\x15ExplainAnomalyRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x9d\x01\n" +
	"\x16ExplainAnomalyResponse\x12,\n" +
	"\aanomaly\x18\x01 \x01(\v2\x12.paryty.v1.AnomalyR\aanomaly\x12+\n" +
	"\x11similar_incidents\x18\x02 \x03(\tR\x10similarIncidents\x12(\n" +
	"\x0frecommendations\x18\x03 \x03(\tR\x0frecommendations\"8\n" +
	"\x19GetDetectionStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xc5\x02\n" +
	"\x1aGetDetectionStatusResponse\x12I\n" +
	"\x06models\x18\x01 \x03(\v21.paryty.v1.GetDetectionStatusResponse.ModelsEntryR\x06models\x12#\n" +
	"\rlast_training\x18\x02 \x01(\x03R\flastTraining\x124\n" +
	"\x16anomalies_detected_24h\x18\x03 \x01(\x05R\x14anomaliesDetected24h\x12.\n" +
	"\x13false_positive_rate\x18\x04 \x01(\x02R\x11falsePositiveRate\x1aQ\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.paryty.v1.ModelStatusR\x05value:\x028\x01\"z\n" +
	"\vModelStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\atrained\x18\x02 \x01(\bR\atrained\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x02R\baccuracy\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated*\x95\x01\n" +
	"\vAnomalyType\x12\x1c\n" +
	"\x18ANOMALY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ANOMALY_TYPE_POINT\x10\x01\x12\x1b\n" +
	"\x17ANOMALY_TYPE_CONTEXTUAL\x10\x02\x12\x1b\n" +
	"\x17ANOMALY_TYPE_COLLECTIVE\x10\x03\x12\x16\n" +
	"\x12ANOMALY_TYPE_TREND\x10\x042\x96\x03\n" +
	"\x17AnomalyDetectionService\x12X\n" +
	"\x0fDetectAnomalies\x12!.paryty.v1.DetectAnomaliesRequest\x1a\".paryty.v1.DetectAnomaliesResponse\x12g\n" +
	"\x1aDetectCrossMetricAnomalies\x12#.paryty.v1.DetectCrossMetricRequest\x1a$.paryty.v1.DetectCrossMetricResponse\x12U\n" +
	"\x0eExplainAnomaly\x12 .paryty.v1.ExplainAnomalyRequest\x1a!.paryty.v1.ExplainAnomalyResponse\x12a\n" +
	"\x12GetDetectionStatus\x12$.paryty.v1.GetDetectionStatusRequest\x1a%.paryty.v1.GetDetectionStatusResponseB?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_anomaly_proto_rawDescOnce sync.Once
	file_paryty_v1_anomaly_proto_rawDescData []byte
)

func file_paryty_v1_anomaly_proto_rawDescGZIP() []byte {
	file_paryty_v1_anomaly_proto_rawDescOnce.Do(func() {
		file_paryty_v1_anomaly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_anomaly_proto_rawDesc), len(file_paryty_v1_anomaly_proto_rawDesc)))
	})
	return file_paryty_v1_anomaly_proto_rawDescData
}

var file_paryty_v1_anomaly_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paryty_v1_anomaly_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_paryty_v1_anomaly_proto_goTypes = []any{
	(AnomalyType)(0),                   // 0: paryty.v1.AnomalyType
	(*DetectAnomaliesRequest)(nil),     // 1: paryty.v1.DetectAnomaliesRequest
	(*DetectAnomaliesResponse)(nil),    // 2: paryty.v1.DetectAnomaliesResponse
	(*Anomaly)(nil),                    // 3: paryty.v1.Anomaly
	(*DetectCrossMetricRequest)(nil),   // 4: paryty.v1.DetectCrossMetricRequest
	(*FloatArray)(nil),                 // 5: paryty.v1.FloatArray
	(*DetectCrossMetricResponse)(nil),  // 6: paryty.v1.DetectCrossMetricResponse
	(*CorrelationAnomaly)(nil),         // 7: paryty.v1.CorrelationAnomaly
	(*ExplainAnomalyRequest)(nil),      // 8: paryty.v1.ExplainAnomalyRequest
	(*ExplainAnomalyResponse)(nil),     // 9: paryty.v1.ExplainAnomalyResponse
	(*GetDetectionStatusRequest)(nil),  // 10: paryty.v1.GetDetectionStatusRequest
	(*GetDetectionStatusResponse)(nil), // 11: paryty.v1.GetDetectionStatusResponse
	(*ModelStatus)(nil),                // 12: paryty.v1.ModelStatus
	nil,                                // 13: paryty.v1.DetectCrossMetricRequest.MetricsEntry
	nil,                                // 14: paryty.v1.GetDetectionStatusResponse.ModelsEntry
	(Severity)(0),                      // 15: paryty.v1.Severity
}
var file_paryty_v1_anomaly_proto_depIdxs = []int32{
	3,  // 0: paryty.v1.DetectAnomaliesResponse.anomalies:type_name -> paryty.v1.Anomaly
	0,  // 1: paryty.v1.Anomaly.type:type_name -> paryty.v1.AnomalyType
	15, // 2: paryty.v1.Anomaly.severity:type_name -> paryty.v1.Severity
	13, // 3: paryty.v1.DetectCrossMetricRequest.metrics:type_name -> paryty.v1.DetectCrossMetricRequest.MetricsEntry
	3,  // 4: paryty.v1.DetectCrossMetricResponse.anomalies:type_name -> paryty.v1.Anomaly
	7,  // 5: paryty.v1.DetectCrossMetricResponse.correlation_anomalies:type_name -> paryty.v1.CorrelationAnomaly
	3,  // 6: paryty.v1.ExplainAnomalyResponse.anomaly:type_name -> paryty.v1.Anomaly
	14, // 7: paryty.v1.GetDetectionStatusResponse.models:type_name -> paryty.v1.GetDetectionStatusResponse.ModelsEntry
	5,  // 8: paryty.v1.DetectCrossMetricRequest.MetricsEntry.value:type_name -> paryty.v1.FloatArray
	12, // 9: paryty.v1.GetDetectionStatusResponse.ModelsEntry.value:type_name -> paryty.v1.ModelStatus
	1,  // 10: paryty.v1.AnomalyDetectionService.DetectAnomalies:input_type -> paryty.v1.DetectAnomaliesRequest
	4,  // 11: paryty.v1.AnomalyDetectionService.DetectCrossMetricAnomalies:input_type -> paryty.v1.DetectCrossMetricRequest
	8,  // 12: paryty.v1.AnomalyDetectionService.ExplainAnomaly:input_type -> paryty.v1.ExplainAnomalyRequest
	10, // 13: paryty.v1.AnomalyDetectionService.GetDetectionStatus:input_type -> paryty.v1.GetDetectionStatusRequest
	2,  // 14: paryty.v1.AnomalyDetectionService.DetectAnomalies:output_type -> paryty.v1.DetectAnomaliesResponse
	6,  // 15: paryty.v1.AnomalyDetectionService.DetectCrossMetricAnomalies:output_type -> paryty.v1.DetectCrossMetricResponse
	9,  // 16: paryty.v1.AnomalyDetectionService.ExplainAnomaly:output_type -> paryty.v1.ExplainAnomalyResponse
	11, // 17: paryty.v1.AnomalyDetectionService.GetDetectionStatus:output_type -> paryty.v1.GetDetectionStatusResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_paryty_v1_anomaly_proto_init() }
func file_paryty_v1_anomaly_proto_init() {
	if File_paryty_v1_anomaly_proto != nil {
		return
	}
	file_paryty_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_anomaly_proto_rawDesc), len(file_paryty_v1_anomaly_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paryty_v1_anomaly_proto_goTypes,
		DependencyIndexes: file_paryty_v1_anomaly_proto_depIdxs,
		EnumInfos:         file_paryty_v1_anomaly_proto_enumTypes,
		MessageInfos:      file_paryty_v1_anomaly_proto_msgTypes,
	}.Build()
	File_paryty_v1_anomaly_proto = out.File
	file_paryty_v1_anomaly_proto_goTypes = nil
	file_paryty_v1_anomaly_proto_depIdxs = nil
}
