// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paryty/v1/auth.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // min 8 chars, must pass entropy check
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PlanName      string                 `protobuf:"bytes,4,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"` // "basic", "pro", "pro_plus"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds until access token expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	User          *UserInfo              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ValidateTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   map[string]bool        `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_paryty_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSubUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "admin", "operator", or "viewer"
	Permissions   map[string]bool        `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubUserRequest) Reset() {
	*x = CreateSubUserRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubUserRequest) ProtoMessage() {}

func (x *CreateSubUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubUserRequest.ProtoReflect.Descriptor instead.
func (*CreateSubUserRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSubUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSubUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSubUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateSubUserRequest) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdatePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   map[string]bool        `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionsRequest) Reset() {
	*x = UpdatePermissionsRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionsRequest) ProtoMessage() {}

func (x *UpdatePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePermissionsRequest) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*PlanInfo            `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ListPlansResponse) GetPlans() []*PlanInfo {
	if x != nil {
		return x.Plans
	}
	return nil
}

type PlanInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MaxTwins    int32                  `protobuf:"varint,3,opt,name=max_twins,json=maxTwins,proto3" json:"max_twins,omitempty"`
	Creatable   bool                   `protobuf:"varint,4,opt,name=creatable,proto3" json:"creatable,omitempty"`
	Features    map[string]bool        `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Limits      *PlanLimits            `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	Quotas      *PlanQuotas            `protobuf:"bytes,7,opt,name=quotas,proto3" json:"quotas,omitempty"`
	// Current usage for the authenticated tenant (only in GetCurrentPlan).
	Usage         *PlanUsage `protobuf:"bytes,8,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanInfo) Reset() {
	*x = PlanInfo{}
	mi := &file_paryty_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanInfo) ProtoMessage() {}

func (x *PlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanInfo.ProtoReflect.Descriptor instead.
func (*PlanInfo) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *PlanInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PlanInfo) GetMaxTwins() int32 {
	if x != nil {
		return x.MaxTwins
	}
	return 0
}

func (x *PlanInfo) GetCreatable() bool {
	if x != nil {
		return x.Creatable
	}
	return false
}

func (x *PlanInfo) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PlanInfo) GetLimits() *PlanLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *PlanInfo) GetQuotas() *PlanQuotas {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *PlanInfo) GetUsage() *PlanUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type PlanLimits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentsPerTwin       int32                  `protobuf:"varint,1,opt,name=agents_per_twin,json=agentsPerTwin,proto3" json:"agents_per_twin,omitempty"`
	DataRetentionDays   int32                  `protobuf:"varint,2,opt,name=data_retention_days,json=dataRetentionDays,proto3" json:"data_retention_days,omitempty"`
	MetricsResolution   string                 `protobuf:"bytes,3,opt,name=metrics_resolution,json=metricsResolution,proto3" json:"metrics_resolution,omitempty"`
	AlertRulesPerTenant int32                  `protobuf:"varint,4,opt,name=alert_rules_per_tenant,json=alertRulesPerTenant,proto3" json:"alert_rules_per_tenant,omitempty"`
	SubUsers            int32                  `protobuf:"varint,5,opt,name=sub_users,json=subUsers,proto3" json:"sub_users,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlanLimits) Reset() {
	*x = PlanLimits{}
	mi := &file_paryty_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanLimits) ProtoMessage() {}

func (x *PlanLimits) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanLimits.ProtoReflect.Descriptor instead.
func (*PlanLimits) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *PlanLimits) GetAgentsPerTwin() int32 {
	if x != nil {
		return x.AgentsPerTwin
	}
	return 0
}

func (x *PlanLimits) GetDataRetentionDays() int32 {
	if x != nil {
		return x.DataRetentionDays
	}
	return 0
}

func (x *PlanLimits) GetMetricsResolution() string {
	if x != nil {
		return x.MetricsResolution
	}
	return ""
}

func (x *PlanLimits) GetAlertRulesPerTenant() int32 {
	if x != nil {
		return x.AlertRulesPerTenant
	}
	return 0
}

func (x *PlanLimits) GetSubUsers() int32 {
	if x != nil {
		return x.SubUsers
	}
	return 0
}

type PlanQuotas struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IngestionBytesPerDay   int64                  `protobuf:"varint,1,opt,name=ingestion_bytes_per_day,json=ingestionBytesPerDay,proto3" json:"ingestion_bytes_per_day,omitempty"`
	QueryRequestsPerMinute int32                  `protobuf:"varint,2,opt,name=query_requests_per_minute,json=queryRequestsPerMinute,proto3" json:"query_requests_per_minute,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlanQuotas) Reset() {
	*x = PlanQuotas{}
	mi := &file_paryty_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanQuotas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanQuotas) ProtoMessage() {}

func (x *PlanQuotas) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanQuotas.ProtoReflect.Descriptor instead.
func (*PlanQuotas) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *PlanQuotas) GetIngestionBytesPerDay() int64 {
	if x != nil {
		return x.IngestionBytesPerDay
	}
	return 0
}

func (x *PlanQuotas) GetQueryRequestsPerMinute() int32 {
	if x != nil {
		return x.QueryRequestsPerMinute
	}
	return 0
}

type PlanUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TwinsUsed     int32                  `protobuf:"varint,1,opt,name=twins_used,json=twinsUsed,proto3" json:"twins_used,omitempty"`
	TwinsLimit    int32                  `protobuf:"varint,2,opt,name=twins_limit,json=twinsLimit,proto3" json:"twins_limit,omitempty"`
	AgentsUsed    int32                  `protobuf:"varint,3,opt,name=agents_used,json=agentsUsed,proto3" json:"agents_used,omitempty"`
	AgentsLimit   int32                  `protobuf:"varint,4,opt,name=agents_limit,json=agentsLimit,proto3" json:"agents_limit,omitempty"`
	UsersUsed     int32                  `protobuf:"varint,5,opt,name=users_used,json=usersUsed,proto3" json:"users_used,omitempty"`
	UsersLimit    int32                  `protobuf:"varint,6,opt,name=users_limit,json=usersLimit,proto3" json:"users_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanUsage) Reset() {
	*x = PlanUsage{}
	mi := &file_paryty_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanUsage) ProtoMessage() {}

func (x *PlanUsage) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanUsage.ProtoReflect.Descriptor instead.
func (*PlanUsage) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *PlanUsage) GetTwinsUsed() int32 {
	if x != nil {
		return x.TwinsUsed
	}
	return 0
}

func (x *PlanUsage) GetTwinsLimit() int32 {
	if x != nil {
		return x.TwinsLimit
	}
	return 0
}

func (x *PlanUsage) GetAgentsUsed() int32 {
	if x != nil {
		return x.AgentsUsed
	}
	return 0
}

func (x *PlanUsage) GetAgentsLimit() int32 {
	if x != nil {
		return x.AgentsLimit
	}
	return 0
}

func (x *PlanUsage) GetUsersUsed() int32 {
	if x != nil {
		return x.UsersUsed
	}
	return 0
}

func (x *PlanUsage) GetUsersLimit() int32 {
	if x != nil {
		return x.UsersLimit
	}
	return 0
}

type PlanFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      map[string]bool        `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanFeaturesResponse) Reset() {
	*x = PlanFeaturesResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanFeaturesResponse) ProtoMessage() {}

func (x *PlanFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanFeaturesResponse.ProtoReflect.Descriptor instead.
func (*PlanFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *PlanFeaturesResponse) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

type CreateTwinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Config        *TwinConfig            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTwinRequest) Reset() {
	*x = CreateTwinRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTwinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTwinRequest) ProtoMessage() {}

func (x *CreateTwinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTwinRequest.ProtoReflect.Descriptor instead.
func (*CreateTwinRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTwinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTwinRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTwinRequest) GetConfig() *TwinConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type TwinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AgentCount    int32                  `protobuf:"varint,6,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	Config        *TwinConfig            `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwinInfo) Reset() {
	*x = TwinInfo{}
	mi := &file_paryty_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinInfo) ProtoMessage() {}

func (x *TwinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinInfo.ProtoReflect.Descriptor instead.
func (*TwinInfo) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *TwinInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwinInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TwinInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TwinInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TwinInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TwinInfo) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *TwinInfo) GetConfig() *TwinConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TwinInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TwinInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TwinConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of agent labels to auto-assign (e.g., {"env": "prod", "region": "us-east-1"}).
	AgentLabels map[string]string `protobuf:"bytes,1,rep,name=agent_labels,json=agentLabels,proto3" json:"agent_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Enabled collectors (e.g., ["cpu", "memory", "disk", "network", "ebpf"]).
	EnabledCollectors []string `protobuf:"bytes,2,rep,name=enabled_collectors,json=enabledCollectors,proto3" json:"enabled_collectors,omitempty"`
	// Collection interval in seconds.
	CollectionIntervalSeconds int32 `protobuf:"varint,3,opt,name=collection_interval_seconds,json=collectionIntervalSeconds,proto3" json:"collection_interval_seconds,omitempty"`
	// Sampling rate (0.0 - 1.0).
	SamplingRate  float32 `protobuf:"fixed32,4,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwinConfig) Reset() {
	*x = TwinConfig{}
	mi := &file_paryty_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinConfig) ProtoMessage() {}

func (x *TwinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinConfig.ProtoReflect.Descriptor instead.
func (*TwinConfig) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *TwinConfig) GetAgentLabels() map[string]string {
	if x != nil {
		return x.AgentLabels
	}
	return nil
}

func (x *TwinConfig) GetEnabledCollectors() []string {
	if x != nil {
		return x.EnabledCollectors
	}
	return nil
}

func (x *TwinConfig) GetCollectionIntervalSeconds() int32 {
	if x != nil {
		return x.CollectionIntervalSeconds
	}
	return 0
}

func (x *TwinConfig) GetSamplingRate() float32 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

type ListTwinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwinsRequest) Reset() {
	*x = ListTwinsRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwinsRequest) ProtoMessage() {}

func (x *ListTwinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwinsRequest.ProtoReflect.Descriptor instead.
func (*ListTwinsRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *ListTwinsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTwinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Twins         []*TwinInfo            `protobuf:"bytes,1,rep,name=twins,proto3" json:"twins,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwinsResponse) Reset() {
	*x = ListTwinsResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwinsResponse) ProtoMessage() {}

func (x *ListTwinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwinsResponse.ProtoReflect.Descriptor instead.
func (*ListTwinsResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{26}
}

func (x *ListTwinsResponse) GetTwins() []*TwinInfo {
	if x != nil {
		return x.Twins
	}
	return nil
}

func (x *ListTwinsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTwinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TwinId        string                 `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTwinRequest) Reset() {
	*x = GetTwinRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTwinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwinRequest) ProtoMessage() {}

func (x *GetTwinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwinRequest.ProtoReflect.Descriptor instead.
func (*GetTwinRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *GetTwinRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

type UpdateTwinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TwinId        string                 `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *TwinConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTwinRequest) Reset() {
	*x = UpdateTwinRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTwinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTwinRequest) ProtoMessage() {}

func (x *UpdateTwinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTwinRequest.ProtoReflect.Descriptor instead.
func (*UpdateTwinRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateTwinRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *UpdateTwinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTwinRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTwinRequest) GetConfig() *TwinConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteTwinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TwinId        string                 `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTwinRequest) Reset() {
	*x = DeleteTwinRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTwinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTwinRequest) ProtoMessage() {}

func (x *DeleteTwinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTwinRequest.ProtoReflect.Descriptor instead.
func (*DeleteTwinRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteTwinRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

type GetTwinConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TwinId        string                 `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTwinConfigRequest) Reset() {
	*x = GetTwinConfigRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTwinConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwinConfigRequest) ProtoMessage() {}

func (x *GetTwinConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwinConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTwinConfigRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{30}
}

func (x *GetTwinConfigRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *GetTwinConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ResolveIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID requesting identity resolution.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityRequest) Reset() {
	*x = ResolveIdentityRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityRequest) ProtoMessage() {}

func (x *ResolveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveIdentityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ResolveIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the agent has an assigned twin.
	Assigned bool `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	// Assigned twin ID.
	TwinId string `protobuf:"bytes,2,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// Client/tenant ID.
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Topic prefix for Redpanda routing (e.g., "clients.acme.twin_7a3f").
	TopicPrefix   string `protobuf:"bytes,4,opt,name=topic_prefix,json=topicPrefix,proto3" json:"topic_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityResponse) Reset() {
	*x = ResolveIdentityResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityResponse) ProtoMessage() {}

func (x *ResolveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{32}
}

func (x *ResolveIdentityResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *ResolveIdentityResponse) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetTopicPrefix() string {
	if x != nil {
		return x.TopicPrefix
	}
	return ""
}

type AssignAgentToTwinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target twin ID.
	TwinId string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// Agent ID to assign.
	AgentId       string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentToTwinRequest) Reset() {
	*x = AssignAgentToTwinRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentToTwinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentToTwinRequest) ProtoMessage() {}

func (x *AssignAgentToTwinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentToTwinRequest.ProtoReflect.Descriptor instead.
func (*AssignAgentToTwinRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{33}
}

func (x *AssignAgentToTwinRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *AssignAgentToTwinRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AssignAgentToTwinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the assignment was accepted by the agent.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Error message if assignment failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentToTwinResponse) Reset() {
	*x = AssignAgentToTwinResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentToTwinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentToTwinResponse) ProtoMessage() {}

func (x *AssignAgentToTwinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentToTwinResponse.ProtoReflect.Descriptor instead.
func (*AssignAgentToTwinResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{34}
}

func (x *AssignAgentToTwinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignAgentToTwinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListTwinAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Twin ID to list agents for.
	TwinId        string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwinAgentsRequest) Reset() {
	*x = ListTwinAgentsRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwinAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwinAgentsRequest) ProtoMessage() {}

func (x *ListTwinAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwinAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListTwinAgentsRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{35}
}

func (x *ListTwinAgentsRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

type ListTwinAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agents associated with this twin.
	Agents        []*TwinAgentInfo `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTwinAgentsResponse) Reset() {
	*x = ListTwinAgentsResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTwinAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwinAgentsResponse) ProtoMessage() {}

func (x *ListTwinAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwinAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListTwinAgentsResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{36}
}

func (x *ListTwinAgentsResponse) GetAgents() []*TwinAgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type TwinAgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent identifier.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Agent hostname.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Connection status: online, offline, connecting, error.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Backlog size in bytes (0 if no backlog).
	BacklogBytes int64 `protobuf:"varint,4,opt,name=backlog_bytes,json=backlogBytes,proto3" json:"backlog_bytes,omitempty"`
	// When the agent last sent a heartbeat.
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Whether this agent is assigned to this twin.
	Assigned bool `protobuf:"varint,6,opt,name=assigned,proto3" json:"assigned,omitempty"`
	// Agent operating system.
	Os string `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	// Agent CPU architecture.
	Arch          string `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwinAgentInfo) Reset() {
	*x = TwinAgentInfo{}
	mi := &file_paryty_v1_auth_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinAgentInfo) ProtoMessage() {}

func (x *TwinAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinAgentInfo.ProtoReflect.Descriptor instead.
func (*TwinAgentInfo) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{37}
}

func (x *TwinAgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TwinAgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TwinAgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TwinAgentInfo) GetBacklogBytes() int64 {
	if x != nil {
		return x.BacklogBytes
	}
	return 0
}

func (x *TwinAgentInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *TwinAgentInfo) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *TwinAgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *TwinAgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type AcceptBacklogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Twin ID.
	TwinId string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// Agent ID with backlog to accept.
	AgentId       string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptBacklogRequest) Reset() {
	*x = AcceptBacklogRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptBacklogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBacklogRequest) ProtoMessage() {}

func (x *AcceptBacklogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBacklogRequest.ProtoReflect.Descriptor instead.
func (*AcceptBacklogRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{38}
}

func (x *AcceptBacklogRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *AcceptBacklogRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AcceptBacklogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the backlog upload command was dispatched.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptBacklogResponse) Reset() {
	*x = AcceptBacklogResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptBacklogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBacklogResponse) ProtoMessage() {}

func (x *AcceptBacklogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBacklogResponse.ProtoReflect.Descriptor instead.
func (*AcceptBacklogResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{39}
}

func (x *AcceptBacklogResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RejectBacklogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Twin ID.
	TwinId string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// Agent ID with backlog to reject.
	AgentId       string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectBacklogRequest) Reset() {
	*x = RejectBacklogRequest{}
	mi := &file_paryty_v1_auth_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectBacklogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectBacklogRequest) ProtoMessage() {}

func (x *RejectBacklogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectBacklogRequest.ProtoReflect.Descriptor instead.
func (*RejectBacklogRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{40}
}

func (x *RejectBacklogRequest) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *RejectBacklogRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type RejectBacklogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the backlog deletion command was dispatched.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectBacklogResponse) Reset() {
	*x = RejectBacklogResponse{}
	mi := &file_paryty_v1_auth_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectBacklogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectBacklogResponse) ProtoMessage() {}

func (x *RejectBacklogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_auth_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectBacklogResponse.ProtoReflect.Descriptor instead.
func (*RejectBacklogResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_auth_proto_rawDescGZIP(), []int{41}
}

func (x *RejectBacklogResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_paryty_v1_auth_proto protoreflect.FileDescriptor

const file_paryty_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x14paryty/v1/auth.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16paryty/v1/common.proto\"t\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tplan_name\x18\x04 \x01(\tR\bplanName\"\xaf\x01\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12'\n" +
	"\x04user\x18\x04 \x01(\v2\x13.paryty.v1.UserInfoR\x04user\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xd4\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc1\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12F\n" +
	"\vpermissions\x18\x06 \x03(\v2$.paryty.v1.UserInfo.PermissionsEntryR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x84\x02\n" +
	"\x14CreateSubUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12R\n" +
	"\vpermissions\x18\x05 \x03(\v20.paryty.v1.CreateSubUserRequest.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"P\n" +
	"\x10ListUsersRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.paryty.v1.PaginationRequestR\n" +
	"pagination\"}\n" +
	"\x11ListUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.paryty.v1.UserInfoR\x05users\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.paryty.v1.PaginationResponseR\n" +
	"pagination\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"q\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xcb\x01\n" +
	"\x18UpdatePermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12V\n" +
	"\vpermissions\x18\x02 \x03(\v24.paryty.v1.UpdatePermissionsRequest.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\">\n" +
	"\x11ListPlansResponse\x12)\n" +
	"\x05plans\x18\x01 \x03(\v2\x13.paryty.v1.PlanInfoR\x05plans\"\x82\x03\n" +
	"\bPlanInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tmax_twins\x18\x03 \x01(\x05R\bmaxTwins\x12\x1c\n" +
	"\tcreatable\x18\x04 \x01(\bR\tcreatable\x12=\n" +
	"\bfeatures\x18\x05 \x03(\v2!.paryty.v1.PlanInfo.FeaturesEntryR\bfeatures\x12-\n" +
	"\x06limits\x18\x06 \x01(\v2\x15.paryty.v1.PlanLimitsR\x06limits\x12-\n" +
	"\x06quotas\x18\a \x01(\v2\x15.paryty.v1.PlanQuotasR\x06quotas\x12*\n" +
	"\x05usage\x18\b \x01(\v2\x14.paryty.v1.PlanUsageR\x05usage\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xe5\x01\n" +
	"\n" +
	"PlanLimits\x12&\n" +
	"\x0fagents_per_twin\x18\x01 \x01(\x05R\ragentsPerTwin\x12.\n" +
	"\x13data_retention_days\x18\x02 \x01(\x05R\x11dataRetentionDays\x12-\n" +
	"\x12metrics_resolution\x18\x03 \x01(\tR\x11metricsResolution\x123\n" +
	"\x16alert_rules_per_tenant\x18\x04 \x01(\x05R\x13alertRulesPerTenant\x12\x1b\n" +
	"\tsub_users\x18\x05 \x01(\x05R\bsubUsers\"~\n" +
	"\n" +
	"PlanQuotas\x125\n" +
	"\x17ingestion_bytes_per_day\x18\x01 \x01(\x03R\x14ingestionBytesPerDay\x129\n" +
	"\x19query_requests_per_minute\x18\x02 \x01(\x05R\x16queryRequestsPerMinute\"\xcf\x01\n" +
	"\tPlanUsage\x12\x1d\n" +
	"\n" +
	"twins_used\x18\x01 \x01(\x05R\ttwinsUsed\x12\x1f\n" +
	"\vtwins_limit\x18\x02 \x01(\x05R\n" +
	"twinsLimit\x12\x1f\n" +
	"\vagents_used\x18\x03 \x01(\x05R\n" +
	"agentsUsed\x12!\n" +
	"\fagents_limit\x18\x04 \x01(\x05R\vagentsLimit\x12\x1d\n" +
	"\n" +
	"users_used\x18\x05 \x01(\x05R\tusersUsed\x12\x1f\n" +
	"\vusers_limit\x18\x06 \x01(\x05R\n" +
	"usersLimit\"\x9e\x01\n" +
	"\x14PlanFeaturesResponse\x12I\n" +
	"\bfeatures\x18\x01 \x03(\v2-.paryty.v1.PlanFeaturesResponse.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"x\n" +
	"\x11CreateTwinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x06config\x18\x03 \x01(\v2\x15.paryty.v1.TwinConfigR\x06config\"\xcb\x02\n" +
	"\bTwinInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vagent_count\x18\x06 \x01(\x05R\n" +
	"agentCount\x12-\n" +
	"\x06config\x18\a \x01(\v2\x15.paryty.v1.TwinConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xab\x02\n" +
	"\n" +
	"TwinConfig\x12I\n" +
	"\fagent_labels\x18\x01 \x03(\v2&.paryty.v1.TwinConfig.AgentLabelsEntryR\vagentLabels\x12-\n" +
	"\x12enabled_collectors\x18\x02 \x03(\tR\x11enabledCollectors\x12>\n" +
	"\x1bcollection_interval_seconds\x18\x03 \x01(\x05R\x19collectionIntervalSeconds\x12#\n" +
	"\rsampling_rate\x18\x04 \x01(\x02R\fsamplingRate\x1a>\n" +
	"\x10AgentLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x10ListTwinsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.paryty.v1.PaginationRequestR\n" +
	"pagination\"}\n" +
	"\x11ListTwinsResponse\x12)\n" +
	"\x05twins\x18\x01 \x03(\v2\x13.paryty.v1.TwinInfoR\x05twins\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.paryty.v1.PaginationResponseR\n" +
	"pagination\")\n" +
	"\x0eGetTwinRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\"\x91\x01\n" +
	"\x11UpdateTwinRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x06config\x18\x04 \x01(\v2\x15.paryty.v1.TwinConfigR\x06config\",\n" +
	"\x11DeleteTwinRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\"J\n" +
	"\x14GetTwinConfigRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"3\n" +
	"\x16ResolveIdentityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x8e\x01\n" +
	"\x17ResolveIdentityResponse\x12\x1a\n" +
	"\bassigned\x18\x01 \x01(\bR\bassigned\x12\x17\n" +
	"\atwin_id\x18\x02 \x01(\tR\x06twinId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12!\n" +
	"\ftopic_prefix\x18\x04 \x01(\tR\vtopicPrefix\"N\n" +
	"\x18AssignAgentToTwinRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"M\n" +
	"\x19AssignAgentToTwinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"0\n" +
	"\x15ListTwinAgentsRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\"J\n" +
	"\x16ListTwinAgentsResponse\x120\n" +
	"\x06agents\x18\x01 \x03(\v2\x18.paryty.v1.TwinAgentInfoR\x06agents\"\x86\x02\n" +
	"\rTwinAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rbacklog_bytes\x18\x04 \x01(\x03R\fbacklogBytes\x12A\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12\x1a\n" +
	"\bassigned\x18\x06 \x01(\bR\bassigned\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\b \x01(\tR\x04arch\"J\n" +
	"\x14AcceptBacklogRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"3\n" +
	"\x15AcceptBacklogResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"J\n" +
	"\x14RejectBacklogRequest\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"1\n" +
	"\x15RejectBacklogResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xe8\x02\n" +
	"\vAuthService\x12C\n" +
	"\bRegister\x12\x1a.paryty.v1.RegisterRequest\x1a\x1b.paryty.v1.RegisterResponse\x12:\n" +
	"\x05Login\x12\x17.paryty.v1.LoginRequest\x1a\x18.paryty.v1.LoginResponse\x12H\n" +
	"\fRefreshToken\x12\x1e.paryty.v1.RefreshTokenRequest\x1a\x18.paryty.v1.LoginResponse\x12:\n" +
	"\x06Logout\x12\x18.paryty.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\rValidateToken\x12\x1f.paryty.v1.ValidateTokenRequest\x1a .paryty.v1.ValidateTokenResponse2\xab\x03\n" +
	"\vUserService\x12E\n" +
	"\rCreateSubUser\x12\x1f.paryty.v1.CreateSubUserRequest\x1a\x13.paryty.v1.UserInfo\x12F\n" +
	"\tListUsers\x12\x1b.paryty.v1.ListUsersRequest\x1a\x1c.paryty.v1.ListUsersResponse\x129\n" +
	"\aGetUser\x12\x19.paryty.v1.GetUserRequest\x1a\x13.paryty.v1.UserInfo\x12?\n" +
	"\n" +
	"UpdateUser\x12\x1c.paryty.v1.UpdateUserRequest\x1a\x13.paryty.v1.UserInfo\x12B\n" +
	"\n" +
	"DeleteUser\x12\x1c.paryty.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x11UpdatePermissions\x12#.paryty.v1.UpdatePermissionsRequest\x1a\x13.paryty.v1.UserInfo2\xdb\x01\n" +
	"\vPlanService\x12A\n" +
	"\tListPlans\x12\x16.google.protobuf.Empty\x1a\x1c.paryty.v1.ListPlansResponse\x12=\n" +
	"\x0eGetCurrentPlan\x12\x16.google.protobuf.Empty\x1a\x13.paryty.v1.PlanInfo\x12J\n" +
	"\x0fGetPlanFeatures\x12\x16.google.protobuf.Empty\x1a\x1f.paryty.v1.PlanFeaturesResponse2\xd8\x06\n" +
	"\vTwinService\x12?\n" +
	"\n" +
	"CreateTwin\x12\x1c.paryty.v1.CreateTwinRequest\x1a\x13.paryty.v1.TwinInfo\x12F\n" +
	"\tListTwins\x12\x1b.paryty.v1.ListTwinsRequest\x1a\x1c.paryty.v1.ListTwinsResponse\x129\n" +
	"\aGetTwin\x12\x19.paryty.v1.GetTwinRequest\x1a\x13.paryty.v1.TwinInfo\x12?\n" +
	"\n" +
	"UpdateTwin\x12\x1c.paryty.v1.UpdateTwinRequest\x1a\x13.paryty.v1.TwinInfo\x12B\n" +
	"\n" +
	"DeleteTwin\x12\x1c.paryty.v1.DeleteTwinRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rGetTwinConfig\x12\x1f.paryty.v1.GetTwinConfigRequest\x1a\x15.paryty.v1.TwinConfig\x12X\n" +
	"\x0fResolveIdentity\x12!.paryty.v1.ResolveIdentityRequest\x1a\".paryty.v1.ResolveIdentityResponse\x12^\n" +
	"\x11AssignAgentToTwin\x12#.paryty.v1.AssignAgentToTwinRequest\x1a$.paryty.v1.AssignAgentToTwinResponse\x12U\n" +
	"\x0eListTwinAgents\x12 .paryty.v1.ListTwinAgentsRequest\x1a!.paryty.v1.ListTwinAgentsResponse\x12R\n" +
	"\rAcceptBacklog\x12\x1f.paryty.v1.AcceptBacklogRequest\x1a .paryty.v1.AcceptBacklogResponse\x12R\n" +
	"\rRejectBacklog\x12\x1f.paryty.v1.RejectBacklogRequest\x1a .paryty.v1.RejectBacklogResponseB?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_auth_proto_rawDescOnce sync.Once
	file_paryty_v1_auth_proto_rawDescData []byte
)

func file_paryty_v1_auth_proto_rawDescGZIP() []byte {
	file_paryty_v1_auth_proto_rawDescOnce.Do(func() {
		file_paryty_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_auth_proto_rawDesc), len(file_paryty_v1_auth_proto_rawDesc)))
	})
	return file_paryty_v1_auth_proto_rawDescData
}

var file_paryty_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_paryty_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: paryty.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 1: paryty.v1.RegisterResponse
	(*LoginRequest)(nil),              // 2: paryty.v1.LoginRequest
	(*LoginResponse)(nil),             // 3: paryty.v1.LoginResponse
	(*RefreshTokenRequest)(nil),       // 4: paryty.v1.RefreshTokenRequest
	(*LogoutRequest)(nil),             // 5: paryty.v1.LogoutRequest
	(*ValidateTokenRequest)(nil),      // 6: paryty.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),     // 7: paryty.v1.ValidateTokenResponse
	(*UserInfo)(nil),                  // 8: paryty.v1.UserInfo
	(*CreateSubUserRequest)(nil),      // 9: paryty.v1.CreateSubUserRequest
	(*ListUsersRequest)(nil),          // 10: paryty.v1.ListUsersRequest
	(*ListUsersResponse)(nil),         // 11: paryty.v1.ListUsersResponse
	(*GetUserRequest)(nil),            // 12: paryty.v1.GetUserRequest
	(*UpdateUserRequest)(nil),         // 13: paryty.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),         // 14: paryty.v1.DeleteUserRequest
	(*UpdatePermissionsRequest)(nil),  // 15: paryty.v1.UpdatePermissionsRequest
	(*ListPlansResponse)(nil),         // 16: paryty.v1.ListPlansResponse
	(*PlanInfo)(nil),                  // 17: paryty.v1.PlanInfo
	(*PlanLimits)(nil),                // 18: paryty.v1.PlanLimits
	(*PlanQuotas)(nil),                // 19: paryty.v1.PlanQuotas
	(*PlanUsage)(nil),                 // 20: paryty.v1.PlanUsage
	(*PlanFeaturesResponse)(nil),      // 21: paryty.v1.PlanFeaturesResponse
	(*CreateTwinRequest)(nil),         // 22: paryty.v1.CreateTwinRequest
	(*TwinInfo)(nil),                  // 23: paryty.v1.TwinInfo
	(*TwinConfig)(nil),                // 24: paryty.v1.TwinConfig
	(*ListTwinsRequest)(nil),          // 25: paryty.v1.ListTwinsRequest
	(*ListTwinsResponse)(nil),         // 26: paryty.v1.ListTwinsResponse
	(*GetTwinRequest)(nil),            // 27: paryty.v1.GetTwinRequest
	(*UpdateTwinRequest)(nil),         // 28: paryty.v1.UpdateTwinRequest
	(*DeleteTwinRequest)(nil),         // 29: paryty.v1.DeleteTwinRequest
	(*GetTwinConfigRequest)(nil),      // 30: paryty.v1.GetTwinConfigRequest
	(*ResolveIdentityRequest)(nil),    // 31: paryty.v1.ResolveIdentityRequest
	(*ResolveIdentityResponse)(nil),   // 32: paryty.v1.ResolveIdentityResponse
	(*AssignAgentToTwinRequest)(nil),  // 33: paryty.v1.AssignAgentToTwinRequest
	(*AssignAgentToTwinResponse)(nil), // 34: paryty.v1.AssignAgentToTwinResponse
	(*ListTwinAgentsRequest)(nil),     // 35: paryty.v1.ListTwinAgentsRequest
	(*ListTwinAgentsResponse)(nil),    // 36: paryty.v1.ListTwinAgentsResponse
	(*TwinAgentInfo)(nil),             // 37: paryty.v1.TwinAgentInfo
	(*AcceptBacklogRequest)(nil),      // 38: paryty.v1.AcceptBacklogRequest
	(*AcceptBacklogResponse)(nil),     // 39: paryty.v1.AcceptBacklogResponse
	(*RejectBacklogRequest)(nil),      // 40: paryty.v1.RejectBacklogRequest
	(*RejectBacklogResponse)(nil),     // 41: paryty.v1.RejectBacklogResponse
	nil,                               // 42: paryty.v1.UserInfo.PermissionsEntry
	nil,                               // 43: paryty.v1.CreateSubUserRequest.PermissionsEntry
	nil,                               // 44: paryty.v1.UpdatePermissionsRequest.PermissionsEntry
	nil,                               // 45: paryty.v1.PlanInfo.FeaturesEntry
	nil,                               // 46: paryty.v1.PlanFeaturesResponse.FeaturesEntry
	nil,                               // 47: paryty.v1.TwinConfig.AgentLabelsEntry
	(*timestamppb.Timestamp)(nil),     // 48: google.protobuf.Timestamp
	(*PaginationRequest)(nil),         // 49: paryty.v1.PaginationRequest
	(*PaginationResponse)(nil),        // 50: paryty.v1.PaginationResponse
	(*emptypb.Empty)(nil),             // 51: google.protobuf.Empty
}
var file_paryty_v1_auth_proto_depIdxs = []int32{
	8,  // 0: paryty.v1.LoginResponse.user:type_name -> paryty.v1.UserInfo
	48, // 1: paryty.v1.ValidateTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	42, // 2: paryty.v1.UserInfo.permissions:type_name -> paryty.v1.UserInfo.PermissionsEntry
	48, // 3: paryty.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	43, // 4: paryty.v1.CreateSubUserRequest.permissions:type_name -> paryty.v1.CreateSubUserRequest.PermissionsEntry
	49, // 5: paryty.v1.ListUsersRequest.pagination:type_name -> paryty.v1.PaginationRequest
	8,  // 6: paryty.v1.ListUsersResponse.users:type_name -> paryty.v1.UserInfo
	50, // 7: paryty.v1.ListUsersResponse.pagination:type_name -> paryty.v1.PaginationResponse
	44, // 8: paryty.v1.UpdatePermissionsRequest.permissions:type_name -> paryty.v1.UpdatePermissionsRequest.PermissionsEntry
	17, // 9: paryty.v1.ListPlansResponse.plans:type_name -> paryty.v1.PlanInfo
	45, // 10: paryty.v1.PlanInfo.features:type_name -> paryty.v1.PlanInfo.FeaturesEntry
	18, // 11: paryty.v1.PlanInfo.limits:type_name -> paryty.v1.PlanLimits
	19, // 12: paryty.v1.PlanInfo.quotas:type_name -> paryty.v1.PlanQuotas
	20, // 13: paryty.v1.PlanInfo.usage:type_name -> paryty.v1.PlanUsage
	46, // 14: paryty.v1.PlanFeaturesResponse.features:type_name -> paryty.v1.PlanFeaturesResponse.FeaturesEntry
	24, // 15: paryty.v1.CreateTwinRequest.config:type_name -> paryty.v1.TwinConfig
	24, // 16: paryty.v1.TwinInfo.config:type_name -> paryty.v1.TwinConfig
	48, // 17: paryty.v1.TwinInfo.created_at:type_name -> google.protobuf.Timestamp
	48, // 18: paryty.v1.TwinInfo.updated_at:type_name -> google.protobuf.Timestamp
	47, // 19: paryty.v1.TwinConfig.agent_labels:type_name -> paryty.v1.TwinConfig.AgentLabelsEntry
	49, // 20: paryty.v1.ListTwinsRequest.pagination:type_name -> paryty.v1.PaginationRequest
	23, // 21: paryty.v1.ListTwinsResponse.twins:type_name -> paryty.v1.TwinInfo
	50, // 22: paryty.v1.ListTwinsResponse.pagination:type_name -> paryty.v1.PaginationResponse
	24, // 23: paryty.v1.UpdateTwinRequest.config:type_name -> paryty.v1.TwinConfig
	37, // 24: paryty.v1.ListTwinAgentsResponse.agents:type_name -> paryty.v1.TwinAgentInfo
	48, // 25: paryty.v1.TwinAgentInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	0,  // 26: paryty.v1.AuthService.Register:input_type -> paryty.v1.RegisterRequest
	2,  // 27: paryty.v1.AuthService.Login:input_type -> paryty.v1.LoginRequest
	4,  // 28: paryty.v1.AuthService.RefreshToken:input_type -> paryty.v1.RefreshTokenRequest
	5,  // 29: paryty.v1.AuthService.Logout:input_type -> paryty.v1.LogoutRequest
	6,  // 30: paryty.v1.AuthService.ValidateToken:input_type -> paryty.v1.ValidateTokenRequest
	9,  // 31: paryty.v1.UserService.CreateSubUser:input_type -> paryty.v1.CreateSubUserRequest
	10, // 32: paryty.v1.UserService.ListUsers:input_type -> paryty.v1.ListUsersRequest
	12, // 33: paryty.v1.UserService.GetUser:input_type -> paryty.v1.GetUserRequest
	13, // 34: paryty.v1.UserService.UpdateUser:input_type -> paryty.v1.UpdateUserRequest
	14, // 35: paryty.v1.UserService.DeleteUser:input_type -> paryty.v1.DeleteUserRequest
	15, // 36: paryty.v1.UserService.UpdatePermissions:input_type -> paryty.v1.UpdatePermissionsRequest
	51, // 37: paryty.v1.PlanService.ListPlans:input_type -> google.protobuf.Empty
	51, // 38: paryty.v1.PlanService.GetCurrentPlan:input_type -> google.protobuf.Empty
	51, // 39: paryty.v1.PlanService.GetPlanFeatures:input_type -> google.protobuf.Empty
	22, // 40: paryty.v1.TwinService.CreateTwin:input_type -> paryty.v1.CreateTwinRequest
	25, // 41: paryty.v1.TwinService.ListTwins:input_type -> paryty.v1.ListTwinsRequest
	27, // 42: paryty.v1.TwinService.GetTwin:input_type -> paryty.v1.GetTwinRequest
	28, // 43: paryty.v1.TwinService.UpdateTwin:input_type -> paryty.v1.UpdateTwinRequest
	29, // 44: paryty.v1.TwinService.DeleteTwin:input_type -> paryty.v1.DeleteTwinRequest
	30, // 45: paryty.v1.TwinService.GetTwinConfig:input_type -> paryty.v1.GetTwinConfigRequest
	31, // 46: paryty.v1.TwinService.ResolveIdentity:input_type -> paryty.v1.ResolveIdentityRequest
	33, // 47: paryty.v1.TwinService.AssignAgentToTwin:input_type -> paryty.v1.AssignAgentToTwinRequest
	35, // 48: paryty.v1.TwinService.ListTwinAgents:input_type -> paryty.v1.ListTwinAgentsRequest
	38, // 49: paryty.v1.TwinService.AcceptBacklog:input_type -> paryty.v1.AcceptBacklogRequest
	40, // 50: paryty.v1.TwinService.RejectBacklog:input_type -> paryty.v1.RejectBacklogRequest
	1,  // 51: paryty.v1.AuthService.Register:output_type -> paryty.v1.RegisterResponse
	3,  // 52: paryty.v1.AuthService.Login:output_type -> paryty.v1.LoginResponse
	3,  // 53: paryty.v1.AuthService.RefreshToken:output_type -> paryty.v1.LoginResponse
	51, // 54: paryty.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	7,  // 55: paryty.v1.AuthService.ValidateToken:output_type -> paryty.v1.ValidateTokenResponse
	8,  // 56: paryty.v1.UserService.CreateSubUser:output_type -> paryty.v1.UserInfo
	11, // 57: paryty.v1.UserService.ListUsers:output_type -> paryty.v1.ListUsersResponse
	8,  // 58: paryty.v1.UserService.GetUser:output_type -> paryty.v1.UserInfo
	8,  // 59: paryty.v1.UserService.UpdateUser:output_type -> paryty.v1.UserInfo
	51, // 60: paryty.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	8,  // 61: paryty.v1.UserService.UpdatePermissions:output_type -> paryty.v1.UserInfo
	16, // 62: paryty.v1.PlanService.ListPlans:output_type -> paryty.v1.ListPlansResponse
	17, // 63: paryty.v1.PlanService.GetCurrentPlan:output_type -> paryty.v1.PlanInfo
	21, // 64: paryty.v1.PlanService.GetPlanFeatures:output_type -> paryty.v1.PlanFeaturesResponse
	23, // 65: paryty.v1.TwinService.CreateTwin:output_type -> paryty.v1.TwinInfo
	26, // 66: paryty.v1.TwinService.ListTwins:output_type -> paryty.v1.ListTwinsResponse
	23, // 67: paryty.v1.TwinService.GetTwin:output_type -> paryty.v1.TwinInfo
	23, // 68: paryty.v1.TwinService.UpdateTwin:output_type -> paryty.v1.TwinInfo
	51, // 69: paryty.v1.TwinService.DeleteTwin:output_type -> google.protobuf.Empty
	24, // 70: paryty.v1.TwinService.GetTwinConfig:output_type -> paryty.v1.TwinConfig
	32, // 71: paryty.v1.TwinService.ResolveIdentity:output_type -> paryty.v1.ResolveIdentityResponse
	34, // 72: paryty.v1.TwinService.AssignAgentToTwin:output_type -> paryty.v1.AssignAgentToTwinResponse
	36, // 73: paryty.v1.TwinService.ListTwinAgents:output_type -> paryty.v1.ListTwinAgentsResponse
	39, // 74: paryty.v1.TwinService.AcceptBacklog:output_type -> paryty.v1.AcceptBacklogResponse
	41, // 75: paryty.v1.TwinService.RejectBacklog:output_type -> paryty.v1.RejectBacklogResponse
	51, // [51:76] is the sub-list for method output_type
	26, // [26:51] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_paryty_v1_auth_proto_init() }
func file_paryty_v1_auth_proto_init() {
	if File_paryty_v1_auth_proto != nil {
		return
	}
	file_paryty_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_auth_proto_rawDesc), len(file_paryty_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_paryty_v1_auth_proto_goTypes,
		DependencyIndexes: file_paryty_v1_auth_proto_depIdxs,
		MessageInfos:      file_paryty_v1_auth_proto_msgTypes,
	}.Build()
	File_paryty_v1_auth_proto = out.File
	file_paryty_v1_auth_proto_goTypes = nil
	file_paryty_v1_auth_proto_depIdxs = nil
}
