// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: paryty/v1/common.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents the health state of a component.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 4
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
		4: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
		"HEALTH_STATUS_UNKNOWN":     4,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_common_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_paryty_v1_common_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{0}
}

// Severity represents alert/event severity levels.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_CRITICAL    Severity = 1
	Severity_SEVERITY_HIGH        Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_LOW         Severity = 4
	Severity_SEVERITY_INFO        Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_CRITICAL",
		2: "SEVERITY_HIGH",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_LOW",
		5: "SEVERITY_INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_CRITICAL":    1,
		"SEVERITY_HIGH":        2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_LOW":         4,
		"SEVERITY_INFO":        5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_common_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_paryty_v1_common_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{1}
}

// PaginationRequest controls result set pagination.
type PaginationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for the next page. Empty for first page.
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Maximum number of results per page. Default 50, max 500.
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_paryty_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PaginationResponse provides pagination metadata.
type PaginationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for the next page. Empty if no more results.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of results available.
	TotalCount    int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_paryty_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PaginationResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Labels is a set of key-value metadata pairs.
type Labels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_paryty_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Labels) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

// TimeRange represents a time window for queries.
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_paryty_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeRange) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Error represents a structured error response.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable error code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Additional error details.
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_paryty_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// AgentCapabilities describes what an agent can collect.
type AgentCapabilities struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasMetalScraper bool                   `protobuf:"varint,1,opt,name=has_metal_scraper,json=hasMetalScraper,proto3" json:"has_metal_scraper,omitempty"`
	HasEbpfObserver bool                   `protobuf:"varint,2,opt,name=has_ebpf_observer,json=hasEbpfObserver,proto3" json:"has_ebpf_observer,omitempty"`
	HasSupervisor   bool                   `protobuf:"varint,3,opt,name=has_supervisor,json=hasSupervisor,proto3" json:"has_supervisor,omitempty"`
	HasSdk          bool                   `protobuf:"varint,4,opt,name=has_sdk,json=hasSdk,proto3" json:"has_sdk,omitempty"`
	// Supported compression algorithms.
	SupportedCompression []string `protobuf:"bytes,5,rep,name=supported_compression,json=supportedCompression,proto3" json:"supported_compression,omitempty"`
	// Agent platform info.
	Os            string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_paryty_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_paryty_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *AgentCapabilities) GetHasMetalScraper() bool {
	if x != nil {
		return x.HasMetalScraper
	}
	return false
}

func (x *AgentCapabilities) GetHasEbpfObserver() bool {
	if x != nil {
		return x.HasEbpfObserver
	}
	return false
}

func (x *AgentCapabilities) GetHasSupervisor() bool {
	if x != nil {
		return x.HasSupervisor
	}
	return false
}

func (x *AgentCapabilities) GetHasSdk() bool {
	if x != nil {
		return x.HasSdk
	}
	return false
}

func (x *AgentCapabilities) GetSupportedCompression() []string {
	if x != nil {
		return x.SupportedCompression
	}
	return nil
}

func (x *AgentCapabilities) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentCapabilities) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

var File_paryty_v1_common_proto protoreflect.FileDescriptor

const file_paryty_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16paryty/v1/common.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"O\n" +
	"\x11PaginationRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"]\n" +
	"\x12PaginationResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"~\n" +
	"\x06Labels\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.paryty.v1.Labels.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\tTimeRange\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xaa\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\adetails\x18\x03 \x03(\v2\x1d.paryty.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x11AgentCapabilities\x12*\n" +
	"\x11has_metal_scraper\x18\x01 \x01(\bR\x0fhasMetalScraper\x12*\n" +
	"\x11has_ebpf_observer\x18\x02 \x01(\bR\x0fhasEbpfObserver\x12%\n" +
	"\x0ehas_supervisor\x18\x03 \x01(\bR\rhasSupervisor\x12\x17\n" +
	"\ahas_sdk\x18\x04 \x01(\bR\x06hasSdk\x123\n" +
	"\x15supported_compression\x18\x05 \x03(\tR\x14supportedCompression\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch*\x9c\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x03\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x04*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x01\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x04\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x05B?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_common_proto_rawDescOnce sync.Once
	file_paryty_v1_common_proto_rawDescData []byte
)

func file_paryty_v1_common_proto_rawDescGZIP() []byte {
	file_paryty_v1_common_proto_rawDescOnce.Do(func() {
		file_paryty_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_common_proto_rawDesc), len(file_paryty_v1_common_proto_rawDesc)))
	})
	return file_paryty_v1_common_proto_rawDescData
}

var file_paryty_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_paryty_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_paryty_v1_common_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: paryty.v1.HealthStatus
	(Severity)(0),                 // 1: paryty.v1.Severity
	(*PaginationRequest)(nil),     // 2: paryty.v1.PaginationRequest
	(*PaginationResponse)(nil),    // 3: paryty.v1.PaginationResponse
	(*Labels)(nil),                // 4: paryty.v1.Labels
	(*TimeRange)(nil),             // 5: paryty.v1.TimeRange
	(*Error)(nil),                 // 6: paryty.v1.Error
	(*AgentCapabilities)(nil),     // 7: paryty.v1.AgentCapabilities
	nil,                           // 8: paryty.v1.Labels.EntriesEntry
	nil,                           // 9: paryty.v1.Error.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_paryty_v1_common_proto_depIdxs = []int32{
	8,  // 0: paryty.v1.Labels.entries:type_name -> paryty.v1.Labels.EntriesEntry
	10, // 1: paryty.v1.TimeRange.start_time:type_name -> google.protobuf.Timestamp
	10, // 2: paryty.v1.TimeRange.end_time:type_name -> google.protobuf.Timestamp
	9,  // 3: paryty.v1.Error.details:type_name -> paryty.v1.Error.DetailsEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_paryty_v1_common_proto_init() }
func file_paryty_v1_common_proto_init() {
	if File_paryty_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_common_proto_rawDesc), len(file_paryty_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paryty_v1_common_proto_goTypes,
		DependencyIndexes: file_paryty_v1_common_proto_depIdxs,
		EnumInfos:         file_paryty_v1_common_proto_enumTypes,
		MessageInfos:      file_paryty_v1_common_proto_msgTypes,
	}.Build()
	File_paryty_v1_common_proto = out.File
	file_paryty_v1_common_proto_goTypes = nil
	file_paryty_v1_common_proto_depIdxs = nil
}
