// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: paryty/v1/ebpf.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TcpEventType describes what happened to a TCP connection.
type TcpEventType int32

const (
	TcpEventType_TCP_EVENT_TYPE_UNSPECIFIED TcpEventType = 0
	TcpEventType_TCP_EVENT_TYPE_CONNECT     TcpEventType = 1
	TcpEventType_TCP_EVENT_TYPE_ACCEPT      TcpEventType = 2
	TcpEventType_TCP_EVENT_TYPE_CLOSE       TcpEventType = 3
	TcpEventType_TCP_EVENT_TYPE_RESET       TcpEventType = 4
)

// Enum value maps for TcpEventType.
var (
	TcpEventType_name = map[int32]string{
		0: "TCP_EVENT_TYPE_UNSPECIFIED",
		1: "TCP_EVENT_TYPE_CONNECT",
		2: "TCP_EVENT_TYPE_ACCEPT",
		3: "TCP_EVENT_TYPE_CLOSE",
		4: "TCP_EVENT_TYPE_RESET",
	}
	TcpEventType_value = map[string]int32{
		"TCP_EVENT_TYPE_UNSPECIFIED": 0,
		"TCP_EVENT_TYPE_CONNECT":     1,
		"TCP_EVENT_TYPE_ACCEPT":      2,
		"TCP_EVENT_TYPE_CLOSE":       3,
		"TCP_EVENT_TYPE_RESET":       4,
	}
)

func (x TcpEventType) Enum() *TcpEventType {
	p := new(TcpEventType)
	*p = x
	return p
}

func (x TcpEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TcpEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_ebpf_proto_enumTypes[0].Descriptor()
}

func (TcpEventType) Type() protoreflect.EnumType {
	return &file_paryty_v1_ebpf_proto_enumTypes[0]
}

func (x TcpEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TcpEventType.Descriptor instead.
func (TcpEventType) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{0}
}

// TcpState represents the state of a TCP connection.
type TcpState int32

const (
	TcpState_TCP_STATE_UNSPECIFIED  TcpState = 0
	TcpState_TCP_STATE_ESTABLISHED  TcpState = 1
	TcpState_TCP_STATE_SYN_SENT     TcpState = 2
	TcpState_TCP_STATE_SYN_RECEIVED TcpState = 3
	TcpState_TCP_STATE_FIN_WAIT_1   TcpState = 4
	TcpState_TCP_STATE_FIN_WAIT_2   TcpState = 5
	TcpState_TCP_STATE_TIME_WAIT    TcpState = 6
	TcpState_TCP_STATE_CLOSE_WAIT   TcpState = 7
	TcpState_TCP_STATE_LAST_ACK     TcpState = 8
	TcpState_TCP_STATE_CLOSING      TcpState = 9
	TcpState_TCP_STATE_LISTEN       TcpState = 10
)

// Enum value maps for TcpState.
var (
	TcpState_name = map[int32]string{
		0:  "TCP_STATE_UNSPECIFIED",
		1:  "TCP_STATE_ESTABLISHED",
		2:  "TCP_STATE_SYN_SENT",
		3:  "TCP_STATE_SYN_RECEIVED",
		4:  "TCP_STATE_FIN_WAIT_1",
		5:  "TCP_STATE_FIN_WAIT_2",
		6:  "TCP_STATE_TIME_WAIT",
		7:  "TCP_STATE_CLOSE_WAIT",
		8:  "TCP_STATE_LAST_ACK",
		9:  "TCP_STATE_CLOSING",
		10: "TCP_STATE_LISTEN",
	}
	TcpState_value = map[string]int32{
		"TCP_STATE_UNSPECIFIED":  0,
		"TCP_STATE_ESTABLISHED":  1,
		"TCP_STATE_SYN_SENT":     2,
		"TCP_STATE_SYN_RECEIVED": 3,
		"TCP_STATE_FIN_WAIT_1":   4,
		"TCP_STATE_FIN_WAIT_2":   5,
		"TCP_STATE_TIME_WAIT":    6,
		"TCP_STATE_CLOSE_WAIT":   7,
		"TCP_STATE_LAST_ACK":     8,
		"TCP_STATE_CLOSING":      9,
		"TCP_STATE_LISTEN":       10,
	}
)

func (x TcpState) Enum() *TcpState {
	p := new(TcpState)
	*p = x
	return p
}

func (x TcpState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TcpState) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_ebpf_proto_enumTypes[1].Descriptor()
}

func (TcpState) Type() protoreflect.EnumType {
	return &file_paryty_v1_ebpf_proto_enumTypes[1]
}

func (x TcpState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TcpState.Descriptor instead.
func (TcpState) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{1}
}

// NetworkEvent is a network-level observation from eBPF.
type NetworkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the event was captured.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event type.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*NetworkEvent_TcpConnection
	//	*NetworkEvent_DnsQuery
	//	*NetworkEvent_HttpRequest
	//	*NetworkEvent_DbQuery
	Event         isNetworkEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_paryty_v1_ebpf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_ebpf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NetworkEvent) GetEvent() isNetworkEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NetworkEvent) GetTcpConnection() *TcpConnectionEvent {
	if x != nil {
		if x, ok := x.Event.(*NetworkEvent_TcpConnection); ok {
			return x.TcpConnection
		}
	}
	return nil
}

func (x *NetworkEvent) GetDnsQuery() *DnsQueryEvent {
	if x != nil {
		if x, ok := x.Event.(*NetworkEvent_DnsQuery); ok {
			return x.DnsQuery
		}
	}
	return nil
}

func (x *NetworkEvent) GetHttpRequest() *HttpRequestEvent {
	if x != nil {
		if x, ok := x.Event.(*NetworkEvent_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *NetworkEvent) GetDbQuery() *DbQueryEvent {
	if x != nil {
		if x, ok := x.Event.(*NetworkEvent_DbQuery); ok {
			return x.DbQuery
		}
	}
	return nil
}

type isNetworkEvent_Event interface {
	isNetworkEvent_Event()
}

type NetworkEvent_TcpConnection struct {
	TcpConnection *TcpConnectionEvent `protobuf:"bytes,2,opt,name=tcp_connection,json=tcpConnection,proto3,oneof"`
}

type NetworkEvent_DnsQuery struct {
	DnsQuery *DnsQueryEvent `protobuf:"bytes,3,opt,name=dns_query,json=dnsQuery,proto3,oneof"`
}

type NetworkEvent_HttpRequest struct {
	HttpRequest *HttpRequestEvent `protobuf:"bytes,4,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type NetworkEvent_DbQuery struct {
	DbQuery *DbQueryEvent `protobuf:"bytes,5,opt,name=db_query,json=dbQuery,proto3,oneof"`
}

func (*NetworkEvent_TcpConnection) isNetworkEvent_Event() {}

func (*NetworkEvent_DnsQuery) isNetworkEvent_Event() {}

func (*NetworkEvent_HttpRequest) isNetworkEvent_Event() {}

func (*NetworkEvent_DbQuery) isNetworkEvent_Event() {}

// TcpConnectionEvent represents a TCP connection lifecycle event.
type TcpConnectionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type.
	Type TcpEventType `protobuf:"varint,1,opt,name=type,proto3,enum=paryty.v1.TcpEventType" json:"type,omitempty"`
	// Source IP address.
	SourceIp string `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Source port.
	SourcePort int32 `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// Destination IP address.
	DestinationIp string `protobuf:"bytes,4,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	// Destination port.
	DestinationPort int32 `protobuf:"varint,5,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// Connection state.
	State TcpState `protobuf:"varint,6,opt,name=state,proto3,enum=paryty.v1.TcpState" json:"state,omitempty"`
	// Duration of the connection (for close events).
	DurationMs int64 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Bytes sent on this connection.
	BytesSent int64 `protobuf:"varint,8,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Bytes received on this connection.
	BytesReceived int64 `protobuf:"varint,9,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// PID of the process that owns this connection.
	Pid int32 `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	// Process name.
	ProcessName   string `protobuf:"bytes,11,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpConnectionEvent) Reset() {
	*x = TcpConnectionEvent{}
	mi := &file_paryty_v1_ebpf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpConnectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpConnectionEvent) ProtoMessage() {}

func (x *TcpConnectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_ebpf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpConnectionEvent.ProtoReflect.Descriptor instead.
func (*TcpConnectionEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{1}
}

func (x *TcpConnectionEvent) GetType() TcpEventType {
	if x != nil {
		return x.Type
	}
	return TcpEventType_TCP_EVENT_TYPE_UNSPECIFIED
}

func (x *TcpConnectionEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *TcpConnectionEvent) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *TcpConnectionEvent) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *TcpConnectionEvent) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *TcpConnectionEvent) GetState() TcpState {
	if x != nil {
		return x.State
	}
	return TcpState_TCP_STATE_UNSPECIFIED
}

func (x *TcpConnectionEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TcpConnectionEvent) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TcpConnectionEvent) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TcpConnectionEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TcpConnectionEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// DnsQueryEvent represents a DNS resolution event.
type DnsQueryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query name (e.g., "api.example.com").
	QueryName string `protobuf:"bytes,1,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	// Query type (A, AAAA, CNAME, etc.).
	QueryType string `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	// Resolved IP addresses.
	ResolvedIps []string `protobuf:"bytes,3,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	// Response code (NOERROR, NXDOMAIN, etc.).
	ResponseCode string `protobuf:"bytes,4,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// Time to live in seconds.
	TtlSeconds int32 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Query latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// PID of the process that made the query.
	Pid int32 `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	// Process name.
	ProcessName   string `protobuf:"bytes,8,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsQueryEvent) Reset() {
	*x = DnsQueryEvent{}
	mi := &file_paryty_v1_ebpf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsQueryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsQueryEvent) ProtoMessage() {}

func (x *DnsQueryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_ebpf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsQueryEvent.ProtoReflect.Descriptor instead.
func (*DnsQueryEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{2}
}

func (x *DnsQueryEvent) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *DnsQueryEvent) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *DnsQueryEvent) GetResolvedIps() []string {
	if x != nil {
		return x.ResolvedIps
	}
	return nil
}

func (x *DnsQueryEvent) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *DnsQueryEvent) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DnsQueryEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DnsQueryEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DnsQueryEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// HttpRequestEvent represents an HTTP request/response pair.
type HttpRequestEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP method (GET, POST, etc.).
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Request path.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// HTTP version (1.1, 2.0).
	HttpVersion string `protobuf:"bytes,3,opt,name=http_version,json=httpVersion,proto3" json:"http_version,omitempty"`
	// Response status code.
	StatusCode int32 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Request latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Request content length in bytes.
	RequestBytes int64 `protobuf:"varint,6,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	// Response content length in bytes.
	ResponseBytes int64 `protobuf:"varint,7,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	// Source IP.
	SourceIp string `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Destination IP.
	DestinationIp string `protobuf:"bytes,9,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	// Destination port.
	DestinationPort int32 `protobuf:"varint,10,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// PID of the process.
	Pid int32 `protobuf:"varint,11,opt,name=pid,proto3" json:"pid,omitempty"`
	// Process name.
	ProcessName string `protobuf:"bytes,12,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Host header value.
	Host string `protobuf:"bytes,13,opt,name=host,proto3" json:"host,omitempty"`
	// User agent.
	UserAgent     string `protobuf:"bytes,14,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequestEvent) Reset() {
	*x = HttpRequestEvent{}
	mi := &file_paryty_v1_ebpf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequestEvent) ProtoMessage() {}

func (x *HttpRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_ebpf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequestEvent.ProtoReflect.Descriptor instead.
func (*HttpRequestEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{3}
}

func (x *HttpRequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequestEvent) GetHttpVersion() string {
	if x != nil {
		return x.HttpVersion
	}
	return ""
}

func (x *HttpRequestEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpRequestEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HttpRequestEvent) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *HttpRequestEvent) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

func (x *HttpRequestEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *HttpRequestEvent) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *HttpRequestEvent) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *HttpRequestEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HttpRequestEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *HttpRequestEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpRequestEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// DbQueryEvent represents a database query event.
type DbQueryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database protocol (postgresql, mysql, redis).
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Query/command text (truncated to 1KB).
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Query type (SELECT, INSERT, UPDATE, DELETE, etc.).
	QueryType string `protobuf:"bytes,3,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	// Target database name.
	Database string `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	// Query latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Number of rows affected/returned.
	RowCount int64 `protobuf:"varint,6,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// Error message (if query failed).
	ErrorMessage string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Source IP.
	SourceIp string `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// Destination IP.
	DestinationIp string `protobuf:"bytes,9,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	// Destination port.
	DestinationPort int32 `protobuf:"varint,10,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// PID of the process.
	Pid int32 `protobuf:"varint,11,opt,name=pid,proto3" json:"pid,omitempty"`
	// Process name.
	ProcessName   string `protobuf:"bytes,12,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbQueryEvent) Reset() {
	*x = DbQueryEvent{}
	mi := &file_paryty_v1_ebpf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbQueryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbQueryEvent) ProtoMessage() {}

func (x *DbQueryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_ebpf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbQueryEvent.ProtoReflect.Descriptor instead.
func (*DbQueryEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_ebpf_proto_rawDescGZIP(), []int{4}
}

func (x *DbQueryEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DbQueryEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DbQueryEvent) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *DbQueryEvent) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DbQueryEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DbQueryEvent) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *DbQueryEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DbQueryEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *DbQueryEvent) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *DbQueryEvent) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *DbQueryEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DbQueryEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

var File_paryty_v1_ebpf_proto protoreflect.FileDescriptor

const file_paryty_v1_ebpf_proto_rawDesc = "" +
	"\n" +
	"\x14paryty/v1/ebpf.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\fNetworkEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12F\n" +
	"\x0etcp_connection\x18\x02 \x01(\v2\x1d.paryty.v1.TcpConnectionEventH\x00R\rtcpConnection\x127\n" +
	"\tdns_query\x18\x03 \x01(\v2\x18.paryty.v1.DnsQueryEventH\x00R\bdnsQuery\x12@\n" +
	"\fhttp_request\x18\x04 \x01(\v2\x1b.paryty.v1.HttpRequestEventH\x00R\vhttpRequest\x124\n" +
	"\bdb_query\x18\x05 \x01(\v2\x17.paryty.v1.DbQueryEventH\x00R\adbQueryB\a\n" +
	"\x05event\"\x98\x03\n" +
	"\x12TcpConnectionEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.paryty.v1.TcpEventTypeR\x04type\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\x05R\n" +
	"sourcePort\x12%\n" +
	"\x0edestination_ip\x18\x04 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x05 \x01(\x05R\x0fdestinationPort\x12)\n" +
	"\x05state\x18\x06 \x01(\x0e2\x13.paryty.v1.TcpStateR\x05state\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\b \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\t \x01(\x03R\rbytesReceived\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\v \x01(\tR\vprocessName\"\x8a\x02\n" +
	"\rDnsQueryEvent\x12\x1d\n" +
	"\n" +
	"query_name\x18\x01 \x01(\tR\tqueryName\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x12!\n" +
	"\fresolved_ips\x18\x03 \x03(\tR\vresolvedIps\x12#\n" +
	"\rresponse_code\x18\x04 \x01(\tR\fresponseCode\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x05R\n" +
	"ttlSeconds\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\b \x01(\tR\vprocessName\"\xc4\x03\n" +
	"\x10HttpRequestEvent\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fhttp_version\x18\x03 \x01(\tR\vhttpVersion\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12#\n" +
	"\rrequest_bytes\x18\x06 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\a \x01(\x03R\rresponseBytes\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x12%\n" +
	"\x0edestination_ip\x18\t \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\n" +
	" \x01(\x05R\x0fdestinationPort\x12\x10\n" +
	"\x03pid\x18\v \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\f \x01(\tR\vprocessName\x12\x12\n" +
	"\x04host\x18\r \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0e \x01(\tR\tuserAgent\"\x80\x03\n" +
	"\fDbQueryEvent\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"query_type\x18\x03 \x01(\tR\tqueryType\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\x1b\n" +
	"\trow_count\x18\x06 \x01(\x03R\browCount\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x12%\n" +
	"\x0edestination_ip\x18\t \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\n" +
	" \x01(\x05R\x0fdestinationPort\x12\x10\n" +
	"\x03pid\x18\v \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\f \x01(\tR\vprocessName*\x99\x01\n" +
	"\fTcpEventType\x12\x1e\n" +
	"\x1aTCP_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TCP_EVENT_TYPE_CONNECT\x10\x01\x12\x19\n" +
	"\x15TCP_EVENT_TYPE_ACCEPT\x10\x02\x12\x18\n" +
	"\x14TCP_EVENT_TYPE_CLOSE\x10\x03\x12\x18\n" +
	"\x14TCP_EVENT_TYPE_RESET\x10\x04*\xa0\x02\n" +
	"\bTcpState\x12\x19\n" +
	"\x15TCP_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TCP_STATE_ESTABLISHED\x10\x01\x12\x16\n" +
	"\x12TCP_STATE_SYN_SENT\x10\x02\x12\x1a\n" +
	"\x16TCP_STATE_SYN_RECEIVED\x10\x03\x12\x18\n" +
	"\x14TCP_STATE_FIN_WAIT_1\x10\x04\x12\x18\n" +
	"\x14TCP_STATE_FIN_WAIT_2\x10\x05\x12\x17\n" +
	"\x13TCP_STATE_TIME_WAIT\x10\x06\x12\x18\n" +
	"\x14TCP_STATE_CLOSE_WAIT\x10\a\x12\x16\n" +
	"\x12TCP_STATE_LAST_ACK\x10\b\x12\x15\n" +
	"\x11TCP_STATE_CLOSING\x10\t\x12\x14\n" +
	"\x10TCP_STATE_LISTEN\x10\n" +
	"B?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_ebpf_proto_rawDescOnce sync.Once
	file_paryty_v1_ebpf_proto_rawDescData []byte
)

func file_paryty_v1_ebpf_proto_rawDescGZIP() []byte {
	file_paryty_v1_ebpf_proto_rawDescOnce.Do(func() {
		file_paryty_v1_ebpf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_ebpf_proto_rawDesc), len(file_paryty_v1_ebpf_proto_rawDesc)))
	})
	return file_paryty_v1_ebpf_proto_rawDescData
}

var file_paryty_v1_ebpf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_paryty_v1_ebpf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_paryty_v1_ebpf_proto_goTypes = []any{
	(TcpEventType)(0),             // 0: paryty.v1.TcpEventType
	(TcpState)(0),                 // 1: paryty.v1.TcpState
	(*NetworkEvent)(nil),          // 2: paryty.v1.NetworkEvent
	(*TcpConnectionEvent)(nil),    // 3: paryty.v1.TcpConnectionEvent
	(*DnsQueryEvent)(nil),         // 4: paryty.v1.DnsQueryEvent
	(*HttpRequestEvent)(nil),      // 5: paryty.v1.HttpRequestEvent
	(*DbQueryEvent)(nil),          // 6: paryty.v1.DbQueryEvent
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_paryty_v1_ebpf_proto_depIdxs = []int32{
	7, // 0: paryty.v1.NetworkEvent.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: paryty.v1.NetworkEvent.tcp_connection:type_name -> paryty.v1.TcpConnectionEvent
	4, // 2: paryty.v1.NetworkEvent.dns_query:type_name -> paryty.v1.DnsQueryEvent
	5, // 3: paryty.v1.NetworkEvent.http_request:type_name -> paryty.v1.HttpRequestEvent
	6, // 4: paryty.v1.NetworkEvent.db_query:type_name -> paryty.v1.DbQueryEvent
	0, // 5: paryty.v1.TcpConnectionEvent.type:type_name -> paryty.v1.TcpEventType
	1, // 6: paryty.v1.TcpConnectionEvent.state:type_name -> paryty.v1.TcpState
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_paryty_v1_ebpf_proto_init() }
func file_paryty_v1_ebpf_proto_init() {
	if File_paryty_v1_ebpf_proto != nil {
		return
	}
	file_paryty_v1_ebpf_proto_msgTypes[0].OneofWrappers = []any{
		(*NetworkEvent_TcpConnection)(nil),
		(*NetworkEvent_DnsQuery)(nil),
		(*NetworkEvent_HttpRequest)(nil),
		(*NetworkEvent_DbQuery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_ebpf_proto_rawDesc), len(file_paryty_v1_ebpf_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paryty_v1_ebpf_proto_goTypes,
		DependencyIndexes: file_paryty_v1_ebpf_proto_depIdxs,
		EnumInfos:         file_paryty_v1_ebpf_proto_enumTypes,
		MessageInfos:      file_paryty_v1_ebpf_proto_msgTypes,
	}.Build()
	File_paryty_v1_ebpf_proto = out.File
	file_paryty_v1_ebpf_proto_goTypes = nil
	file_paryty_v1_ebpf_proto_depIdxs = nil
}
