// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paryty/v1/forecasting.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForecastMetricRequest requests a forecast for a single metric.
type ForecastMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent to forecast for. Empty = aggregate across all agents.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope for the forecast.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Metric name (e.g., "cpu_usage", "memory_usage", "disk_usage").
	MetricName string `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// How far ahead to forecast in seconds. Default: 604800 (7 days).
	HorizonSeconds int64 `protobuf:"varint,4,opt,name=horizon_seconds,json=horizonSeconds,proto3" json:"horizon_seconds,omitempty"`
	// Confidence level: 95 or 99. Default: 95.
	ConfidenceLevel int32 `protobuf:"varint,5,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	// Time step between forecast points in seconds. Default: 300 (5 min).
	StepSeconds   int32 `protobuf:"varint,6,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastMetricRequest) Reset() {
	*x = ForecastMetricRequest{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastMetricRequest) ProtoMessage() {}

func (x *ForecastMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastMetricRequest.ProtoReflect.Descriptor instead.
func (*ForecastMetricRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{0}
}

func (x *ForecastMetricRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ForecastMetricRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ForecastMetricRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ForecastMetricRequest) GetHorizonSeconds() int64 {
	if x != nil {
		return x.HorizonSeconds
	}
	return 0
}

func (x *ForecastMetricRequest) GetConfidenceLevel() int32 {
	if x != nil {
		return x.ConfidenceLevel
	}
	return 0
}

func (x *ForecastMetricRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

// ForecastMetricResponse contains the forecast for a single metric.
type ForecastMetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent the forecast is for.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Metric name.
	MetricName string `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Forecast data points.
	Forecast []*ForecastPoint `protobuf:"bytes,4,rep,name=forecast,proto3" json:"forecast,omitempty"`
	// Model information.
	ModelInfo *ModelInfo `protobuf:"bytes,5,opt,name=model_info,json=modelInfo,proto3" json:"model_info,omitempty"`
	// Overall confidence score (0.0 - 1.0).
	OverallConfidence float32 `protobuf:"fixed32,6,opt,name=overall_confidence,json=overallConfidence,proto3" json:"overall_confidence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForecastMetricResponse) Reset() {
	*x = ForecastMetricResponse{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastMetricResponse) ProtoMessage() {}

func (x *ForecastMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastMetricResponse.ProtoReflect.Descriptor instead.
func (*ForecastMetricResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{1}
}

func (x *ForecastMetricResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ForecastMetricResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ForecastMetricResponse) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ForecastMetricResponse) GetForecast() []*ForecastPoint {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *ForecastMetricResponse) GetModelInfo() *ModelInfo {
	if x != nil {
		return x.ModelInfo
	}
	return nil
}

func (x *ForecastMetricResponse) GetOverallConfidence() float32 {
	if x != nil {
		return x.OverallConfidence
	}
	return 0
}

// ForecastPoint is a single point in a forecast.
type ForecastPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp for this forecast point.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Forecasted value.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// Confidence interval lower bound.
	LowerBound float32 `protobuf:"fixed32,3,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	// Confidence interval upper bound.
	UpperBound    float32 `protobuf:"fixed32,4,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastPoint) Reset() {
	*x = ForecastPoint{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastPoint) ProtoMessage() {}

func (x *ForecastPoint) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastPoint.ProtoReflect.Descriptor instead.
func (*ForecastPoint) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{2}
}

func (x *ForecastPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ForecastPoint) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ForecastPoint) GetLowerBound() float32 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *ForecastPoint) GetUpperBound() float32 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

// ModelInfo contains metadata about the forecasting model used.
type ModelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Best performing model name: "linear", "prophet", "xgboost", "ensemble".
	BestModel string `protobuf:"bytes,1,opt,name=best_model,json=bestModel,proto3" json:"best_model,omitempty"`
	// Model weights in the ensemble.
	Weights map[string]float32 `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Per-model MAPE (Mean Absolute Percentage Error).
	Accuracy map[string]float32 `protobuf:"bytes,3,rep,name=accuracy,proto3" json:"accuracy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Unix timestamp of last training.
	LastTrained int64 `protobuf:"varint,4,opt,name=last_trained,json=lastTrained,proto3" json:"last_trained,omitempty"`
	// Number of training data points used.
	TrainingSamples int64 `protobuf:"varint,5,opt,name=training_samples,json=trainingSamples,proto3" json:"training_samples,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{3}
}

func (x *ModelInfo) GetBestModel() string {
	if x != nil {
		return x.BestModel
	}
	return ""
}

func (x *ModelInfo) GetWeights() map[string]float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *ModelInfo) GetAccuracy() map[string]float32 {
	if x != nil {
		return x.Accuracy
	}
	return nil
}

func (x *ModelInfo) GetLastTrained() int64 {
	if x != nil {
		return x.LastTrained
	}
	return 0
}

func (x *ModelInfo) GetTrainingSamples() int64 {
	if x != nil {
		return x.TrainingSamples
	}
	return 0
}

// ForecastBatchRequest forecasts multiple metrics in one call.
type ForecastBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Requests      []*ForecastMetricRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastBatchRequest) Reset() {
	*x = ForecastBatchRequest{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastBatchRequest) ProtoMessage() {}

func (x *ForecastBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastBatchRequest.ProtoReflect.Descriptor instead.
func (*ForecastBatchRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{4}
}

func (x *ForecastBatchRequest) GetRequests() []*ForecastMetricRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// ForecastBatchResponse contains forecasts for all requested metrics.
type ForecastBatchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Forecasts     []*ForecastMetricResponse `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastBatchResponse) Reset() {
	*x = ForecastBatchResponse{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastBatchResponse) ProtoMessage() {}

func (x *ForecastBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastBatchResponse.ProtoReflect.Descriptor instead.
func (*ForecastBatchResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{5}
}

func (x *ForecastBatchResponse) GetForecasts() []*ForecastMetricResponse {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

// GetModelAccuracyRequest requests model accuracy information.
type GetModelAccuracyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric name to get accuracy for. Empty = all metrics.
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Tenant scope.
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelAccuracyRequest) Reset() {
	*x = GetModelAccuracyRequest{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelAccuracyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelAccuracyRequest) ProtoMessage() {}

func (x *GetModelAccuracyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelAccuracyRequest.ProtoReflect.Descriptor instead.
func (*GetModelAccuracyRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelAccuracyRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *GetModelAccuracyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetModelAccuracyResponse contains model accuracy data.
type GetModelAccuracyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of metric_name -> model info.
	Models        map[string]*ModelInfo `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelAccuracyResponse) Reset() {
	*x = GetModelAccuracyResponse{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelAccuracyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelAccuracyResponse) ProtoMessage() {}

func (x *GetModelAccuracyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelAccuracyResponse.ProtoReflect.Descriptor instead.
func (*GetModelAccuracyResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{7}
}

func (x *GetModelAccuracyResponse) GetModels() map[string]*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// RetrainModelsRequest triggers model retraining.
type RetrainModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric name to retrain. Empty = all metrics.
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Force retrain even if model is recent.
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrainModelsRequest) Reset() {
	*x = RetrainModelsRequest{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrainModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainModelsRequest) ProtoMessage() {}

func (x *RetrainModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainModelsRequest.ProtoReflect.Descriptor instead.
func (*RetrainModelsRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{8}
}

func (x *RetrainModelsRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *RetrainModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RetrainModelsRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RetrainModelsResponse confirms retraining status.
type RetrainModelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether retraining succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Updated model info per metric.
	UpdatedModels map[string]*ModelInfo `protobuf:"bytes,3,rep,name=updated_models,json=updatedModels,proto3" json:"updated_models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrainModelsResponse) Reset() {
	*x = RetrainModelsResponse{}
	mi := &file_paryty_v1_forecasting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrainModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainModelsResponse) ProtoMessage() {}

func (x *RetrainModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_forecasting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainModelsResponse.ProtoReflect.Descriptor instead.
func (*RetrainModelsResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_forecasting_proto_rawDescGZIP(), []int{9}
}

func (x *RetrainModelsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetrainModelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrainModelsResponse) GetUpdatedModels() map[string]*ModelInfo {
	if x != nil {
		return x.UpdatedModels
	}
	return nil
}

var File_paryty_v1_forecasting_proto protoreflect.FileDescriptor

const file_paryty_v1_forecasting_proto_rawDesc = "" +
	"\n" +
	"\x1bparyty/v1/forecasting.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xe7\x01\n" +
	"\x15ForecastMetricRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12'\n" +
	"\x0fhorizon_seconds\x18\x04 \x01(\x03R\x0ehorizonSeconds\x12)\n" +
	"\x10confidence_level\x18\x05 \x01(\x05R\x0fconfidenceLevel\x12!\n" +
	"\fstep_seconds\x18\x06 \x01(\x05R\vstepSeconds\"\x8b\x02\n" +
	"\x16ForecastMetricResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x124\n" +
	"\bforecast\x18\x04 \x03(\v2\x18.paryty.v1.ForecastPointR\bforecast\x123\n" +
	"\n" +
	"model_info\x18\x05 \x01(\v2\x14.paryty.v1.ModelInfoR\tmodelInfo\x12-\n" +
	"\x12overall_confidence\x18\x06 \x01(\x02R\x11overallConfidence\"\x85\x01\n" +
	"\rForecastPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x1f\n" +
	"\vlower_bound\x18\x03 \x01(\x02R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x04 \x01(\x02R\n" +
	"upperBound\"\xee\x02\n" +
	"\tModelInfo\x12\x1d\n" +
	"\n" +
	"best_model\x18\x01 \x01(\tR\tbestModel\x12;\n" +
	"\aweights\x18\x02 \x03(\v2!.paryty.v1.ModelInfo.WeightsEntryR\aweights\x12>\n" +
	"\baccuracy\x18\x03 \x03(\v2\".paryty.v1.ModelInfo.AccuracyEntryR\baccuracy\x12!\n" +
	"\flast_trained\x18\x04 \x01(\x03R\vlastTrained\x12)\n" +
	"\x10training_samples\x18\x05 \x01(\x03R\x0ftrainingSamples\x1a:\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a;\n" +
	"\rAccuracyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"T\n" +
	"\x14ForecastBatchRequest\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .paryty.v1.ForecastMetricRequestR\brequests\"X\n" +
	"\x15ForecastBatchResponse\x12?\n" +
	"\tforecasts\x18\x01 \x03(\v2!.paryty.v1.ForecastMetricResponseR\tforecasts\"W\n" +
	"\x17GetModelAccuracyRequest\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xb4\x01\n" +
	"\x18GetModelAccuracyResponse\x12G\n" +
	"\x06models\x18\x01 \x03(\v2/.paryty.v1.GetModelAccuracyResponse.ModelsEntryR\x06models\x1aO\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.paryty.v1.ModelInfoR\x05value:\x028\x01\"j\n" +
	"\x14RetrainModelsRequest\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xff\x01\n" +
	"\x15RetrainModelsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Z\n" +
	"\x0eupdated_models\x18\x03 \x03(\v23.paryty.v1.RetrainModelsResponse.UpdatedModelsEntryR\rupdatedModels\x1aV\n" +
	"\x12UpdatedModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.paryty.v1.ModelInfoR\x05value:\x028\x012\xf0\x02\n" +
	"\x12ForecastingService\x12U\n" +
	"\x0eForecastMetric\x12 .paryty.v1.ForecastMetricRequest\x1a!.paryty.v1.ForecastMetricResponse\x12R\n" +
	"\rForecastBatch\x12\x1f.paryty.v1.ForecastBatchRequest\x1a .paryty.v1.ForecastBatchResponse\x12[\n" +
	"\x10GetModelAccuracy\x12\".paryty.v1.GetModelAccuracyRequest\x1a#.paryty.v1.GetModelAccuracyResponse\x12R\n" +
	"\rRetrainModels\x12\x1f.paryty.v1.RetrainModelsRequest\x1a .paryty.v1.RetrainModelsResponseB?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_forecasting_proto_rawDescOnce sync.Once
	file_paryty_v1_forecasting_proto_rawDescData []byte
)

func file_paryty_v1_forecasting_proto_rawDescGZIP() []byte {
	file_paryty_v1_forecasting_proto_rawDescOnce.Do(func() {
		file_paryty_v1_forecasting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_forecasting_proto_rawDesc), len(file_paryty_v1_forecasting_proto_rawDesc)))
	})
	return file_paryty_v1_forecasting_proto_rawDescData
}

var file_paryty_v1_forecasting_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_paryty_v1_forecasting_proto_goTypes = []any{
	(*ForecastMetricRequest)(nil),    // 0: paryty.v1.ForecastMetricRequest
	(*ForecastMetricResponse)(nil),   // 1: paryty.v1.ForecastMetricResponse
	(*ForecastPoint)(nil),            // 2: paryty.v1.ForecastPoint
	(*ModelInfo)(nil),                // 3: paryty.v1.ModelInfo
	(*ForecastBatchRequest)(nil),     // 4: paryty.v1.ForecastBatchRequest
	(*ForecastBatchResponse)(nil),    // 5: paryty.v1.ForecastBatchResponse
	(*GetModelAccuracyRequest)(nil),  // 6: paryty.v1.GetModelAccuracyRequest
	(*GetModelAccuracyResponse)(nil), // 7: paryty.v1.GetModelAccuracyResponse
	(*RetrainModelsRequest)(nil),     // 8: paryty.v1.RetrainModelsRequest
	(*RetrainModelsResponse)(nil),    // 9: paryty.v1.RetrainModelsResponse
	nil,                              // 10: paryty.v1.ModelInfo.WeightsEntry
	nil,                              // 11: paryty.v1.ModelInfo.AccuracyEntry
	nil,                              // 12: paryty.v1.GetModelAccuracyResponse.ModelsEntry
	nil,                              // 13: paryty.v1.RetrainModelsResponse.UpdatedModelsEntry
}
var file_paryty_v1_forecasting_proto_depIdxs = []int32{
	2,  // 0: paryty.v1.ForecastMetricResponse.forecast:type_name -> paryty.v1.ForecastPoint
	3,  // 1: paryty.v1.ForecastMetricResponse.model_info:type_name -> paryty.v1.ModelInfo
	10, // 2: paryty.v1.ModelInfo.weights:type_name -> paryty.v1.ModelInfo.WeightsEntry
	11, // 3: paryty.v1.ModelInfo.accuracy:type_name -> paryty.v1.ModelInfo.AccuracyEntry
	0,  // 4: paryty.v1.ForecastBatchRequest.requests:type_name -> paryty.v1.ForecastMetricRequest
	1,  // 5: paryty.v1.ForecastBatchResponse.forecasts:type_name -> paryty.v1.ForecastMetricResponse
	12, // 6: paryty.v1.GetModelAccuracyResponse.models:type_name -> paryty.v1.GetModelAccuracyResponse.ModelsEntry
	13, // 7: paryty.v1.RetrainModelsResponse.updated_models:type_name -> paryty.v1.RetrainModelsResponse.UpdatedModelsEntry
	3,  // 8: paryty.v1.GetModelAccuracyResponse.ModelsEntry.value:type_name -> paryty.v1.ModelInfo
	3,  // 9: paryty.v1.RetrainModelsResponse.UpdatedModelsEntry.value:type_name -> paryty.v1.ModelInfo
	0,  // 10: paryty.v1.ForecastingService.ForecastMetric:input_type -> paryty.v1.ForecastMetricRequest
	4,  // 11: paryty.v1.ForecastingService.ForecastBatch:input_type -> paryty.v1.ForecastBatchRequest
	6,  // 12: paryty.v1.ForecastingService.GetModelAccuracy:input_type -> paryty.v1.GetModelAccuracyRequest
	8,  // 13: paryty.v1.ForecastingService.RetrainModels:input_type -> paryty.v1.RetrainModelsRequest
	1,  // 14: paryty.v1.ForecastingService.ForecastMetric:output_type -> paryty.v1.ForecastMetricResponse
	5,  // 15: paryty.v1.ForecastingService.ForecastBatch:output_type -> paryty.v1.ForecastBatchResponse
	7,  // 16: paryty.v1.ForecastingService.GetModelAccuracy:output_type -> paryty.v1.GetModelAccuracyResponse
	9,  // 17: paryty.v1.ForecastingService.RetrainModels:output_type -> paryty.v1.RetrainModelsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_paryty_v1_forecasting_proto_init() }
func file_paryty_v1_forecasting_proto_init() {
	if File_paryty_v1_forecasting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_forecasting_proto_rawDesc), len(file_paryty_v1_forecasting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paryty_v1_forecasting_proto_goTypes,
		DependencyIndexes: file_paryty_v1_forecasting_proto_depIdxs,
		MessageInfos:      file_paryty_v1_forecasting_proto_msgTypes,
	}.Build()
	File_paryty_v1_forecasting_proto = out.File
	file_paryty_v1_forecasting_proto_goTypes = nil
	file_paryty_v1_forecasting_proto_depIdxs = nil
}
