// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: paryty/v1/forecasting.proto

package parytyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForecastingService_ForecastMetric_FullMethodName   = "/paryty.v1.ForecastingService/ForecastMetric"
	ForecastingService_ForecastBatch_FullMethodName    = "/paryty.v1.ForecastingService/ForecastBatch"
	ForecastingService_GetModelAccuracy_FullMethodName = "/paryty.v1.ForecastingService/GetModelAccuracy"
	ForecastingService_RetrainModels_FullMethodName    = "/paryty.v1.ForecastingService/RetrainModels"
)

// ForecastingServiceClient is the client API for ForecastingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForecastingService provides ML-powered metric forecasting.
type ForecastingServiceClient interface {
	// Forecast a single metric for a given agent.
	ForecastMetric(ctx context.Context, in *ForecastMetricRequest, opts ...grpc.CallOption) (*ForecastMetricResponse, error)
	// Forecast multiple metrics in batch.
	ForecastBatch(ctx context.Context, in *ForecastBatchRequest, opts ...grpc.CallOption) (*ForecastBatchResponse, error)
	// Get model accuracy metrics.
	GetModelAccuracy(ctx context.Context, in *GetModelAccuracyRequest, opts ...grpc.CallOption) (*GetModelAccuracyResponse, error)
	// Trigger model retraining.
	RetrainModels(ctx context.Context, in *RetrainModelsRequest, opts ...grpc.CallOption) (*RetrainModelsResponse, error)
}

type forecastingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastingServiceClient(cc grpc.ClientConnInterface) ForecastingServiceClient {
	return &forecastingServiceClient{cc}
}

func (c *forecastingServiceClient) ForecastMetric(ctx context.Context, in *ForecastMetricRequest, opts ...grpc.CallOption) (*ForecastMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastMetricResponse)
	err := c.cc.Invoke(ctx, ForecastingService_ForecastMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) ForecastBatch(ctx context.Context, in *ForecastBatchRequest, opts ...grpc.CallOption) (*ForecastBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastBatchResponse)
	err := c.cc.Invoke(ctx, ForecastingService_ForecastBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) GetModelAccuracy(ctx context.Context, in *GetModelAccuracyRequest, opts ...grpc.CallOption) (*GetModelAccuracyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelAccuracyResponse)
	err := c.cc.Invoke(ctx, ForecastingService_GetModelAccuracy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) RetrainModels(ctx context.Context, in *RetrainModelsRequest, opts ...grpc.CallOption) (*RetrainModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrainModelsResponse)
	err := c.cc.Invoke(ctx, ForecastingService_RetrainModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastingServiceServer is the server API for ForecastingService service.
// All implementations must embed UnimplementedForecastingServiceServer
// for forward compatibility.
//
// ForecastingService provides ML-powered metric forecasting.
type ForecastingServiceServer interface {
	// Forecast a single metric for a given agent.
	ForecastMetric(context.Context, *ForecastMetricRequest) (*ForecastMetricResponse, error)
	// Forecast multiple metrics in batch.
	ForecastBatch(context.Context, *ForecastBatchRequest) (*ForecastBatchResponse, error)
	// Get model accuracy metrics.
	GetModelAccuracy(context.Context, *GetModelAccuracyRequest) (*GetModelAccuracyResponse, error)
	// Trigger model retraining.
	RetrainModels(context.Context, *RetrainModelsRequest) (*RetrainModelsResponse, error)
	mustEmbedUnimplementedForecastingServiceServer()
}

// UnimplementedForecastingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecastingServiceServer struct{}

func (UnimplementedForecastingServiceServer) ForecastMetric(context.Context, *ForecastMetricRequest) (*ForecastMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForecastMetric not implemented")
}
func (UnimplementedForecastingServiceServer) ForecastBatch(context.Context, *ForecastBatchRequest) (*ForecastBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForecastBatch not implemented")
}
func (UnimplementedForecastingServiceServer) GetModelAccuracy(context.Context, *GetModelAccuracyRequest) (*GetModelAccuracyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelAccuracy not implemented")
}
func (UnimplementedForecastingServiceServer) RetrainModels(context.Context, *RetrainModelsRequest) (*RetrainModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrainModels not implemented")
}
func (UnimplementedForecastingServiceServer) mustEmbedUnimplementedForecastingServiceServer() {}
func (UnimplementedForecastingServiceServer) testEmbeddedByValue()                            {}

// UnsafeForecastingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastingServiceServer will
// result in compilation errors.
type UnsafeForecastingServiceServer interface {
	mustEmbedUnimplementedForecastingServiceServer()
}

func RegisterForecastingServiceServer(s grpc.ServiceRegistrar, srv ForecastingServiceServer) {
	// If the following call panics, it indicates UnimplementedForecastingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForecastingService_ServiceDesc, srv)
}

func _ForecastingService_ForecastMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).ForecastMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_ForecastMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).ForecastMetric(ctx, req.(*ForecastMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_ForecastBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).ForecastBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_ForecastBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).ForecastBatch(ctx, req.(*ForecastBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_GetModelAccuracy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelAccuracyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).GetModelAccuracy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_GetModelAccuracy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).GetModelAccuracy(ctx, req.(*GetModelAccuracyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_RetrainModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrainModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).RetrainModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_RetrainModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).RetrainModels(ctx, req.(*RetrainModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForecastingService_ServiceDesc is the grpc.ServiceDesc for ForecastingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForecastingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paryty.v1.ForecastingService",
	HandlerType: (*ForecastingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForecastMetric",
			Handler:    _ForecastingService_ForecastMetric_Handler,
		},
		{
			MethodName: "ForecastBatch",
			Handler:    _ForecastingService_ForecastBatch_Handler,
		},
		{
			MethodName: "GetModelAccuracy",
			Handler:    _ForecastingService_GetModelAccuracy_Handler,
		},
		{
			MethodName: "RetrainModels",
			Handler:    _ForecastingService_RetrainModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paryty/v1/forecasting.proto",
}
