// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paryty/v1/pipeline.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PipelineStage identifies which stage produced a PipelineMessage.
type PipelineStage int32

const (
	PipelineStage_PIPELINE_STAGE_UNSPECIFIED PipelineStage = 0
	PipelineStage_PIPELINE_STAGE_AGGREGATOR  PipelineStage = 1
	PipelineStage_PIPELINE_STAGE_CORRELATOR  PipelineStage = 2
	PipelineStage_PIPELINE_STAGE_ENRICHER    PipelineStage = 3
)

// Enum value maps for PipelineStage.
var (
	PipelineStage_name = map[int32]string{
		0: "PIPELINE_STAGE_UNSPECIFIED",
		1: "PIPELINE_STAGE_AGGREGATOR",
		2: "PIPELINE_STAGE_CORRELATOR",
		3: "PIPELINE_STAGE_ENRICHER",
	}
	PipelineStage_value = map[string]int32{
		"PIPELINE_STAGE_UNSPECIFIED": 0,
		"PIPELINE_STAGE_AGGREGATOR":  1,
		"PIPELINE_STAGE_CORRELATOR":  2,
		"PIPELINE_STAGE_ENRICHER":    3,
	}
)

func (x PipelineStage) Enum() *PipelineStage {
	p := new(PipelineStage)
	*p = x
	return p
}

func (x PipelineStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineStage) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_pipeline_proto_enumTypes[0].Descriptor()
}

func (PipelineStage) Type() protoreflect.EnumType {
	return &file_paryty_v1_pipeline_proto_enumTypes[0]
}

func (x PipelineStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineStage.Descriptor instead.
func (PipelineStage) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

// PipelineMessage is the inter-stage message protocol for the processing
// pipeline. When PARYTY_PIPELINE_MODE=distributed, messages are serialized
// to Redpanda topics between stages instead of using in-process Go channels.
// In single mode (default), the oneof payload is used directly via
// Go channels for zero-copy inter-stage transfer.
type PipelineMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier for deduplication and tracing.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Tenant identifier for multi-tenant isolation.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The pipeline stage that produced this message.
	Stage PipelineStage `protobuf:"varint,3,opt,name=stage,proto3,enum=paryty.v1.PipelineStage" json:"stage,omitempty"`
	// When this message was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The stage-specific payload.
	Payload       *PipelinePayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineMessage) Reset() {
	*x = PipelineMessage{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineMessage) ProtoMessage() {}

func (x *PipelineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineMessage.ProtoReflect.Descriptor instead.
func (*PipelineMessage) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PipelineMessage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PipelineMessage) GetStage() PipelineStage {
	if x != nil {
		return x.Stage
	}
	return PipelineStage_PIPELINE_STAGE_UNSPECIFIED
}

func (x *PipelineMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PipelineMessage) GetPayload() *PipelinePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PipelinePayload carries the stage-specific data as a oneof.
type PipelinePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*PipelinePayload_Aggregated
	//	*PipelinePayload_Correlated
	//	*PipelinePayload_Enriched
	//	*PipelinePayload_Anomaly
	Data          isPipelinePayload_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelinePayload) Reset() {
	*x = PipelinePayload{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelinePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelinePayload) ProtoMessage() {}

func (x *PipelinePayload) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelinePayload.ProtoReflect.Descriptor instead.
func (*PipelinePayload) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *PipelinePayload) GetData() isPipelinePayload_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PipelinePayload) GetAggregated() *AggregatedMetrics {
	if x != nil {
		if x, ok := x.Data.(*PipelinePayload_Aggregated); ok {
			return x.Aggregated
		}
	}
	return nil
}

func (x *PipelinePayload) GetCorrelated() *CorrelatedMetrics {
	if x != nil {
		if x, ok := x.Data.(*PipelinePayload_Correlated); ok {
			return x.Correlated
		}
	}
	return nil
}

func (x *PipelinePayload) GetEnriched() *EnrichedMetrics {
	if x != nil {
		if x, ok := x.Data.(*PipelinePayload_Enriched); ok {
			return x.Enriched
		}
	}
	return nil
}

func (x *PipelinePayload) GetAnomaly() *AnomalyEvent {
	if x != nil {
		if x, ok := x.Data.(*PipelinePayload_Anomaly); ok {
			return x.Anomaly
		}
	}
	return nil
}

type isPipelinePayload_Data interface {
	isPipelinePayload_Data()
}

type PipelinePayload_Aggregated struct {
	// Aggregator output: windowed metric aggregations.
	Aggregated *AggregatedMetrics `protobuf:"bytes,1,opt,name=aggregated,proto3,oneof"`
}

type PipelinePayload_Correlated struct {
	// Correlator output: correlated metrics with dependency graph.
	Correlated *CorrelatedMetrics `protobuf:"bytes,2,opt,name=correlated,proto3,oneof"`
}

type PipelinePayload_Enriched struct {
	// Enricher output: enriched metrics with metadata.
	Enriched *EnrichedMetrics `protobuf:"bytes,3,opt,name=enriched,proto3,oneof"`
}

type PipelinePayload_Anomaly struct {
	// Anomaly payload: anomaly detection results from intelligence layer.
	Anomaly *AnomalyEvent `protobuf:"bytes,4,opt,name=anomaly,proto3,oneof"`
}

func (*PipelinePayload_Aggregated) isPipelinePayload_Data() {}

func (*PipelinePayload_Correlated) isPipelinePayload_Data() {}

func (*PipelinePayload_Enriched) isPipelinePayload_Data() {}

func (*PipelinePayload_Anomaly) isPipelinePayload_Data() {}

// AggregatedMetrics represents windowed metric aggregations from the
// aggregator stage. This is a lightweight proto representation of the
// internal models.AggregatedMetric type, suitable for serialization.
type AggregatedMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent that produced these metrics.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Metric name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON-encoded labels.
	Labels string `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	// Aggregation window in seconds.
	WindowSeconds int64 `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// Aggregation type: sum, avg, min, max, p50, p95, p99.
	AggType string `protobuf:"bytes,5,opt,name=agg_type,json=aggType,proto3" json:"agg_type,omitempty"`
	// Aggregated value.
	Value float64 `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	// Window end timestamp.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedMetrics) Reset() {
	*x = AggregatedMetrics{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetrics) ProtoMessage() {}

func (x *AggregatedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetrics.ProtoReflect.Descriptor instead.
func (*AggregatedMetrics) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *AggregatedMetrics) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AggregatedMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AggregatedMetrics) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *AggregatedMetrics) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *AggregatedMetrics) GetAggType() string {
	if x != nil {
		return x.AggType
	}
	return ""
}

func (x *AggregatedMetrics) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AggregatedMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CorrelatedMetrics represents the output of the correlator stage,
// including service dependencies and topology changes.
type CorrelatedMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent that correlated these metrics.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Service dependencies discovered.
	Dependencies []*Dependency `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Topology changes detected.
	TopologyChanges []*TopologyChange `protobuf:"bytes,3,rep,name=topology_changes,json=topologyChanges,proto3" json:"topology_changes,omitempty"`
	// Process services identified.
	ProcessServices []string `protobuf:"bytes,4,rep,name=process_services,json=processServices,proto3" json:"process_services,omitempty"`
	// Correlation timestamp.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelatedMetrics) Reset() {
	*x = CorrelatedMetrics{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelatedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelatedMetrics) ProtoMessage() {}

func (x *CorrelatedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelatedMetrics.ProtoReflect.Descriptor instead.
func (*CorrelatedMetrics) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *CorrelatedMetrics) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CorrelatedMetrics) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CorrelatedMetrics) GetTopologyChanges() []*TopologyChange {
	if x != nil {
		return x.TopologyChanges
	}
	return nil
}

func (x *CorrelatedMetrics) GetProcessServices() []string {
	if x != nil {
		return x.ProcessServices
	}
	return nil
}

func (x *CorrelatedMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Dependency represents a service-to-service dependency discovered
// by the correlator.
type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceService string                 `protobuf:"bytes,1,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *Dependency) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *Dependency) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *Dependency) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// TopologyChange represents a change in the service topology.
type TopologyChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChangeType    string                 `protobuf:"bytes,2,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyChange) Reset() {
	*x = TopologyChange{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyChange) ProtoMessage() {}

func (x *TopologyChange) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyChange.ProtoReflect.Descriptor instead.
func (*TopologyChange) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *TopologyChange) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TopologyChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *TopologyChange) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// EnrichedMetrics represents the output of the enricher stage,
// with metadata, labels, and correlation results attached.
type EnrichedMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent that produced these metrics.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Enriched metric batches (JSON-serialized for flexibility).
	MetricBatchJson string `protobuf:"bytes,2,opt,name=metric_batch_json,json=metricBatchJson,proto3" json:"metric_batch_json,omitempty"`
	// Correlation metadata.
	Correlation *CorrelatedMetrics `protobuf:"bytes,3,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Enrichment timestamp.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedMetrics) Reset() {
	*x = EnrichedMetrics{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedMetrics) ProtoMessage() {}

func (x *EnrichedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedMetrics.ProtoReflect.Descriptor instead.
func (*EnrichedMetrics) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichedMetrics) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedMetrics) GetMetricBatchJson() string {
	if x != nil {
		return x.MetricBatchJson
	}
	return ""
}

func (x *EnrichedMetrics) GetCorrelation() *CorrelatedMetrics {
	if x != nil {
		return x.Correlation
	}
	return nil
}

func (x *EnrichedMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// AnomalyEvent represents an anomaly detection result published by
// the intelligence layer and consumed by the pipeline for storage.
type AnomalyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique anomaly identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant scope.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Agent that produced the anomalous metrics.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Metric name that triggered the anomaly.
	MetricName string `protobuf:"bytes,4,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Anomaly severity: critical, warning, info.
	Severity string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	// Anomaly score: 0.0 (normal) to 1.0 (highly anomalous).
	Score float64 `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	// Expected value from the model.
	ExpectedValue float64 `protobuf:"fixed64,7,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	// Actual observed value.
	ActualValue float64 `protobuf:"fixed64,8,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	// Human-readable anomaly description.
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// When the anomaly was detected.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyEvent) Reset() {
	*x = AnomalyEvent{}
	mi := &file_paryty_v1_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyEvent) ProtoMessage() {}

func (x *AnomalyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyEvent.ProtoReflect.Descriptor instead.
func (*AnomalyEvent) Descriptor() ([]byte, []int) {
	return file_paryty_v1_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *AnomalyEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnomalyEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AnomalyEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AnomalyEvent) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *AnomalyEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnomalyEvent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnomalyEvent) GetExpectedValue() float64 {
	if x != nil {
		return x.ExpectedValue
	}
	return 0
}

func (x *AnomalyEvent) GetActualValue() float64 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *AnomalyEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnomalyEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_paryty_v1_pipeline_proto protoreflect.FileDescriptor

const file_paryty_v1_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x18paryty/v1/pipeline.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\x0fPipelineMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12.\n" +
	"\x05stage\x18\x03 \x01(\x0e2\x18.paryty.v1.PipelineStageR\x05stage\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x124\n" +
	"\apayload\x18\x05 \x01(\v2\x1a.paryty.v1.PipelinePayloadR\apayload\"\x88\x02\n" +
	"\x0fPipelinePayload\x12>\n" +
	"\n" +
	"aggregated\x18\x01 \x01(\v2\x1c.paryty.v1.AggregatedMetricsH\x00R\n" +
	"aggregated\x12>\n" +
	"\n" +
	"correlated\x18\x02 \x01(\v2\x1c.paryty.v1.CorrelatedMetricsH\x00R\n" +
	"correlated\x128\n" +
	"\benriched\x18\x03 \x01(\v2\x1a.paryty.v1.EnrichedMetricsH\x00R\benriched\x123\n" +
	"\aanomaly\x18\x04 \x01(\v2\x17.paryty.v1.AnomalyEventH\x00R\aanomalyB\x06\n" +
	"\x04data\"\xec\x01\n" +
	"\x11AggregatedMetrics\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x03 \x01(\tR\x06labels\x12%\n" +
	"\x0ewindow_seconds\x18\x04 \x01(\x03R\rwindowSeconds\x12\x19\n" +
	"\bagg_type\x18\x05 \x01(\tR\aaggType\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x94\x02\n" +
	"\x11CorrelatedMetrics\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\fdependencies\x18\x02 \x03(\v2\x15.paryty.v1.DependencyR\fdependencies\x12D\n" +
	"\x10topology_changes\x18\x03 \x03(\v2\x19.paryty.v1.TopologyChangeR\x0ftopologyChanges\x12)\n" +
	"\x10process_services\x18\x04 \x03(\tR\x0fprocessServices\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"v\n" +
	"\n" +
	"Dependency\x12%\n" +
	"\x0esource_service\x18\x01 \x01(\tR\rsourceService\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x84\x01\n" +
	"\x0eTopologyChange\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\tR\n" +
	"changeType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd2\x01\n" +
	"\x0fEnrichedMetrics\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11metric_batch_json\x18\x02 \x01(\tR\x0fmetricBatchJson\x12>\n" +
	"\vcorrelation\x18\x03 \x01(\v2\x1c.paryty.v1.CorrelatedMetricsR\vcorrelation\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcf\x02\n" +
	"\fAnomalyEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1f\n" +
	"\vmetric_name\x18\x04 \x01(\tR\n" +
	"metricName\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12%\n" +
	"\x0eexpected_value\x18\a \x01(\x01R\rexpectedValue\x12!\n" +
	"\factual_value\x18\b \x01(\x01R\vactualValue\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\x8a\x01\n" +
	"\rPipelineStage\x12\x1e\n" +
	"\x1aPIPELINE_STAGE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PIPELINE_STAGE_AGGREGATOR\x10\x01\x12\x1d\n" +
	"\x19PIPELINE_STAGE_CORRELATOR\x10\x02\x12\x1b\n" +
	"\x17PIPELINE_STAGE_ENRICHER\x10\x03B?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_pipeline_proto_rawDescOnce sync.Once
	file_paryty_v1_pipeline_proto_rawDescData []byte
)

func file_paryty_v1_pipeline_proto_rawDescGZIP() []byte {
	file_paryty_v1_pipeline_proto_rawDescOnce.Do(func() {
		file_paryty_v1_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_pipeline_proto_rawDesc), len(file_paryty_v1_pipeline_proto_rawDesc)))
	})
	return file_paryty_v1_pipeline_proto_rawDescData
}

var file_paryty_v1_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paryty_v1_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_paryty_v1_pipeline_proto_goTypes = []any{
	(PipelineStage)(0),            // 0: paryty.v1.PipelineStage
	(*PipelineMessage)(nil),       // 1: paryty.v1.PipelineMessage
	(*PipelinePayload)(nil),       // 2: paryty.v1.PipelinePayload
	(*AggregatedMetrics)(nil),     // 3: paryty.v1.AggregatedMetrics
	(*CorrelatedMetrics)(nil),     // 4: paryty.v1.CorrelatedMetrics
	(*Dependency)(nil),            // 5: paryty.v1.Dependency
	(*TopologyChange)(nil),        // 6: paryty.v1.TopologyChange
	(*EnrichedMetrics)(nil),       // 7: paryty.v1.EnrichedMetrics
	(*AnomalyEvent)(nil),          // 8: paryty.v1.AnomalyEvent
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_paryty_v1_pipeline_proto_depIdxs = []int32{
	0,  // 0: paryty.v1.PipelineMessage.stage:type_name -> paryty.v1.PipelineStage
	9,  // 1: paryty.v1.PipelineMessage.created_at:type_name -> google.protobuf.Timestamp
	2,  // 2: paryty.v1.PipelineMessage.payload:type_name -> paryty.v1.PipelinePayload
	3,  // 3: paryty.v1.PipelinePayload.aggregated:type_name -> paryty.v1.AggregatedMetrics
	4,  // 4: paryty.v1.PipelinePayload.correlated:type_name -> paryty.v1.CorrelatedMetrics
	7,  // 5: paryty.v1.PipelinePayload.enriched:type_name -> paryty.v1.EnrichedMetrics
	8,  // 6: paryty.v1.PipelinePayload.anomaly:type_name -> paryty.v1.AnomalyEvent
	9,  // 7: paryty.v1.AggregatedMetrics.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 8: paryty.v1.CorrelatedMetrics.dependencies:type_name -> paryty.v1.Dependency
	6,  // 9: paryty.v1.CorrelatedMetrics.topology_changes:type_name -> paryty.v1.TopologyChange
	9,  // 10: paryty.v1.CorrelatedMetrics.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 11: paryty.v1.TopologyChange.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 12: paryty.v1.EnrichedMetrics.correlation:type_name -> paryty.v1.CorrelatedMetrics
	9,  // 13: paryty.v1.EnrichedMetrics.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 14: paryty.v1.AnomalyEvent.timestamp:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_paryty_v1_pipeline_proto_init() }
func file_paryty_v1_pipeline_proto_init() {
	if File_paryty_v1_pipeline_proto != nil {
		return
	}
	file_paryty_v1_pipeline_proto_msgTypes[1].OneofWrappers = []any{
		(*PipelinePayload_Aggregated)(nil),
		(*PipelinePayload_Correlated)(nil),
		(*PipelinePayload_Enriched)(nil),
		(*PipelinePayload_Anomaly)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_pipeline_proto_rawDesc), len(file_paryty_v1_pipeline_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paryty_v1_pipeline_proto_goTypes,
		DependencyIndexes: file_paryty_v1_pipeline_proto_depIdxs,
		EnumInfos:         file_paryty_v1_pipeline_proto_enumTypes,
		MessageInfos:      file_paryty_v1_pipeline_proto_msgTypes,
	}.Build()
	File_paryty_v1_pipeline_proto = out.File
	file_paryty_v1_pipeline_proto_goTypes = nil
	file_paryty_v1_pipeline_proto_depIdxs = nil
}
