// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: paryty/v1/simulation.proto

package parytyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationService_RunScenario_FullMethodName       = "/paryty.v1.SimulationService/RunScenario"
	SimulationService_ListScenarios_FullMethodName     = "/paryty.v1.SimulationService/ListScenarios"
	SimulationService_GetScenarioStatus_FullMethodName = "/paryty.v1.SimulationService/GetScenarioStatus"
	SimulationService_CancelScenario_FullMethodName    = "/paryty.v1.SimulationService/CancelScenario"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulationService provides what-if analysis and chaos engineering.
type SimulationServiceClient interface {
	// Run a what-if scenario.
	RunScenario(ctx context.Context, in *RunScenarioRequest, opts ...grpc.CallOption) (*RunScenarioResponse, error)
	// List available scenarios.
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
	// Get scenario execution status.
	GetScenarioStatus(ctx context.Context, in *GetScenarioStatusRequest, opts ...grpc.CallOption) (*GetScenarioStatusResponse, error)
	// Cancel a running scenario.
	CancelScenario(ctx context.Context, in *CancelScenarioRequest, opts ...grpc.CallOption) (*CancelScenarioResponse, error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) RunScenario(ctx context.Context, in *RunScenarioRequest, opts ...grpc.CallOption) (*RunScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScenarioResponse)
	err := c.cc.Invoke(ctx, SimulationService_RunScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, SimulationService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetScenarioStatus(ctx context.Context, in *GetScenarioStatusRequest, opts ...grpc.CallOption) (*GetScenarioStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScenarioStatusResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetScenarioStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) CancelScenario(ctx context.Context, in *CancelScenarioRequest, opts ...grpc.CallOption) (*CancelScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelScenarioResponse)
	err := c.cc.Invoke(ctx, SimulationService_CancelScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
// All implementations must embed UnimplementedSimulationServiceServer
// for forward compatibility.
//
// SimulationService provides what-if analysis and chaos engineering.
type SimulationServiceServer interface {
	// Run a what-if scenario.
	RunScenario(context.Context, *RunScenarioRequest) (*RunScenarioResponse, error)
	// List available scenarios.
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error)
	// Get scenario execution status.
	GetScenarioStatus(context.Context, *GetScenarioStatusRequest) (*GetScenarioStatusResponse, error)
	// Cancel a running scenario.
	CancelScenario(context.Context, *CancelScenarioRequest) (*CancelScenarioResponse, error)
	mustEmbedUnimplementedSimulationServiceServer()
}

// UnimplementedSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) RunScenario(context.Context, *RunScenarioRequest) (*RunScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScenario not implemented")
}
func (UnimplementedSimulationServiceServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedSimulationServiceServer) GetScenarioStatus(context.Context, *GetScenarioStatusRequest) (*GetScenarioStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScenarioStatus not implemented")
}
func (UnimplementedSimulationServiceServer) CancelScenario(context.Context, *CancelScenarioRequest) (*CancelScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelScenario not implemented")
}
func (UnimplementedSimulationServiceServer) mustEmbedUnimplementedSimulationServiceServer() {}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_RunScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).RunScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_RunScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).RunScenario(ctx, req.(*RunScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetScenarioStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenarioStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetScenarioStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetScenarioStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetScenarioStatus(ctx, req.(*GetScenarioStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_CancelScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CancelScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_CancelScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CancelScenario(ctx, req.(*CancelScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paryty.v1.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunScenario",
			Handler:    _SimulationService_RunScenario_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _SimulationService_ListScenarios_Handler,
		},
		{
			MethodName: "GetScenarioStatus",
			Handler:    _SimulationService_GetScenarioStatus_Handler,
		},
		{
			MethodName: "CancelScenario",
			Handler:    _SimulationService_CancelScenario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paryty/v1/simulation.proto",
}
