// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paryty/v1/simulation.proto

package parytyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeType classifies the type of infrastructure change.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_HOST        ChangeType = 1
	ChangeType_CHANGE_TYPE_CONTAINER   ChangeType = 2
	ChangeType_CHANGE_TYPE_SERVICE     ChangeType = 3
	ChangeType_CHANGE_TYPE_NETWORK     ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_HOST",
		2: "CHANGE_TYPE_CONTAINER",
		3: "CHANGE_TYPE_SERVICE",
		4: "CHANGE_TYPE_NETWORK",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_HOST":        1,
		"CHANGE_TYPE_CONTAINER":   2,
		"CHANGE_TYPE_SERVICE":     3,
		"CHANGE_TYPE_NETWORK":     4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_simulation_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_paryty_v1_simulation_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{0}
}

// TrafficType classifies traffic source.
type TrafficType int32

const (
	TrafficType_TRAFFIC_TYPE_UNSPECIFIED TrafficType = 0
	TrafficType_TRAFFIC_TYPE_SIMULATED   TrafficType = 1
	// V2.0: production traffic replay
	TrafficType_TRAFFIC_TYPE_REPLAY TrafficType = 2
	// V2.0: production traffic mirror
	TrafficType_TRAFFIC_TYPE_MIRROR TrafficType = 3
)

// Enum value maps for TrafficType.
var (
	TrafficType_name = map[int32]string{
		0: "TRAFFIC_TYPE_UNSPECIFIED",
		1: "TRAFFIC_TYPE_SIMULATED",
		2: "TRAFFIC_TYPE_REPLAY",
		3: "TRAFFIC_TYPE_MIRROR",
	}
	TrafficType_value = map[string]int32{
		"TRAFFIC_TYPE_UNSPECIFIED": 0,
		"TRAFFIC_TYPE_SIMULATED":   1,
		"TRAFFIC_TYPE_REPLAY":      2,
		"TRAFFIC_TYPE_MIRROR":      3,
	}
)

func (x TrafficType) Enum() *TrafficType {
	p := new(TrafficType)
	*p = x
	return p
}

func (x TrafficType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficType) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_simulation_proto_enumTypes[1].Descriptor()
}

func (TrafficType) Type() protoreflect.EnumType {
	return &file_paryty_v1_simulation_proto_enumTypes[1]
}

func (x TrafficType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficType.Descriptor instead.
func (TrafficType) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{1}
}

// ScenarioStatus represents scenario execution state.
type ScenarioStatus int32

const (
	ScenarioStatus_SCENARIO_STATUS_UNSPECIFIED ScenarioStatus = 0
	ScenarioStatus_SCENARIO_STATUS_PENDING     ScenarioStatus = 1
	ScenarioStatus_SCENARIO_STATUS_RUNNING     ScenarioStatus = 2
	ScenarioStatus_SCENARIO_STATUS_COMPLETE    ScenarioStatus = 3
	ScenarioStatus_SCENARIO_STATUS_FAILED      ScenarioStatus = 4
	ScenarioStatus_SCENARIO_STATUS_CANCELED    ScenarioStatus = 5
)

// Enum value maps for ScenarioStatus.
var (
	ScenarioStatus_name = map[int32]string{
		0: "SCENARIO_STATUS_UNSPECIFIED",
		1: "SCENARIO_STATUS_PENDING",
		2: "SCENARIO_STATUS_RUNNING",
		3: "SCENARIO_STATUS_COMPLETE",
		4: "SCENARIO_STATUS_FAILED",
		5: "SCENARIO_STATUS_CANCELED",
	}
	ScenarioStatus_value = map[string]int32{
		"SCENARIO_STATUS_UNSPECIFIED": 0,
		"SCENARIO_STATUS_PENDING":     1,
		"SCENARIO_STATUS_RUNNING":     2,
		"SCENARIO_STATUS_COMPLETE":    3,
		"SCENARIO_STATUS_FAILED":      4,
		"SCENARIO_STATUS_CANCELED":    5,
	}
)

func (x ScenarioStatus) Enum() *ScenarioStatus {
	p := new(ScenarioStatus)
	*p = x
	return p
}

func (x ScenarioStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScenarioStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_paryty_v1_simulation_proto_enumTypes[2].Descriptor()
}

func (ScenarioStatus) Type() protoreflect.EnumType {
	return &file_paryty_v1_simulation_proto_enumTypes[2]
}

func (x ScenarioStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScenarioStatus.Descriptor instead.
func (ScenarioStatus) EnumDescriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{2}
}

// RunScenarioRequest starts a what-if simulation.
type RunScenarioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scenario definition.
	Scenario *WhatIfScenario `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	// Tenant scope.
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScenarioRequest) Reset() {
	*x = RunScenarioRequest{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScenarioRequest) ProtoMessage() {}

func (x *RunScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScenarioRequest.ProtoReflect.Descriptor instead.
func (*RunScenarioRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *RunScenarioRequest) GetScenario() *WhatIfScenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *RunScenarioRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// RunScenarioResponse contains simulation results.
type RunScenarioResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scenario execution result.
	Result        *SimulationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScenarioResponse) Reset() {
	*x = RunScenarioResponse{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScenarioResponse) ProtoMessage() {}

func (x *RunScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScenarioResponse.ProtoReflect.Descriptor instead.
func (*RunScenarioResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *RunScenarioResponse) GetResult() *SimulationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// WhatIfScenario defines a simulation scenario.
type WhatIfScenario struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique scenario ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the scenario.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Infrastructure changes to simulate.
	Changes []*InfraChange `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	// Traffic pattern for the simulation.
	Traffic *TrafficPattern `protobuf:"bytes,5,opt,name=traffic,proto3" json:"traffic,omitempty"`
	// Simulation duration.
	Duration *durationpb.Duration `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// Metrics to track during simulation.
	Metrics []string `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Tags for categorization.
	Tags          map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhatIfScenario) Reset() {
	*x = WhatIfScenario{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhatIfScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatIfScenario) ProtoMessage() {}

func (x *WhatIfScenario) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatIfScenario.ProtoReflect.Descriptor instead.
func (*WhatIfScenario) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *WhatIfScenario) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhatIfScenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WhatIfScenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WhatIfScenario) GetChanges() []*InfraChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *WhatIfScenario) GetTraffic() *TrafficPattern {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *WhatIfScenario) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *WhatIfScenario) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *WhatIfScenario) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// InfraChange represents a proposed infrastructure change.
type InfraChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of resource to change.
	Type ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=paryty.v1.ChangeType" json:"type,omitempty"`
	// Target service/host/container.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Action: "add", "remove", "scale".
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Number of instances.
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Additional configuration.
	Config        map[string]string `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfraChange) Reset() {
	*x = InfraChange{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfraChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfraChange) ProtoMessage() {}

func (x *InfraChange) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfraChange.ProtoReflect.Descriptor instead.
func (*InfraChange) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *InfraChange) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *InfraChange) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InfraChange) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InfraChange) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InfraChange) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// TrafficPattern defines simulated traffic.
type TrafficPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traffic type.
	Type TrafficType `protobuf:"varint,1,opt,name=type,proto3,enum=paryty.v1.TrafficType" json:"type,omitempty"`
	// Requests per second.
	Rps int32 `protobuf:"varint,2,opt,name=rps,proto3" json:"rps,omitempty"`
	// Duration of the traffic pattern.
	Duration *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	// Traffic profile: "steady", "ramp", "spike", "wave".
	Profile       string `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPattern) Reset() {
	*x = TrafficPattern{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPattern) ProtoMessage() {}

func (x *TrafficPattern) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPattern.ProtoReflect.Descriptor instead.
func (*TrafficPattern) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficPattern) GetType() TrafficType {
	if x != nil {
		return x.Type
	}
	return TrafficType_TRAFFIC_TYPE_UNSPECIFIED
}

func (x *TrafficPattern) GetRps() int32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *TrafficPattern) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TrafficPattern) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// SimulationResult contains the results of a simulation.
type SimulationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scenario ID.
	ScenarioId string `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	// Execution status.
	Status ScenarioStatus `protobuf:"varint,2,opt,name=status,proto3,enum=paryty.v1.ScenarioStatus" json:"status,omitempty"`
	// Start time.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Metric values over simulation duration.
	Metrics map[string]*FloatArray `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// High-level summary.
	Summary *SimulationSummary `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	// Breaking point (if detected).
	BreakingPoint *BreakingPoint `protobuf:"bytes,7,opt,name=breaking_point,json=breakingPoint,proto3" json:"breaking_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationResult) Reset() {
	*x = SimulationResult{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResult) ProtoMessage() {}

func (x *SimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResult.ProtoReflect.Descriptor instead.
func (*SimulationResult) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *SimulationResult) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SimulationResult) GetStatus() ScenarioStatus {
	if x != nil {
		return x.Status
	}
	return ScenarioStatus_SCENARIO_STATUS_UNSPECIFIED
}

func (x *SimulationResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SimulationResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SimulationResult) GetMetrics() map[string]*FloatArray {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SimulationResult) GetSummary() *SimulationSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SimulationResult) GetBreakingPoint() *BreakingPoint {
	if x != nil {
		return x.BreakingPoint
	}
	return nil
}

// SimulationSummary provides a high-level result summary.
type SimulationSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total simulated requests.
	TotalRequests int64 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// Success rate (0.0 - 1.0).
	SuccessRate float32 `protobuf:"fixed32,2,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	// Average latency in milliseconds.
	AvgLatencyMs float32 `protobuf:"fixed32,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	// P99 latency in milliseconds.
	P99LatencyMs float32 `protobuf:"fixed32,4,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	// Maximum CPU usage observed.
	MaxCpu float32 `protobuf:"fixed32,5,opt,name=max_cpu,json=maxCpu,proto3" json:"max_cpu,omitempty"`
	// Maximum memory usage observed.
	MaxMemory float32 `protobuf:"fixed32,6,opt,name=max_memory,json=maxMemory,proto3" json:"max_memory,omitempty"`
	// Estimated monthly cost.
	CostEstimate float32 `protobuf:"fixed32,7,opt,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	// Generated recommendations.
	Recommendations []string `protobuf:"bytes,8,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationSummary) Reset() {
	*x = SimulationSummary{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationSummary) ProtoMessage() {}

func (x *SimulationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationSummary.ProtoReflect.Descriptor instead.
func (*SimulationSummary) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *SimulationSummary) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *SimulationSummary) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *SimulationSummary) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *SimulationSummary) GetP99LatencyMs() float32 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *SimulationSummary) GetMaxCpu() float32 {
	if x != nil {
		return x.MaxCpu
	}
	return 0
}

func (x *SimulationSummary) GetMaxMemory() float32 {
	if x != nil {
		return x.MaxMemory
	}
	return 0
}

func (x *SimulationSummary) GetCostEstimate() float32 {
	if x != nil {
		return x.CostEstimate
	}
	return 0
}

func (x *SimulationSummary) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// BreakingPoint represents where the system fails.
type BreakingPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RPS at breaking point.
	Rps int32 `protobuf:"varint,1,opt,name=rps,proto3" json:"rps,omitempty"`
	// P99 latency at breaking point in milliseconds.
	LatencyMs float32 `protobuf:"fixed32,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Error rate at breaking point.
	ErrorRate float32 `protobuf:"fixed32,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// What broke first: "cpu", "memory", "disk", "network".
	Bottleneck string `protobuf:"bytes,4,opt,name=bottleneck,proto3" json:"bottleneck,omitempty"`
	// Recommendations to avoid the breaking point.
	Recommendations []string `protobuf:"bytes,5,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BreakingPoint) Reset() {
	*x = BreakingPoint{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakingPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakingPoint) ProtoMessage() {}

func (x *BreakingPoint) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakingPoint.ProtoReflect.Descriptor instead.
func (*BreakingPoint) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *BreakingPoint) GetRps() int32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *BreakingPoint) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *BreakingPoint) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *BreakingPoint) GetBottleneck() string {
	if x != nil {
		return x.Bottleneck
	}
	return ""
}

func (x *BreakingPoint) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// ListScenariosRequest lists available scenarios.
type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *ListScenariosRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListScenariosResponse returns available scenarios.
type ListScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*WhatIfScenario      `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResponse) Reset() {
	*x = ListScenariosResponse{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResponse) ProtoMessage() {}

func (x *ListScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *ListScenariosResponse) GetScenarios() []*WhatIfScenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

// GetScenarioStatusRequest checks scenario execution status.
type GetScenarioStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioStatusRequest) Reset() {
	*x = GetScenarioStatusRequest{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioStatusRequest) ProtoMessage() {}

func (x *GetScenarioStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioStatusRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioStatusRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{10}
}

func (x *GetScenarioStatusRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

// GetScenarioStatusResponse returns scenario status.
type GetScenarioStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Status     ScenarioStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=paryty.v1.ScenarioStatus" json:"status,omitempty"`
	// Progress: 0.0 - 1.0.
	Progress float32 `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	// Partial results (if running).
	PartialResult *SimulationResult `protobuf:"bytes,4,opt,name=partial_result,json=partialResult,proto3" json:"partial_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioStatusResponse) Reset() {
	*x = GetScenarioStatusResponse{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioStatusResponse) ProtoMessage() {}

func (x *GetScenarioStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioStatusResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioStatusResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{11}
}

func (x *GetScenarioStatusResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GetScenarioStatusResponse) GetStatus() ScenarioStatus {
	if x != nil {
		return x.Status
	}
	return ScenarioStatus_SCENARIO_STATUS_UNSPECIFIED
}

func (x *GetScenarioStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetScenarioStatusResponse) GetPartialResult() *SimulationResult {
	if x != nil {
		return x.PartialResult
	}
	return nil
}

// CancelScenarioRequest cancels a running scenario.
type CancelScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScenarioRequest) Reset() {
	*x = CancelScenarioRequest{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScenarioRequest) ProtoMessage() {}

func (x *CancelScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScenarioRequest.ProtoReflect.Descriptor instead.
func (*CancelScenarioRequest) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{12}
}

func (x *CancelScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

// CancelScenarioResponse confirms cancellation.
type CancelScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScenarioResponse) Reset() {
	*x = CancelScenarioResponse{}
	mi := &file_paryty_v1_simulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScenarioResponse) ProtoMessage() {}

func (x *CancelScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paryty_v1_simulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScenarioResponse.ProtoReflect.Descriptor instead.
func (*CancelScenarioResponse) Descriptor() ([]byte, []int) {
	return file_paryty_v1_simulation_proto_rawDescGZIP(), []int{13}
}

func (x *CancelScenarioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelScenarioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_paryty_v1_simulation_proto protoreflect.FileDescriptor

const file_paryty_v1_simulation_proto_rawDesc = "" +
	"\n" +
	"\x1aparyty/v1/simulation.proto\x12\tparyty.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x16paryty/v1/common.proto\x1a\x17paryty/v1/anomaly.proto\"h\n" +
	"\x12RunScenarioRequest\x125\n" +
	"\bscenario\x18\x01 \x01(\v2\x19.paryty.v1.WhatIfScenarioR\bscenario\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"J\n" +
	"\x13RunScenarioResponse\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.paryty.v1.SimulationResultR\x06result\"\x80\x03\n" +
	"\x0eWhatIfScenario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\achanges\x18\x04 \x03(\v2\x16.paryty.v1.InfraChangeR\achanges\x123\n" +
	"\atraffic\x18\x05 \x01(\v2\x19.paryty.v1.TrafficPatternR\atraffic\x125\n" +
	"\bduration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x18\n" +
	"\ametrics\x18\a \x03(\tR\ametrics\x127\n" +
	"\x04tags\x18\b \x03(\v2#.paryty.v1.WhatIfScenario.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\vInfraChange\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.paryty.v1.ChangeTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12:\n" +
	"\x06config\x18\x05 \x03(\v2\".paryty.v1.InfraChange.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x0eTrafficPattern\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.paryty.v1.TrafficTypeR\x04type\x12\x10\n" +
	"\x03rps\x18\x02 \x01(\x05R\x03rps\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\"\xe8\x03\n" +
	"\x10SimulationResult\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.paryty.v1.ScenarioStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12B\n" +
	"\ametrics\x18\x05 \x03(\v2(.paryty.v1.SimulationResult.MetricsEntryR\ametrics\x126\n" +
	"\asummary\x18\x06 \x01(\v2\x1c.paryty.v1.SimulationSummaryR\asummary\x12?\n" +
	"\x0ebreaking_point\x18\a \x01(\v2\x18.paryty.v1.BreakingPointR\rbreakingPoint\x1aQ\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.paryty.v1.FloatArrayR\x05value:\x028\x01\"\xb0\x02\n" +
	"\x11SimulationSummary\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12!\n" +
	"\fsuccess_rate\x18\x02 \x01(\x02R\vsuccessRate\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x02R\favgLatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x04 \x01(\x02R\fp99LatencyMs\x12\x17\n" +
	"\amax_cpu\x18\x05 \x01(\x02R\x06maxCpu\x12\x1d\n" +
	"\n" +
	"max_memory\x18\x06 \x01(\x02R\tmaxMemory\x12#\n" +
	"\rcost_estimate\x18\a \x01(\x02R\fcostEstimate\x12(\n" +
	"\x0frecommendations\x18\b \x03(\tR\x0frecommendations\"\xa9\x01\n" +
	"\rBreakingPoint\x12\x10\n" +
	"\x03rps\x18\x01 \x01(\x05R\x03rps\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x02R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x02R\terrorRate\x12\x1e\n" +
	"\n" +
	"bottleneck\x18\x04 \x01(\tR\n" +
	"bottleneck\x12(\n" +
	"\x0frecommendations\x18\x05 \x03(\tR\x0frecommendations\"3\n" +
	"\x14ListScenariosRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"P\n" +
	"\x15ListScenariosResponse\x127\n" +
	"\tscenarios\x18\x01 \x03(\v2\x19.paryty.v1.WhatIfScenarioR\tscenarios\";\n" +
	"\x18GetScenarioStatusRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"\xcf\x01\n" +
	"\x19GetScenarioStatusResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.paryty.v1.ScenarioStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x02R\bprogress\x12B\n" +
	"\x0epartial_result\x18\x04 \x01(\v2\x1b.paryty.v1.SimulationResultR\rpartialResult\"8\n" +
	"\x15CancelScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"L\n" +
	"\x16CancelScenarioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8c\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHANGE_TYPE_HOST\x10\x01\x12\x19\n" +
	"\x15CHANGE_TYPE_CONTAINER\x10\x02\x12\x17\n" +
	"\x13CHANGE_TYPE_SERVICE\x10\x03\x12\x17\n" +
	"\x13CHANGE_TYPE_NETWORK\x10\x04*y\n" +
	"\vTrafficType\x12\x1c\n" +
	"\x18TRAFFIC_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRAFFIC_TYPE_SIMULATED\x10\x01\x12\x17\n" +
	"\x13TRAFFIC_TYPE_REPLAY\x10\x02\x12\x17\n" +
	"\x13TRAFFIC_TYPE_MIRROR\x10\x03*\xc3\x01\n" +
	"\x0eScenarioStatus\x12\x1f\n" +
	"\x1bSCENARIO_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SCENARIO_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17SCENARIO_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18SCENARIO_STATUS_COMPLETE\x10\x03\x12\x1a\n" +
	"\x16SCENARIO_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18SCENARIO_STATUS_CANCELED\x10\x052\xec\x02\n" +
	"\x11SimulationService\x12L\n" +
	"\vRunScenario\x12\x1d.paryty.v1.RunScenarioRequest\x1a\x1e.paryty.v1.RunScenarioResponse\x12R\n" +
	"\rListScenarios\x12\x1f.paryty.v1.ListScenariosRequest\x1a .paryty.v1.ListScenariosResponse\x12^\n" +
	"\x11GetScenarioStatus\x12#.paryty.v1.GetScenarioStatusRequest\x1a$.paryty.v1.GetScenarioStatusResponse\x12U\n" +
	"\x0eCancelScenario\x12 .paryty.v1.CancelScenarioRequest\x1a!.paryty.v1.CancelScenarioResponseB?Z=github.com/paryty/paryty-v1.0/cluster/internal/proto;parytyv1b\x06proto3"

var (
	file_paryty_v1_simulation_proto_rawDescOnce sync.Once
	file_paryty_v1_simulation_proto_rawDescData []byte
)

func file_paryty_v1_simulation_proto_rawDescGZIP() []byte {
	file_paryty_v1_simulation_proto_rawDescOnce.Do(func() {
		file_paryty_v1_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paryty_v1_simulation_proto_rawDesc), len(file_paryty_v1_simulation_proto_rawDesc)))
	})
	return file_paryty_v1_simulation_proto_rawDescData
}

var file_paryty_v1_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_paryty_v1_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_paryty_v1_simulation_proto_goTypes = []any{
	(ChangeType)(0),                   // 0: paryty.v1.ChangeType
	(TrafficType)(0),                  // 1: paryty.v1.TrafficType
	(ScenarioStatus)(0),               // 2: paryty.v1.ScenarioStatus
	(*RunScenarioRequest)(nil),        // 3: paryty.v1.RunScenarioRequest
	(*RunScenarioResponse)(nil),       // 4: paryty.v1.RunScenarioResponse
	(*WhatIfScenario)(nil),            // 5: paryty.v1.WhatIfScenario
	(*InfraChange)(nil),               // 6: paryty.v1.InfraChange
	(*TrafficPattern)(nil),            // 7: paryty.v1.TrafficPattern
	(*SimulationResult)(nil),          // 8: paryty.v1.SimulationResult
	(*SimulationSummary)(nil),         // 9: paryty.v1.SimulationSummary
	(*BreakingPoint)(nil),             // 10: paryty.v1.BreakingPoint
	(*ListScenariosRequest)(nil),      // 11: paryty.v1.ListScenariosRequest
	(*ListScenariosResponse)(nil),     // 12: paryty.v1.ListScenariosResponse
	(*GetScenarioStatusRequest)(nil),  // 13: paryty.v1.GetScenarioStatusRequest
	(*GetScenarioStatusResponse)(nil), // 14: paryty.v1.GetScenarioStatusResponse
	(*CancelScenarioRequest)(nil),     // 15: paryty.v1.CancelScenarioRequest
	(*CancelScenarioResponse)(nil),    // 16: paryty.v1.CancelScenarioResponse
	nil,                               // 17: paryty.v1.WhatIfScenario.TagsEntry
	nil,                               // 18: paryty.v1.InfraChange.ConfigEntry
	nil,                               // 19: paryty.v1.SimulationResult.MetricsEntry
	(*durationpb.Duration)(nil),       // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
	(*FloatArray)(nil),                // 22: paryty.v1.FloatArray
}
var file_paryty_v1_simulation_proto_depIdxs = []int32{
	5,  // 0: paryty.v1.RunScenarioRequest.scenario:type_name -> paryty.v1.WhatIfScenario
	8,  // 1: paryty.v1.RunScenarioResponse.result:type_name -> paryty.v1.SimulationResult
	6,  // 2: paryty.v1.WhatIfScenario.changes:type_name -> paryty.v1.InfraChange
	7,  // 3: paryty.v1.WhatIfScenario.traffic:type_name -> paryty.v1.TrafficPattern
	20, // 4: paryty.v1.WhatIfScenario.duration:type_name -> google.protobuf.Duration
	17, // 5: paryty.v1.WhatIfScenario.tags:type_name -> paryty.v1.WhatIfScenario.TagsEntry
	0,  // 6: paryty.v1.InfraChange.type:type_name -> paryty.v1.ChangeType
	18, // 7: paryty.v1.InfraChange.config:type_name -> paryty.v1.InfraChange.ConfigEntry
	1,  // 8: paryty.v1.TrafficPattern.type:type_name -> paryty.v1.TrafficType
	20, // 9: paryty.v1.TrafficPattern.duration:type_name -> google.protobuf.Duration
	2,  // 10: paryty.v1.SimulationResult.status:type_name -> paryty.v1.ScenarioStatus
	21, // 11: paryty.v1.SimulationResult.start_time:type_name -> google.protobuf.Timestamp
	21, // 12: paryty.v1.SimulationResult.end_time:type_name -> google.protobuf.Timestamp
	19, // 13: paryty.v1.SimulationResult.metrics:type_name -> paryty.v1.SimulationResult.MetricsEntry
	9,  // 14: paryty.v1.SimulationResult.summary:type_name -> paryty.v1.SimulationSummary
	10, // 15: paryty.v1.SimulationResult.breaking_point:type_name -> paryty.v1.BreakingPoint
	5,  // 16: paryty.v1.ListScenariosResponse.scenarios:type_name -> paryty.v1.WhatIfScenario
	2,  // 17: paryty.v1.GetScenarioStatusResponse.status:type_name -> paryty.v1.ScenarioStatus
	8,  // 18: paryty.v1.GetScenarioStatusResponse.partial_result:type_name -> paryty.v1.SimulationResult
	22, // 19: paryty.v1.SimulationResult.MetricsEntry.value:type_name -> paryty.v1.FloatArray
	3,  // 20: paryty.v1.SimulationService.RunScenario:input_type -> paryty.v1.RunScenarioRequest
	11, // 21: paryty.v1.SimulationService.ListScenarios:input_type -> paryty.v1.ListScenariosRequest
	13, // 22: paryty.v1.SimulationService.GetScenarioStatus:input_type -> paryty.v1.GetScenarioStatusRequest
	15, // 23: paryty.v1.SimulationService.CancelScenario:input_type -> paryty.v1.CancelScenarioRequest
	4,  // 24: paryty.v1.SimulationService.RunScenario:output_type -> paryty.v1.RunScenarioResponse
	12, // 25: paryty.v1.SimulationService.ListScenarios:output_type -> paryty.v1.ListScenariosResponse
	14, // 26: paryty.v1.SimulationService.GetScenarioStatus:output_type -> paryty.v1.GetScenarioStatusResponse
	16, // 27: paryty.v1.SimulationService.CancelScenario:output_type -> paryty.v1.CancelScenarioResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_paryty_v1_simulation_proto_init() }
func file_paryty_v1_simulation_proto_init() {
	if File_paryty_v1_simulation_proto != nil {
		return
	}
	file_paryty_v1_common_proto_init()
	file_paryty_v1_anomaly_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paryty_v1_simulation_proto_rawDesc), len(file_paryty_v1_simulation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paryty_v1_simulation_proto_goTypes,
		DependencyIndexes: file_paryty_v1_simulation_proto_depIdxs,
		EnumInfos:         file_paryty_v1_simulation_proto_enumTypes,
		MessageInfos:      file_paryty_v1_simulation_proto_msgTypes,
	}.Build()
	File_paryty_v1_simulation_proto = out.File
	file_paryty_v1_simulation_proto_goTypes = nil
	file_paryty_v1_simulation_proto_depIdxs = nil
}
