// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: paryty/v1/timeline.proto

package parytyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimelineEngineService_CreateSnapshot_FullMethodName = "/paryty.v1.TimelineEngineService/CreateSnapshot"
	TimelineEngineService_ListSnapshots_FullMethodName  = "/paryty.v1.TimelineEngineService/ListSnapshots"
	TimelineEngineService_GetSnapshot_FullMethodName    = "/paryty.v1.TimelineEngineService/GetSnapshot"
	TimelineEngineService_DiffSnapshots_FullMethodName  = "/paryty.v1.TimelineEngineService/DiffSnapshots"
	TimelineEngineService_StartReplay_FullMethodName    = "/paryty.v1.TimelineEngineService/StartReplay"
	TimelineEngineService_ExportReport_FullMethodName   = "/paryty.v1.TimelineEngineService/ExportReport"
	TimelineEngineService_TagSnapshot_FullMethodName    = "/paryty.v1.TimelineEngineService/TagSnapshot"
)

// TimelineEngineServiceClient is the client API for TimelineEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimelineEngineService provides snapshot management, replay, diff, and export.
type TimelineEngineServiceClient interface {
	// Create a system state snapshot.
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// List available snapshots.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// Get a specific snapshot.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// Diff two snapshots.
	DiffSnapshots(ctx context.Context, in *DiffSnapshotsRequest, opts ...grpc.CallOption) (*DiffSnapshotsResponse, error)
	// Start a replay session.
	StartReplay(ctx context.Context, in *StartReplayRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplayFrame], error)
	// Export a snapshot or report.
	ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// Tag a snapshot.
	TagSnapshot(ctx context.Context, in *TagSnapshotRequest, opts ...grpc.CallOption) (*TagSnapshotResponse, error)
}

type timelineEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineEngineServiceClient(cc grpc.ClientConnInterface) TimelineEngineServiceClient {
	return &timelineEngineServiceClient{cc}
}

func (c *timelineEngineServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineEngineServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineEngineServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineEngineServiceClient) DiffSnapshots(ctx context.Context, in *DiffSnapshotsRequest, opts ...grpc.CallOption) (*DiffSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffSnapshotsResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_DiffSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineEngineServiceClient) StartReplay(ctx context.Context, in *StartReplayRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplayFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TimelineEngineService_ServiceDesc.Streams[0], TimelineEngineService_StartReplay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartReplayRequest, ReplayFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineEngineService_StartReplayClient = grpc.ServerStreamingClient[ReplayFrame]

func (c *timelineEngineServiceClient) ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_ExportReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineEngineServiceClient) TagSnapshot(ctx context.Context, in *TagSnapshotRequest, opts ...grpc.CallOption) (*TagSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagSnapshotResponse)
	err := c.cc.Invoke(ctx, TimelineEngineService_TagSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimelineEngineServiceServer is the server API for TimelineEngineService service.
// All implementations must embed UnimplementedTimelineEngineServiceServer
// for forward compatibility.
//
// TimelineEngineService provides snapshot management, replay, diff, and export.
type TimelineEngineServiceServer interface {
	// Create a system state snapshot.
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// List available snapshots.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// Get a specific snapshot.
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// Diff two snapshots.
	DiffSnapshots(context.Context, *DiffSnapshotsRequest) (*DiffSnapshotsResponse, error)
	// Start a replay session.
	StartReplay(*StartReplayRequest, grpc.ServerStreamingServer[ReplayFrame]) error
	// Export a snapshot or report.
	ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error)
	// Tag a snapshot.
	TagSnapshot(context.Context, *TagSnapshotRequest) (*TagSnapshotResponse, error)
	mustEmbedUnimplementedTimelineEngineServiceServer()
}

// UnimplementedTimelineEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimelineEngineServiceServer struct{}

func (UnimplementedTimelineEngineServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedTimelineEngineServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedTimelineEngineServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedTimelineEngineServiceServer) DiffSnapshots(context.Context, *DiffSnapshotsRequest) (*DiffSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffSnapshots not implemented")
}
func (UnimplementedTimelineEngineServiceServer) StartReplay(*StartReplayRequest, grpc.ServerStreamingServer[ReplayFrame]) error {
	return status.Error(codes.Unimplemented, "method StartReplay not implemented")
}
func (UnimplementedTimelineEngineServiceServer) ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportReport not implemented")
}
func (UnimplementedTimelineEngineServiceServer) TagSnapshot(context.Context, *TagSnapshotRequest) (*TagSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagSnapshot not implemented")
}
func (UnimplementedTimelineEngineServiceServer) mustEmbedUnimplementedTimelineEngineServiceServer() {}
func (UnimplementedTimelineEngineServiceServer) testEmbeddedByValue()                               {}

// UnsafeTimelineEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineEngineServiceServer will
// result in compilation errors.
type UnsafeTimelineEngineServiceServer interface {
	mustEmbedUnimplementedTimelineEngineServiceServer()
}

func RegisterTimelineEngineServiceServer(s grpc.ServiceRegistrar, srv TimelineEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedTimelineEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimelineEngineService_ServiceDesc, srv)
}

func _TimelineEngineService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineEngineService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineEngineService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineEngineService_DiffSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).DiffSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_DiffSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).DiffSnapshots(ctx, req.(*DiffSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineEngineService_StartReplay_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartReplayRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimelineEngineServiceServer).StartReplay(m, &grpc.GenericServerStream[StartReplayRequest, ReplayFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TimelineEngineService_StartReplayServer = grpc.ServerStreamingServer[ReplayFrame]

func _TimelineEngineService_ExportReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).ExportReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_ExportReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).ExportReport(ctx, req.(*ExportReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineEngineService_TagSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineEngineServiceServer).TagSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineEngineService_TagSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineEngineServiceServer).TagSnapshot(ctx, req.(*TagSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimelineEngineService_ServiceDesc is the grpc.ServiceDesc for TimelineEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paryty.v1.TimelineEngineService",
	HandlerType: (*TimelineEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshot",
			Handler:    _TimelineEngineService_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _TimelineEngineService_ListSnapshots_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _TimelineEngineService_GetSnapshot_Handler,
		},
		{
			MethodName: "DiffSnapshots",
			Handler:    _TimelineEngineService_DiffSnapshots_Handler,
		},
		{
			MethodName: "ExportReport",
			Handler:    _TimelineEngineService_ExportReport_Handler,
		},
		{
			MethodName: "TagSnapshot",
			Handler:    _TimelineEngineService_TagSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartReplay",
			Handler:       _TimelineEngineService_StartReplay_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "paryty/v1/timeline.proto",
}
