apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paryty-intelligence
  labels:
    app.kubernetes.io/component: intelligence
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: intelligence
