apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paryty-pipeline
  labels:
    app.kubernetes.io/component: pipeline
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pipeline
