apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paryty-ingestion
  labels:
    app.kubernetes.io/component: ingestion
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ingestion
