apiVersion: v1
kind: Service
metadata:
  name: paryty-ingestion
  labels:
    app.kubernetes.io/component: ingestion
spec:
  ports:
    - port: 8080
      name: grpc
      targetPort: grpc
    - port: 8081
      name: health
      targetPort: health
  selector:
    app.kubernetes.io/component: ingestion
