apiVersion: v1
kind: Service
metadata:
  name: paryty-pipeline
  namespace: paryty
  labels:
    app.kubernetes.io/name: paryty-pipeline
    app.kubernetes.io/component: pipeline
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: paryty-pipeline
