apiVersion: v1
kind: Service
metadata:
  name: {{ include "paryty.fullname" . }}-ingestion
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      name: grpc
      targetPort: grpc
    - port: {{ .Values.service.health.port }}
      name: health
      targetPort: health
  selector:
    {{- include "paryty.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
