{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "paryty.fullname" . }}-pipeline
  labels:
    {{- include "paryty.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "paryty.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pipeline
{{- end }}