package api

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	"github.com/paryty/paryty-v1.0/cluster/internal/storage"
	"github.com/twmb/franz-go/pkg/kgo"
	"go.uber.org/zap"
)

// newUpgrader builds a websocket.Upgrader whose origin policy mirrors the
// HTTP CORS configuration. With no configured origins, ALL connections are
// rejected (secure-by-default). To allow localhost for development, explicitly
// configure it in the allowed origins list. With explicit origins, cross-origin
// upgrade attempts from unlisted origins are rejected — defense-in-depth against
// cross-site WebSocket hijacking on top of the mandatory JWT.
func newUpgrader(allowedOrigins []string, logger *zap.Logger) websocket.Upgrader {
	if len(allowedOrigins) == 0 {
		logger.Warn("WebSocket origin check: no allowed origins configured, rejecting all connections")
	}
	return websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool {
			if len(allowedOrigins) == 0 {
				// Secure-by-default: reject all connections when no origins are
				// explicitly configured. To allow localhost for development,
				// add "http://localhost:3000" to the allowed origins list.
				return false
			}
			origin := r.Header.Get("Origin")
			if origin == "" {
				// Non-browser clients (no Origin header) are allowed; they
				// cannot be victims of cross-site request forgery.
				return true
			}
			for _, allowed := range allowedOrigins {
				if strings.EqualFold(origin, allowed) {
					return true
				}
			}
			return false
		},
	}
}

// clientState holds per-connection metadata including tenant and subscriptions.
type clientState struct {
	tenant        string
	subscriptions map[string]bool // channel → subscribed?
}

// WebSocketHandler handles WebSocket connections.
type WebSocketHandler struct {
	store       *storage.Store
	logger      *zap.Logger
	upgrader    websocket.Upgrader
	clients     sync.Map // map[*websocket.Conn]*clientState
	broadcast   chan []byte
	eventFanout chan tenantScopedMessage // fan-in from Redpanda events consumer
	mu          sync.RWMutex
}

// tenantScopedMessage carries a serialized WS payload together with the
// tenant it belongs to, so the fanout loop can enforce tenant isolation.
type tenantScopedMessage struct {
	tenant string
	data   []byte
}

// NewWebSocketHandler creates a new WebSocket handler. allowedOrigins
// mirrors the HTTP CORS allow-list. When empty, ALL WebSocket connections
// are rejected (secure-by-default) — configure explicit origins for production.
func NewWebSocketHandler(store *storage.Store, logger *zap.Logger, allowedOrigins []string) *WebSocketHandler {
	h := &WebSocketHandler{
		store:       store,
		logger:      logger,
		upgrader:    newUpgrader(allowedOrigins, logger),
		broadcast:   make(chan []byte, 256),
		eventFanout: make(chan tenantScopedMessage, 256),
	}
	go h.broadcastLoop()
	go h.eventFanoutLoop()
	return h
}

// HandleWebSocket handles WebSocket upgrade and message handling.
// Requires JWT auth (GinJWTAuthFlexible — token query param supported because
// the browser WebSocket API cannot set headers). The connection's tenant scope
// comes from the validated JWT claims, never from client-supplied parameters.
func (h *WebSocketHandler) HandleWebSocket(c *gin.Context) {
	tenant, ok := requireTenant(c)
	if !ok {
		return
	}

	conn, err := h.upgrader.Upgrade(c.Writer, c.Request, nil)
	if err != nil {
		h.logger.Error("WebSocket upgrade failed", zap.Error(err))
		return
	}
	defer conn.Close()

	state := &clientState{
		tenant:        tenant,
		subscriptions: make(map[string]bool),
	}

	h.clients.Store(conn, state)
	h.logger.Info("Client connected",
		zap.String("remote", conn.RemoteAddr().String()),
		zap.String("tenant", tenant),
	)

	defer func() {
		h.clients.Delete(conn)
		h.logger.Info("Client disconnected", zap.String("remote", conn.RemoteAddr().String()))
	}()

	// Read messages (subscriptions)
	for {
		_, message, err := conn.ReadMessage()
		if err != nil {
			// BUGFIX: Treat common transient close codes as normal disconnects
			// instead of errors. 1005 (no status) and 1006 (abnormal closure)
			// are generated by the WebSocket library when the peer disconnects
			// without sending a proper close frame — expected during page
			// navigation, network interruptions, or client-side reconnection.
			if websocket.IsUnexpectedCloseError(err,
				websocket.CloseGoingAway,       // 1001
				websocket.CloseNormalClosure,   // 1000
				websocket.CloseNoStatusReceived, // 1005
				websocket.CloseAbnormalClosure,  // 1006
			) {
				h.logger.Warn("WebSocket unexpected close", zap.Error(err))
			}
			break
		}

		var msg WSMessage
		if err := json.Unmarshal(message, &msg); err != nil {
			h.logger.Error("Invalid message", zap.Error(err))
			continue
		}

		h.handleMessage(conn, state, &msg)
	}
}

// WSMessage represents a WebSocket message.
// Accepts both "channel" (frontend) and "topic" (legacy) fields.
type WSMessage struct {
	Type    string          `json:"type"`
	Channel string          `json:"channel"`
	Topic   string          `json:"topic"`
	ID      string          `json:"id"`
	Payload json.RawMessage `json:"payload"`
}

// topic returns the effective topic, preferring channel over topic.
func (m *WSMessage) effectiveTopic() string {
	if m.Channel != "" {
		return m.Channel
	}
	return m.Topic
}

// WSResponse represents a WebSocket response matching the frontend's WsIncomingMessage format.
type WSResponse struct {
	Type    string      `json:"type"`
	Channel string      `json:"channel"`
	Data    interface{} `json:"data"`
	ID      string      `json:"id,omitempty"`
	Time    time.Time   `json:"timestamp"`
}

func (h *WebSocketHandler) handleMessage(conn *websocket.Conn, state *clientState, msg *WSMessage) {
	topic := msg.effectiveTopic()
	switch msg.Type {
	case "subscribe":
		h.handleSubscribe(conn, state, state.tenant, topic)
	case "unsubscribe":
		h.handleUnsubscribe(state, topic)
	case "ping":
		h.sendMessage(conn, &WSResponse{
			Type: "pong",
			Time: time.Now(),
		})
	default:
		h.logger.Warn("Unknown message type", zap.String("type", msg.Type))
	}
}

func (h *WebSocketHandler) handleSubscribe(conn *websocket.Conn, state *clientState, tenant, topic string) {
	h.logger.Info("Client subscribed",
		zap.String("tenant", tenant),
		zap.String("topic", topic),
	)

	// Track subscription in per-client state
	state.subscriptions[topic] = true

	// Send initial data based on topic
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	switch topic {
	case "topology":
		topo, err := h.store.GetTopology(ctx, tenant)
		if err == nil && topo != nil {
			h.sendMessage(conn, &WSResponse{
				Type:    "topology",
				Channel: topic,
				Data:    toFrontendTopology(topo),
				Time:    time.Now(),
			})
		}
	case "alerts":
		alerts, err := h.store.GetActiveAlerts(ctx, tenant)
		if err == nil {
			h.sendMessage(conn, &WSResponse{
				Type:    "alerts",
				Channel: topic,
				Data:    alerts,
				Time:    time.Now(),
			})
		}
	case "events":
		// Events are streaming-only — no initial data.
		// REST handles catch-up via EventQuery.
	}
}

func (h *WebSocketHandler) handleUnsubscribe(state *clientState, topic string) {
	h.logger.Info("Client unsubscribed", zap.String("topic", topic))
	delete(state.subscriptions, topic)
}

func (h *WebSocketHandler) sendMessage(conn *websocket.Conn, msg *WSResponse) {
	data, err := json.Marshal(msg)
	if err != nil {
		h.logger.Error("Marshal message failed", zap.Error(err))
		return
	}
	conn.WriteMessage(websocket.TextMessage, data) //nolint:errcheck
}

// Broadcast sends a message to all connected clients.
func (h *WebSocketHandler) Broadcast(topic string, payload interface{}) {
	msg := &WSResponse{
		Type:    "update",
		Channel: topic,
		Data:    payload,
		Time:    time.Now(),
	}
	data, err := json.Marshal(msg)
	if err != nil {
		h.logger.Error("Marshal broadcast failed", zap.Error(err))
		return
	}
	h.broadcast <- data
}

func (h *WebSocketHandler) broadcastLoop() {
	for msg := range h.broadcast {
		h.clients.Range(func(key, value interface{}) bool {
			conn := key.(*websocket.Conn)
			if err := conn.WriteMessage(websocket.TextMessage, msg); err != nil {
				h.logger.Error("Broadcast failed", zap.Error(err))
				conn.Close()
				h.clients.Delete(conn)
			}
			return true
		})
	}
}

// eventFanoutLoop fans out Redpanda events only to clients that are
// subscribed to "events" AND belong to the message's tenant. Tenant
// filtering here is mandatory — without it one tenant's events would be
// visible to every connected client.
func (h *WebSocketHandler) eventFanoutLoop() {
	for msg := range h.eventFanout {
		h.clients.Range(func(key, value interface{}) bool {
			conn := key.(*websocket.Conn)
			state := value.(*clientState)
			if state.tenant == msg.tenant && state.subscriptions["events"] {
				if err := conn.WriteMessage(websocket.TextMessage, msg.data); err != nil {
					h.logger.Error("Event fanout failed", zap.Error(err))
					conn.Close()
					h.clients.Delete(conn)
				}
			}
			return true
		})
	}
}

// StartEventConsumer creates a franz-go consumer reading from the events topic
// and fans out event messages via eventFanout to subscribed WebSocket clients.
func (h *WebSocketHandler) StartEventConsumer(ctx context.Context, brokers []string, tenant string) error {
	topic := "paryty." + tenant + ".events"

	client, err := kgo.NewClient(
		kgo.SeedBrokers(brokers...),
		kgo.ConsumerGroup("ws-event-fanout-"+tenant),
		kgo.ConsumeTopics(topic),
	)
	if err != nil {
		return err
	}

	h.logger.Info("Event consumer started",
		zap.String("topic", topic),
		zap.Strings("brokers", brokers),
	)

	go func() {
		defer client.Close()
		for {
			select {
			case <-ctx.Done():
				return
			default:
			}

			fetches := client.PollFetches(ctx)
			if fetches.IsClientClosed() {
				return
			}
			if errs := fetches.Errors(); len(errs) > 0 {
				h.logger.Error("Event consumer fetch errors", zap.Int("count", len(errs)))
				continue
			}

			fetches.EachRecord(func(record *kgo.Record) {
				msg := &WSResponse{
					Type:    "update",
					Channel: "events",
					Data:    json.RawMessage(record.Value),
					Time:    time.Now(),
				}
				data, err := json.Marshal(msg)
				if err != nil {
					h.logger.Error("Marshal event failed", zap.Error(err))
					return
				}
				select {
				case h.eventFanout <- tenantScopedMessage{tenant: tenant, data: data}:
				default:
					// Drop if fanout channel is full (backpressure)
				}
			})
		}
	}()

	return nil
}
