// Protocol Buffer generated code
// This file is auto-generated by tonic-build from proto/paryty/v1/*.proto
// Do NOT edit manually — regenerate with: cargo build (uses build.rs)

#![allow(dead_code)]
#![allow(clippy::all)]

// Protocol Buffer generated code
// Generated by tonic-build from proto/paryty/v1/*.proto
// Re-run `cargo build` (with protoc available) to regenerate.

mod generated {
    include!("paryty.v1.rs");
}

// Re-export all generated types at module level
pub use generated::*;

// Re-export under paryty::v1 namespace for proto-idiomatic access
pub mod paryty {
    pub mod v1 {
        pub use super::super::generated::*;
    }
}
